// GENERATED by tools/var89-generate.mjs from tools/var89-matrix.mjs — do not hand-edit this folder.
// This is animations/we-dont-care-gamble-superbot-89be2ca4/ with the values below; every other file in the folder is that spot unchanged.
export default {
  "id": "grok-sportsbook-superbot-cae00e0c",
  "voice": "Grok",
  "introLine": "Grok says you shouldn't gamble",
  "redWord": "gamble",
  "slamLine": "WE DONT CARE!",
  "ask": "Make a website of all my DraftKings wins",
  "say": "On it. Pulling every settled bet that paid.",
  "workTitle": "DraftKings wins site",
  "site": {
    "slug": "sams-sportsbook.site",
    "hero": "All my DraftKings wins",
    "sub": "1,046 bets · every graded leg · paid at the closing line",
    "totalDisplay": "$12,780",
    "chartLabel": "CUMULATIVE PROFIT",
    "hitsLabel": "TOP PAYOUTS",
    "hitsTitle": "Biggest hits",
    "rows": [
      [
        "4-leg NFL parlay",
        4900
      ],
      [
        "Chiefs, Sunday night",
        2830
      ],
      [
        "Celtics moneyline",
        2150
      ],
      [
        "Yankees, over 8.5",
        1600
      ],
      [
        "PGA outright, 40/1",
        1300
      ]
    ],
    "night": {
      "label": "Wild card weekend",
      "amount": 3900,
      "sub": "Three tickets, three sweat-free endings"
    }
  },
  "steps": [
    "Synced 1,046 settled bets from your sportsbook",
    "Graded every parlay leg at the closing line",
    "Totaled the wins, biggest hits first",
    "Built and deployed sams-sportsbook.site"
  ]
};
