/* data.js - nine mid-century couches for sale near the searcher, gathered from five local marketplaces.
   Every listing is one object: photo, ask, size, the neighbourhood it sits in, how far the drive is,
   when it was posted, how fast the seller answers, and the platform it came from. The list, the map
   pins, the summary strip and the hub aggregation card all read these same objects.

   The pieces of furniture are fictional, the sellers are unnamed, the prices, streets and times are
   invented. The photos are sourced photos of real mid-century sofas (see CREDITS.txt). */

export const search = {
  ask: 'Find me a mid-century couch under $800 within 20 miles',
  radiusMiles: 20,
  homeLabel: 'You, Eastwood',
  read: 486,
  kept: 38,
  shown: 9,
  median: 612,
  cheapest: 275,
  fastestReply: '12 min',
  refreshed: '09:41 today',
  city: 'Louisville, KY',
};

export const platforms = [
  { id: 'facebook', name: 'Facebook Marketplace', short: 'Facebook', logo: './brand/facebook.svg', count: 178, note: 'Local pickup only, cash or card at the door.' },
  { id: 'craigslist', name: 'Craigslist', short: 'Craigslist', logo: './brand/craigslist.svg', count: 96, note: 'Email replies, no listing photos are re-hosted here.' },
  { id: 'offerup', name: 'OfferUp', short: 'OfferUp', logo: './brand/offerup.svg', count: 121, note: 'In-app chat, the seller answers in the same thread.' },
  { id: 'nextdoor', name: 'Nextdoor', short: 'Nextdoor', logo: './brand/nextdoor.svg', count: 54, note: 'Neighbours only, most of these are within 3 miles.' },
  { id: 'ebay', name: 'eBay', short: 'eBay', logo: './brand/ebay.svg', count: 37, note: 'Local pickup listings, the deposit goes through eBay.' },
];

export const filters = [
  { key: 'all', label: 'All 9 shown' },
  { key: 'under600', label: 'Under $600' },
  { key: 'fiveMiles', label: 'Within 5 miles' },
  { key: 'leather', label: 'Leather' },
  { key: 'twoSeat', label: 'Two seat' },
  { key: 'fastReply', label: 'Answers in an hour' },
];

/* map coordinates are percentages inside the map plate, 0,0 the top left corner.
   They are invented, like the streets the diagram draws. */
const raw = [
  {
    id: 'olive-3seat',
    img: './img/couch-olive.jpg',
    title: 'Olive three seat sofa, walnut arms',
    fabric: 'Wool blend, olive',
    seat: 'Three seat',
    lengthIn: 84,
    price: 640,
    year: 1962,
    neighbour: 'Clifton',
    miles: 2.4,
    posted: 'posted 2h ago',
    reply: 'answers in 12 min',
    replyMin: 12,
    platform: 'facebook',
    condition: 'No wear on the arms, one seam in the back cushion',
    tags: ['Pickup only', 'Curb at 1320 Hepburn Ave'],
    saves: 14,
    pin: { x: 46, y: 40 },
    story: 'Bought for a back room in 1998 and barely used since.',
  },
  {
    id: 'rust-3seat',
    img: './img/couch-rust.jpg',
    title: 'Rust orange three seat couch',
    fabric: 'Woven wool, rust',
    seat: 'Three seat',
    lengthIn: 78,
    price: 520,
    year: 1968,
    neighbour: 'Germantown',
    miles: 3.9,
    posted: 'posted 5h ago',
    reply: 'answers in 3h',
    replyMin: 180,
    platform: 'craigslist',
    condition: 'Frame is solid, fabric sun faded on the left cushion',
    tags: ['Cash only', 'Second floor walk up'],
    saves: 22,
    pin: { x: 33, y: 63 },
    story: 'Came out of a house on East Oak that just sold.',
  },
  {
    id: 'cream-tuxedo',
    img: './img/couch-cream.jpg',
    title: 'Cream tufted tuxedo sofa',
    fabric: 'Cotton velvet, cream',
    seat: 'Three seat',
    lengthIn: 82,
    price: 780,
    year: 1960,
    neighbour: 'Highlands',
    miles: 6.1,
    posted: 'posted yesterday',
    reply: 'answers in 40 min',
    replyMin: 40,
    platform: 'offerup',
    condition: 'Buttons all intact, one small mark under the seat cushion',
    tags: ['Pickup only', 'Has the matching chair for $200'],
    saves: 31,
    pin: { x: 62, y: 30 },
    story: 'Their grandmother had it recovered in 1974, still the original frame.',
  },
  {
    id: 'teal-loveseat',
    img: './img/couch-teal.jpg',
    title: 'Teal two seat loveseat, oak frame',
    fabric: 'Wool, teal green',
    seat: 'Two seat',
    lengthIn: 58,
    price: 275,
    year: 1965,
    neighbour: 'Shelby Park',
    miles: 4.6,
    posted: 'posted 6h ago',
    reply: 'answers in 25 min',
    replyMin: 25,
    platform: 'offerup',
    condition: 'Visible wear on the seat cushion, frame and webbing are sound',
    tags: ['Fits a small car', 'Porch pickup'],
    saves: 46,
    pin: { x: 55, y: 66 },
    story: 'Priced to leave the studio before the new lease starts.',
  },
  {
    id: 'ivory-vinyl',
    img: './img/couch-ivory.jpg',
    title: 'Ivory vinyl sofa on a chrome base',
    fabric: 'Vinyl, ivory',
    seat: 'Three seat',
    lengthIn: 76,
    price: 395,
    year: 1970,
    neighbour: 'Bonnycastle',
    miles: 8.3,
    posted: 'posted 2d ago',
    reply: 'answers in 5h',
    replyMin: 300,
    platform: 'ebay',
    condition: 'Vinyl is whole, the chrome has light scratches',
    tags: ['Local pickup', 'Deposit through eBay'],
    saves: 9,
    pin: { x: 40, y: 24 },
    story: 'Listed with a buy it now price and pickup in the alley behind the shop.',
  },
  {
    id: 'caramel-leather',
    img: './img/couch-caramel.jpg',
    title: 'Danish caramel leather sofa, teak legs',
    fabric: 'Leather, caramel',
    seat: 'Three seat',
    lengthIn: 80,
    price: 740,
    year: 1966,
    neighbour: 'St Matthews',
    miles: 11.2,
    posted: 'posted yesterday',
    reply: 'answers in 55 min',
    replyMin: 55,
    platform: 'facebook',
    condition: 'Leather is dry at the top of the back, no tears',
    tags: ['Two people to lift', 'Off the Watterson by 8'],
    saves: 27,
    pin: { x: 71, y: 50 },
    story: 'Moved here from Copenhagen with a consulate family in 1971.',
  },
  {
    id: 'rose-2seat',
    img: './img/couch-rose.jpg',
    title: 'Rose two seat sofa, walnut base',
    fabric: 'Wool, rose pink',
    seat: 'Two seat',
    lengthIn: 60,
    price: 310,
    year: 1969,
    neighbour: 'Camp Taylor',
    miles: 14.8,
    posted: 'posted 3d ago',
    reply: 'answers in 1h',
    replyMin: 60,
    platform: 'nextdoor',
    condition: 'One leg has a repair under the walnut cap',
    tags: ['Garage pickup', 'Will not deliver'],
    saves: 12,
    pin: { x: 66, y: 76 },
    story: 'Been in the same family since they bought it new on Bardstown Road.',
  },
  {
    id: 'black-leather-3seat',
    img: './img/couch-black-leather.jpg',
    title: 'Black leather three seat sofa, teak frame',
    fabric: 'Leather, black',
    seat: 'Three seat',
    lengthIn: 84,
    price: 695,
    year: 1964,
    neighbour: 'Anchorage',
    miles: 17.5,
    posted: 'posted 9h ago',
    reply: 'answers in 4h',
    replyMin: 240,
    platform: 'craigslist',
    condition: 'Leather and frame are both clean, cushions still firm',
    tags: ['Bring a truck', 'Gate code at the top of the hill'],
    saves: 18,
    pin: { x: 87, y: 38 },
    story: 'Out of an office on La Grange Road that closed in June.',
  },
  {
    id: 'velvet-rose',
    img: './img/couch-velvet-rose.jpg',
    title: 'Dusty rose velvet sofa, channel back',
    fabric: 'Velvet, dusty rose',
    seat: 'Three seat',
    lengthIn: 79,
    price: 455,
    year: 1963,
    neighbour: 'Fern Creek',
    miles: 19.1,
    posted: 'posted 4d ago',
    reply: 'answers in 2h',
    replyMin: 120,
    platform: 'facebook',
    condition: 'Velvet has a flat spot where the sun hits, no rips',
    tags: ['Cheapest velvet within 20 miles', 'Pickup only'],
    saves: 7,
    pin: { x: 78, y: 82 },
    story: 'They reupholstered the frame in 2011 and are honest about the fading.',
  },
];

const usd = (n) => '$' + Number(n).toLocaleString('en-US');

export const listings = raw.map((l) => {
  const delta = l.price - search.median;
  return {
    ...l,
    priceText: usd(l.price),
    milesText: l.miles.toFixed(1) + ' mi',
    lengthText: l.lengthIn + ' in',
    yearText: String(l.year),
    driveText: Math.max(3, Math.round(l.miles * 2.4)) + ' min drive',
    delta,
    deltaText: delta <= 0 ? usd(-delta) + ' under the local median' : usd(delta) + ' over the local median',
  };
});

/** the nine rows the page and the hub aggregation card both read */
export const items = listings.map((l) => ({
  img: l.img,
  title: l.title,
  price: l.priceText,
  meta: `${l.year} · ${l.lengthText} · ${l.milesText} away`,
  source: l.platform,
}));

export const mapPins = listings.map((l) => ({
  id: l.id,
  x: l.pin.x,
  y: l.pin.y,
  price: l.price,
  priceText: l.priceText,
  neighbour: l.neighbour,
  miles: l.miles,
}));

/** the four numbers the strip above the split view prints */
export const summary = {
  read: search.read,
  kept: search.kept,
  shown: search.shown,
  median: search.median,
  medianText: usd(search.median),
  cheapest: search.cheapest,
  cheapestText: usd(search.cheapest),
  under600: listings.filter((l) => l.price < 600).length,
  within5: listings.filter((l) => l.miles < 5).length,
  leather: listings.filter((l) => /leather/i.test(l.fabric)).length,
  twoSeat: listings.filter((l) => l.seat === 'Two seat').length,
  fastReply: listings.filter((l) => l.replyMin <= 60).length,
  droppedCheap: 145,
  droppedFar: 71,
  droppedLate: 232,
  fastestReply: search.fastestReply,
  refreshed: search.refreshed,
  radius: search.radiusMiles,
  city: search.city,
  homeLabel: search.homeLabel,
};

export const filterNotes = {
  all: `${search.shown} of the ${search.kept} couches kept are inside 20 miles. The other 29 sit outside the ring, 21 to 46 miles out.`,
  under600: `${summary.under600} of the 9 shown are under $600, cheapest ${usd(275)} in Shelby Park.`,
  fiveMiles: `${summary.within5} of the 9 shown are inside 5 miles. Sorting by distance puts those first.`,
  leather: `${summary.leather} of the 9 shown are leather. Both are described as dry, not torn.`,
  twoSeat: `${summary.twoSeat} of the 9 shown are two seat, which is what fits a 60 inch wall.`,
  fastReply: `${summary.fastReply} of the 9 shown answer within the hour, one in ${search.fastestReply}.`,
};

/** what the searcher cut, printed under the list: three reasons, three counts */
export const dropped = [
  { k: 'Over $800', v: summary.droppedCheap, note: 'still mid-century, still nearby, just past the price' },
  { k: 'Past 20 miles', v: summary.droppedFar, note: 'a two hour round trip for a couch is not a good deal' },
  { k: 'Not mid-century', v: summary.droppedLate, note: 'sectionals, sleepers, and anything with a recliner built in' },
];

/** the photo in the "where they come from" band: a 1960s room the same sofas came out of */
export const roomImage = './img/room-1960s.jpg';

export const notes = {
  title: 'How these nine were picked',
  body: 'Five marketplaces were read one page at a time. Anything over $800, past 20 miles, or made after 1974 was dropped before it reached this board.',
  fine: "Photo 6 and photo 9 both list fading honestly. Distances are from your zip to the pickup address, not the seller's neighbourhood centre.",
  replyNote: "Reply times are the median of the seller's answers on that platform over the last 90 days.",
};