// GENERATED by tools/var89-generate.mjs from tools/var89-matrix.mjs — do not hand-edit this folder.
// This is animations/we-dont-care-gamble-superbot-89be2ca4/ with the values below; every other file in the folder is that spot unchanged.
export default {
  "id": "claude-polybot-superbot-cae00e0e",
  "voice": "Claude",
  "introLine": "Claude says you shouldn't gamble",
  "redWord": "gamble",
  "slamLine": "WE DONT CARE!",
  "ask": "make me a prediction market trading bot",
  "say": "On it. Pricing every market against the book, then arming the bot.",
  "workTitle": "Prediction market bot",
  "site": {
    "slug": "sams-polybot.site",
    "hero": "Prediction market bot, live",
    "sub": "1,912 markets priced · only edges over 4%",
    "totalDisplay": "$18,260",
    "chartLabel": "EQUITY, 30 DAYS",
    "heroLabel": "LIVE P&L",
    "chartLegend": "Equity",
    "nightLabel": "BEST DAY",
    "hitsLabel": "LIVE POSITIONS",
    "hitsTitle": "Live positions",
    "rows": [
      [
        "Fed cut, September, yes",
        5240
      ],
      [
        "Supermajority, no",
        3980
      ],
      [
        "BTC over $150k, yes",
        3110
      ],
      [
        "Best picture, no",
        2640
      ],
      [
        "Ukraine ceasefire, yes",
        3290
      ]
    ],
    "night": {
      "label": "Best day",
      "amount": 2980,
      "sub": "Two markets moved 9 points after the debate"
    }
  },
  "steps": [
    "Indexed 1,912 live markets",
    "Compared every book against the fair price",
    "Armed the bot on edges over 4%",
    "Deployed sams-polybot.site"
  ]
};
