// The files DeepSeek "scraped" for the Japanese biking demo: real, license-clean images (thumbnails in this folder)
// and audio (originals kept outside the ad; only their facts and ffmpeg-computed waveform peaks are baked here).
// Generated by /tmp/first-model-ad-7d540b7f/scraped-src/build-manifest.cjs. Credits: CREDITS.txt.
// bytes = the original file's size; lic = short license name shown on screen.
export const IMAGES = [
  {"file":"rice-paddies.jpg","domain":"flickr.com","bytes":911842,"w":1868,"h":2500,"lic":"CC BY 2.0"},
  {"file":"minka-house.jpg","domain":"flickr.com","bytes":18805869,"w":5616,"h":3744,"lic":"CC BY 2.0"},
  {"file":"bike-basket.jpg","domain":"wordpress.org","bytes":8711718,"w":5532,"h":3688,"lic":"CC0"},
  {"file":"country-road.jpg","domain":"flickr.com","bytes":1402138,"w":3840,"h":2160,"lic":"CC0"},
  {"file":"utility-poles.jpg","domain":"flickr.com","bytes":5798526,"w":3968,"h":2976,"lic":"PD"},
  {"file":"sunset-sky.jpg","domain":"polyhaven.com","bytes":345976514,"w":16384,"h":8192,"lic":"CC0"},
  {"file":"dirt-road.jpg","domain":"ambientcg.com","bytes":434264050,"w":8192,"h":8192,"lic":"CC0"},
  {"file":"wood-planks.jpg","domain":"polyhaven.com","bytes":42779848,"w":16384,"h":16384,"lic":"CC0"},
];
export const AUDIO = [
  {"file":"cicadas.mp3","domain":"freesound.org","bytes":313289,"dur":13.9,"lic":"CC0","peaks":[0.63,0.72,0.6,0.67,0.52,0.7,0.58,0.55,0.56,0.57,0.62,0.73,0.57,0.55,0.76,0.97,1,0.6,0.58,0.55,0.59,0.77,1,0.58,0.48,0.45,0.5,0.54,0.43,0.5,0.49,0.5,0.59,0.61,0.47,0.45,0.56,0.46,0.6,0.49,0.59,0.45,0.48,0.41,0.48,0.49,0.48,0.46,0.42,0.53,0.45,0.47,0.57,0.5,0.44,0.54]},
  {"file":"bicycle-bell.mp3","domain":"freesound.org","bytes":677136,"dur":29.1,"lic":"CC0","peaks":[0.52,0.56,0.88,0.1,0.08,0.06,0.06,0.06,0.06,0.07,0.06,0.06,0.06,0.06,0.76,0.7,0.23,0.09,0.06,0.06,0.06,0.06,0.06,0.55,0.68,0.57,0.1,0.06,0.06,0.06,0.06,0.06,0.06,0.57,0.67,0.47,0.14,0.06,0.06,0.06,0.06,0.06,0.78,1,0.45,0.16,0.07,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.06,0.07]},
  {"file":"furin-chime.mp3","domain":"freesound.org","bytes":102215,"dur":4.3,"lic":"CC0","peaks":[0.06,0.48,0.47,0.58,0.36,0.58,0.6,0.55,0.46,0.47,0.43,0.48,0.5,0.47,0.43,0.57,0.57,0.42,0.45,0.4,0.37,0.5,0.42,0.54,0.45,0.59,0.46,0.42,0.58,0.4,0.5,0.54,0.39,0.47,0.44,0.48,1,0.52,0.47,0.45,0.39,0.38,0.33,0.26,0.27,0.19,0.18,0.15,0.1,0.11,0.1,0.1,0.08,0.08,0.07,0.33]},
  {"file":"koto-phrase.mp3","domain":"freesound.org","bytes":470431,"dur":17.5,"lic":"CC0","peaks":[0.51,0.93,0.61,1,0.71,0.82,0.8,0.63,0.82,0.51,0.78,0.78,0.93,0.81,0.6,0.9,0.67,0.85,0.88,0.79,0.83,0.68,0.79,0.58,0.85,0.91,0.85,0.79,0.6,0.87,0.73,0.83,0.85,0.78,0.84,0.55,0.77,0.61,0.79,0.96,0.82,0.76,0.55,0.86,0.76,0.83,0.85,0.74,0.81,0.59,0.81,0.56,0.86,0.92,0.88,0.77]},
];
