// Generated by research/build.c54c5ecd.mjs on 2026-09-29. Every verbatim string is sourced in research/research.json.
export const PLACEHOLDER = false;
export const DOC = {
  "file": "Proof queue 2026-09-29",
  "words": 494,
  "date": "Tue, Sep 29, 2026"
};
export const QUEUE = [
  {
    "id": "maine-overtime-serial-comma",
    "heading": "Maine overtime law, §664(3)(F)",
    "pub": "Maine Legislature",
    "published": "May 21, 2012",
    "where": "26 M.R.S. §664(3)(F); PL 2011, c. 681, §1",
    "kind": "Serial comma",
    "before": "F. The canning, processing, preserving, freezing, drying, marketing, storing, packing for shipment or distribution of: (1) Agricultural produce; (2) Meat and fish products; and (3) Perishable foods.",
    "wrong": "",
    "at": 98,
    "right": ",",
    "after": "F. The canning, processing, preserving, freezing, drying, marketing, storing, packing for shipment, or distribution of: (1) Agricultural produce; (2) Meat and fish products; and (3) Perishable foods.",
    "comment": "Add a serial comma so “or distribution” stands alone (GPO 8.46).",
    "rule": 0,
    "fact": null,
    "fix": {
      "by": "Maine Legislature, PL 2017, c. 219, §15",
      "date": "Jun 16, 2017",
      "text": "F. The canning; processing; preserving; freezing; drying; marketing; storing; packing for shipment; or distributing of:",
      "url": "https://legislature.maine.gov/statutes/26/title26sec664.html"
    },
    "cost": {
      "text": "A $5 million settlement has been reached.",
      "src": "NPR, Feb 8, 2018",
      "url": "https://www.npr.org/sections/thetwo-way/2018/02/08/584391391/maine-dairy-drivers-settle-overtime-case-that-hinged-on-an-absent-comma"
    },
    "srcs": {
      "before": "https://legislature.maine.gov/legis/bills/bills_125th/chapters/PUBLIC681.asp",
      "fix": "https://legislature.maine.gov/legis/bills/bills_128th/chapters/PUBLIC219.asp"
    }
  },
  {
    "id": "rba-50-note-responsibilty",
    "heading": "RBA $50 banknote, Cowan microprint",
    "pub": "Reserve Bank of Australia",
    "published": "Oct 18, 2018",
    "where": "$50 banknote, microprint above Edith Cowan’s shoulder",
    "kind": "Misspelling",
    "before": "It is a great responsibilty to be the only woman here, and I want to emphasise the necessity which exists for other women being here…",
    "wrong": "",
    "at": 25,
    "right": "i",
    "after": "It is a great responsibility to be the only woman here, and I want to emphasise the necessity which exists for other women being here…",
    "comment": "Cowan said “responsibility”; a quotation must be exact (Guardian style guide).",
    "rule": 1,
    "fact": {
      "text": "The word \"responsibility\" is misspelled as \"responsibilty\", missing the third \"i\"",
      "src": "ABC News, May 9, 2019",
      "url": "https://www.abc.net.au/news/2019-05-09/new-$50-note-contains-typo-in-word-responsibility-rba-confirms/11096528"
    },
    "fix": {
      "by": "Reserve Bank of Australia",
      "date": "2019",
      "text": "The spelling error has been corrected. New $50 banknotes printed since 2019 have the correct spelling.",
      "url": "https://banknotes.rba.gov.au/questions-and-answers/new-banknote-series/"
    },
    "cost": {
      "text": "around 400 million $50 banknotes with this error on it",
      "src": "SBS News, May 9, 2019 (RBA spokeswoman)",
      "url": "https://www.sbs.com.au/news/article/millions-of-50-notes-carry-typo/qniy6okwv"
    },
    "srcs": {
      "before": "https://www.theguardian.com/australia-news/2019/may/09/australian-50-note-typo-spelling-mistake-printed-46-million-times",
      "fix": "https://banknotes.rba.gov.au/questions-and-answers/new-banknote-series/"
    }
  },
  {
    "id": "fed-rules-of-procedure-or-of",
    "heading": "Fed Rules of Procedure, 12 CFR 262.3",
    "pub": "Board of Governors of the Federal Reserve System",
    "published": "Dec 11, 1980",
    "where": "12 CFR 262.3(b)(1)(ii)(E); 45 FR 81543, 81544",
    "kind": "Wrong word",
    "before": "(E) The community or communities in which the head offices of the largest subsidiary bank, if any, or an applicant and of each bank, shares of which are to be directly or indirectly acquired, are located…",
    "wrong": "or",
    "at": 99,
    "right": "of",
    "after": "(E) The community or communities in which the head offices of the largest subsidiary bank, if any, of an applicant and of each bank, shares of which are to be directly or indirectly acquired, are located…",
    "comment": "Spellcheck passes “or”; the rule meant “of an applicant” (Guardian style guide).",
    "rule": 2,
    "fact": {
      "text": "the community or communities in which the head offices of the largest subsidiary bank, if any, of an applicant and of each bank, shares of which are to be directly or indirectly acquired, are located.",
      "src": "43 FR 47157 (Oct 12, 1978), quoted at 91 FR 13491",
      "url": "https://www.federalregister.gov/documents/2026/03/20/2026-05544/rules-of-procedure-correction"
    },
    "fix": {
      "by": "Board of Governors of the Federal Reserve System, 91 FR 13491",
      "date": "Mar 20, 2026",
      "text": "(E) The community or communities in which the head offices of the largest subsidiary bank, if any, of an applicant and of each bank, shares of which are to be directly or indirectly acquired, are located…",
      "url": "https://www.federalregister.gov/documents/2026/03/20/2026-05544/rules-of-procedure-correction"
    },
    "cost": {
      "text": "which has resulted in confusion among some applicants",
      "src": "Federal Reserve Board, 91 FR 13491 (Mar 20, 2026)",
      "url": "https://www.federalregister.gov/documents/2026/03/20/2026-05544/rules-of-procedure-correction"
    },
    "srcs": {
      "before": "https://www.govinfo.gov/link/cfr/12/262?link-type=pdf&year=2025&sectionnum=3",
      "fix": "https://www.federalregister.gov/documents/2026/03/20/2026-05544/rules-of-procedure-correction"
    }
  },
  {
    "id": "epa-title-v-bought-my",
    "heading": "EPA Title V rule, 40 CFR 70.6(g)(2)",
    "pub": "Environmental Protection Agency",
    "published": "Jun 1, 2026",
    "where": "91 FR 32360; 40 CFR 70.6(g)(2) and 71.6(g)(2)",
    "kind": "Wrong word",
    "before": "An emergency constitutes an affirmative defense to an action bought my noncompliance with such technology-based emission limitations…",
    "wrong": "bought my",
    "at": 61,
    "right": "brought for",
    "after": "An emergency constitutes an affirmative defense to an action brought for noncompliance with such technology-based emission limitations…",
    "comment": "Read “an action brought for”; proof the printed copy (OFR Drafting Handbook).",
    "rule": 3,
    "fact": null,
    "fix": {
      "by": "EPA, 91 FR 61323",
      "date": "Sep 29, 2026",
      "text": "The EPA now amends the regulatory text to replace the phrase “bought my” to “brought for”…",
      "url": "https://www.federalregister.gov/documents/2026/09/29/2026-19889/rescission-of-title-v-emergency-affirmative-defense-rule-corrections"
    },
    "cost": null,
    "srcs": {
      "before": "https://www.federalregister.gov/documents/2026/06/01/2026-10875/rescission-of-title-v-emergency-affirmative-defense-rule",
      "fix": "https://www.federalregister.gov/documents/2026/09/29/2026-19889/rescission-of-title-v-emergency-affirmative-defense-rule-corrections"
    }
  },
  {
    "id": "faa-ad-2026-17-03-blade",
    "heading": "FAA AD 2026-17-03, IAE AG engines",
    "pub": "Federal Aviation Administration",
    "published": "Aug 20, 2026",
    "where": "AD 2026-17-03, paragraph (g); 91 FR 53717",
    "kind": "Missing word",
    "before": "At the next engine shop visit after the effective date of this AD where the 3rd stage HPC rotor is exposed, replace the full set of 3rd stage HPC rotor blades…",
    "wrong": "",
    "at": 95,
    "right": " blade",
    "after": "At the next engine shop visit after the effective date of this AD where the 3rd stage HPC rotor blade is exposed, replace the full set of 3rd stage HPC rotor blades…",
    "comment": "Insert “blade”: the rotor blade is exposed. Edit before it prints (GPO 1.1).",
    "rule": 4,
    "fact": null,
    "fix": {
      "by": "FAA, 91 FR 57491",
      "date": "Sep 10, 2026",
      "text": "Paragraph (g) of AD 2026-17-03 should read, “. . . where the 3rd stage HPC rotor blade is exposed . . .,”",
      "url": "https://www.federalregister.gov/documents/2026/09/10/2026-18423/airworthiness-directives-international-aero-engines-ag-engines-correction"
    },
    "cost": {
      "text": "the FAA is publishing the entire rule",
      "src": "FAA correction, 91 FR 57491 (Sep 10, 2026)",
      "url": "https://www.federalregister.gov/documents/2026/09/10/2026-18423/airworthiness-directives-international-aero-engines-ag-engines-correction"
    },
    "srcs": {
      "before": "https://www.federalregister.gov/documents/2026/08/20/2026-16954/airworthiness-directives-international-aero-engines-ag-engines",
      "fix": "https://www.federalregister.gov/documents/2026/09/10/2026-18423/airworthiness-directives-international-aero-engines-ag-engines-correction"
    }
  },
  {
    "id": "cms-ipps-fy2027-comment-date",
    "heading": "CMS FY 2027 IPPS proposed rule",
    "pub": "Centers for Medicare & Medicaid Services",
    "published": "Apr 14, 2026",
    "where": "91 FR 19312, first column, DATES caption",
    "kind": "Wrong date",
    "before": "…comments must be received at one of the addresses provided in the ADDRESSES section, no later than 5 p.m. EDT on April 10, 2026.",
    "wrong": "April 10",
    "at": 114,
    "right": "June 9",
    "after": "…comments must be received at one of the addresses provided in the ADDRESSES section, no later than 5 p.m. EDT on June 9, 2026.",
    "comment": "The deadline predates the April 14 issue; count from it (OFR Drafting Handbook).",
    "rule": 5,
    "fact": {
      "text": "Tuesday, April 14, 2026",
      "src": "Federal Register masthead, Vol. 91, No. 71",
      "url": "https://www.federalregister.gov/documents/2026/04/14/2026-07203/medicare-program-hospital-inpatient-prospective-payment-systems-for-acute-care-hospitals-ipps-and"
    },
    "fix": {
      "by": "CMS, 91 FR 20397",
      "date": "Apr 16, 2026",
      "text": "On page 19312, first column, 10th full paragraph (DATES section) last line the date “April 10, 2026” is corrected to read “June 9, 2026”.",
      "url": "https://www.federalregister.gov/documents/2026/04/16/2026-07470/medicare-program-hospital-inpatient-prospective-payment-systems-for-acute-care-hospitals-ipps-and"
    },
    "cost": null,
    "srcs": {
      "before": "https://www.federalregister.gov/documents/2026/04/14/2026-07203/medicare-program-hospital-inpatient-prospective-payment-systems-for-acute-care-hospitals-ipps-and",
      "fix": "https://www.federalregister.gov/documents/2026/04/16/2026-07470/medicare-program-hospital-inpatient-prospective-payment-systems-for-acute-care-hospitals-ipps-and"
    }
  },
  {
    "id": "sec-fy2026-fee-rate-minus",
    "heading": "SEC FY 2026 fee rate order",
    "pub": "Securities and Exchange Commission",
    "published": "Mar 4, 2026",
    "where": "91 FR 10645, third column, 20th line; App. A, B, item 5",
    "kind": "Stray minus sign",
    "before": "5. Round the result to the seventh decimal point, yielding a rate of 0.0000206 (or -$20.60 per million).",
    "wrong": "-",
    "at": 83,
    "right": "",
    "after": "5. Round the result to the seventh decimal point, yielding a rate of 0.0000206 (or $20.60 per million).",
    "comment": "A rate of 0.0000206 is positive; the minus is a typo (OFR Drafting Handbook).",
    "rule": 6,
    "fact": {
      "text": "This rate is $2,149,000,000 divided by $104,121,391,900,000 or 0.00002063937.",
      "src": "SEC order, 91 FR 10645, App. A, B, item 4",
      "url": "https://www.federalregister.gov/documents/2026/03/04/2026-04233/order-making-fiscal-year-2026-annual-adjustments-to-transaction-fee-rates"
    },
    "fix": {
      "by": "SEC, 91 FR 24948",
      "date": "May 7, 2026",
      "text": "…“-$20.60 per million” to read “$20.60 per million.",
      "url": "https://www.federalregister.gov/documents/2026/05/07/2026-09078/order-making-fiscal-year-2026-annual-adjustments-to-transaction-fee-rates-correction"
    },
    "cost": null,
    "srcs": {
      "before": "https://www.federalregister.gov/documents/2026/03/04/2026-04233/order-making-fiscal-year-2026-annual-adjustments-to-transaction-fee-rates",
      "fix": "https://www.federalregister.gov/documents/2026/05/07/2026-09078/order-making-fiscal-year-2026-annual-adjustments-to-transaction-fee-rates-correction"
    }
  },
  {
    "id": "commerce-ptmeg-htsus-number",
    "heading": "Commerce PTMEG investigations, scope",
    "pub": "International Trade Administration",
    "published": "May 5, 2026",
    "where": "91 FR 24168, second column; Appendix, scope, 4th para.",
    "kind": "Wrong number",
    "before": "Subject merchandise may also be imported under HTSUS subheadings 2932.11.0000 and 3404.91.5150.",
    "wrong": "3404.91.5150",
    "at": 82,
    "right": "3404.90.5150",
    "after": "Subject merchandise may also be imported under HTSUS subheadings 2932.11.0000 and 3404.90.5150.",
    "comment": "No HTSUS 3404.91 exists; the tariff lists 3404.90.51.50 (GPO 1.5).",
    "rule": 7,
    "fact": {
      "text": "3404.90.51.50",
      "src": "USITC Harmonized Tariff Schedule, search 3404.90.51",
      "url": "https://hts.usitc.gov/reststop/search?keyword=3404.90.51"
    },
    "fix": {
      "by": "Commerce (ITA), 91 FR 27266",
      "date": "May 14, 2026",
      "text": "Subject merchandise may also be imported under HTSUS subheadings 2932.11.0000 and 3404.90.5150.",
      "url": "https://www.federalregister.gov/documents/2026/05/14/2026-09711/polytetramethylene-ether-glycol-from-the-peoples-republic-of-china-the-republic-of-korea-taiwan-and"
    },
    "cost": null,
    "srcs": {
      "before": "https://www.federalregister.gov/documents/2026/05/05/2026-08727/polytetramethylene-ether-glycol-from-the-peoples-republic-of-china-the-republic-of-korea-taiwan-and",
      "fix": "https://www.federalregister.gov/documents/2026/05/14/2026-09711/polytetramethylene-ether-glycol-from-the-peoples-republic-of-china-the-republic-of-korea-taiwan-and"
    }
  },
  {
    "id": "commerce-sunset-colombia",
    "heading": "Commerce five-year sunset initiations",
    "pub": "International Trade Administration",
    "published": "Jan 2, 2026",
    "where": "91 FR 125, third column of the table",
    "kind": "Name misspelled",
    "before": "A-301-804 731-TA-1503 Columbia Prestressed Concrete Steel Wire Strand (1st Review)",
    "wrong": "Columbia",
    "at": 22,
    "right": "Colombia",
    "after": "A-301-804 731-TA-1503 Colombia Prestressed Concrete Steel Wire Strand (1st Review)",
    "comment": "The country is Colombia; “Columbia” is the usual slip (Guardian style guide).",
    "rule": 8,
    "fact": null,
    "fix": {
      "by": "Commerce (ITA), 91 FR 1133",
      "date": "Jan 12, 2026",
      "text": "In the Federal Register of January 2, 2026, in FR Doc 2025-24163, on page 125, in the third column of the table, correct “Columbia” to “Colombia,”…",
      "url": "https://www.federalregister.gov/documents/2026/01/12/2026-00383/initiation-of-five-year-sunset-reviews-correction"
    },
    "cost": null,
    "srcs": {
      "before": "https://www.federalregister.gov/documents/2026/01/02/2025-24163/initiation-of-five-year-sunset-reviews",
      "fix": "https://www.federalregister.gov/documents/2026/01/12/2026-00383/initiation-of-five-year-sunset-reviews-correction"
    }
  },
  {
    "id": "commerce-emek-boru-makina",
    "heading": "Commerce welded pipe review, Türkiye",
    "pub": "International Trade Administration",
    "published": "Sep 15, 2025",
    "where": "90 FR 44369, first column, non-selected rate, 2nd para.",
    "kind": "Name misspelled",
    "before": "…we assigned a rate of zero percent to Emek Boru Makine Sanayi ve Ticaret A.S. (Emek Boru), the company not selected for individual examination in this review…",
    "wrong": "Makine",
    "at": 49,
    "right": "Makina",
    "after": "…we assigned a rate of zero percent to Emek Boru Makina Sanayi ve Ticaret A.S. (Emek Boru), the company not selected for individual examination in this review…",
    "comment": "The name is “Makina,” as in the 2024 initiation notice (Guardian style guide).",
    "rule": 9,
    "fact": {
      "text": "Emek Boru Makina Sanayi ve Ticaret A.S.",
      "src": "Commerce initiation notice, 89 FR 55573 (Jul 5, 2024)",
      "url": "https://www.federalregister.gov/documents/2024/07/05/2024-14771/initiation-of-antidumping-and-countervailing-duty-administrative-reviews"
    },
    "fix": {
      "by": "Commerce (ITA), 90 FR 52913",
      "date": "Nov 24, 2025",
      "text": "correct the company name in the last sentence from Emek Boru Makine Sanayi ve Ticaret A.S. to Emek Boru Makina Sanayi ve Ticaret A.S.",
      "url": "https://www.federalregister.gov/documents/2025/11/24/2025-20736/large-diameter-welded-pipe-from-the-republic-of-trkiye-final-results-of-antidumping-duty"
    },
    "cost": null,
    "srcs": {
      "before": "https://www.federalregister.gov/documents/2025/09/15/2025-17776/large-diameter-welded-pipe-from-the-republic-of-trkiye-final-results-of-antidumping-duty",
      "fix": "https://www.federalregister.gov/documents/2025/11/24/2025-20736/large-diameter-welded-pipe-from-the-republic-of-trkiye-final-results-of-antidumping-duty"
    }
  },
  {
    "id": "epa-snur-ethanediyl",
    "heading": "EPA SNURs 23-3.5e, 40 CFR 721.11839",
    "pub": "Environmental Protection Agency",
    "published": "Jun 13, 2025",
    "where": "90 FR 24985; 40 CFR 721.11839 section heading",
    "kind": "Misspelling",
    "before": "§ 721.11839 Poly[oxy(methyl-1,2-ethandiyl)], .alpha.-(dithiocarboxy)-.omega.-(1-methylethoxy)-, sodium salt (1:1).",
    "wrong": "",
    "at": 37,
    "right": "e",
    "after": "§ 721.11839 Poly[oxy(methyl-1,2-ethanediyl)], .alpha.-(dithiocarboxy)-.omega.-(1-methylethoxy)-, sodium salt (1:1).",
    "comment": "Keep the “e”: “diyl” starts with a consonant, so “ethanediyl” (IUPAC P-16.7.1).",
    "rule": 10,
    "fact": null,
    "fix": {
      "by": "EPA, 90 FR 34184",
      "date": "Jul 21, 2025",
      "text": "the word “ethandiyl” in the name of the chemical substance was misspelled and is corrected to read “ethanediyl”.",
      "url": "https://www.federalregister.gov/documents/2025/07/21/2025-13677/significant-new-use-rules-on-certain-chemical-substances-23-35e-correction"
    },
    "cost": null,
    "srcs": {
      "before": "https://www.federalregister.gov/documents/2025/06/13/2025-10812/significant-new-use-rules-on-certain-chemical-substances-23-35e",
      "fix": "https://www.federalregister.gov/documents/2025/07/21/2025-13677/significant-new-use-rules-on-certain-chemical-substances-23-35e-correction"
    }
  },
  {
    "id": "dol-qpam-extraneous-or",
    "heading": "DOL QPAM exemption, PTE 84-14",
    "pub": "Employee Benefits Security Administration",
    "published": "Apr 3, 2024",
    "where": "89 FR 23138; PTE 84-14, Section I(g)(1)(B)",
    "kind": "Extra word",
    "before": "…interest in the QPAM Participates In Prohibited Misconduct as defined in Section VI(s) and VI(t); or",
    "wrong": " or",
    "at": 98,
    "right": "",
    "after": "…interest in the QPAM Participates In Prohibited Misconduct as defined in Section VI(s) and VI(t);",
    "comment": "Drop the last “or”; the conjunction follows the penultimate item (GPO 8.28).",
    "rule": 11,
    "fact": null,
    "fix": {
      "by": "EBSA, 89 FR 65779",
      "date": "Aug 13, 2024",
      "text": "The Department is removing the extraneous word “or” that appears at the end of Section I(g)(1)(B) of the Final Amendment due to a scrivener’s error.",
      "url": "https://www.federalregister.gov/documents/2024/08/13/2024-17586/prohibited-transaction-class-exemption-84-14-for-transactions-determined-by-independent-qualified"
    },
    "cost": null,
    "srcs": {
      "before": "https://www.federalregister.gov/documents/2024/04/03/2024-06059/amendment-to-prohibited-transaction-class-exemption-84-14-for-transactions-determined-by-independent",
      "fix": "https://www.federalregister.gov/documents/2024/08/13/2024-17586/prohibited-transaction-class-exemption-84-14-for-transactions-determined-by-independent-qualified"
    }
  }
];
export const LEARN = [
  {
    "text": "After each member within a series of three or more words, phrases, letters, or figures used with and, or, or nor.",
    "head": null,
    "src": "GPO Style Manual (2016), 8.46",
    "label": "Serial comma",
    "url": "https://www.govinfo.gov/content/pkg/GPO-STYLEMANUAL-2016/pdf/GPO-STYLEMANUAL-2016.pdf"
  },
  {
    "text": "If you are quoting, be sure to get it right.",
    "head": null,
    "src": "Guardian and Observer style guide, “headlines”",
    "label": "Quote it exactly",
    "url": "https://www.theguardian.com/guardian-observer-style-guide-h"
  },
  {
    "text": "spellchecker if you use one, read through your work afterwards",
    "head": "spellchecker",
    "src": "Guardian and Observer style guide, “spellchecker”",
    "label": "Read past spellcheck",
    "url": "https://www.theguardian.com/guardian-observer-style-guide-s"
  },
  {
    "text": "As soon as possible after publication, proofread the published document against a copy of the document that was sent.",
    "head": null,
    "src": "OFR Document Drafting Handbook (2018, rev. 2.2), ch. 5",
    "label": "Proof the print",
    "url": "https://www.archives.gov/files/federal-register/write/handbook/ddh.pdf"
  },
  {
    "text": "Making changes after submission of copy delays the production of the publication and adds to the expense of the work…",
    "head": null,
    "src": "GPO Style Manual (2016), 1.1",
    "label": "Edit before print",
    "url": "https://www.govinfo.gov/content/pkg/GPO-STYLEMANUAL-2016/pdf/GPO-STYLEMANUAL-2016.pdf"
  },
  {
    "text": "In calculating the date, we count the day after publication as the first day, and then each succeeding day, including Saturdays, Sundays, and holidays.",
    "head": null,
    "src": "OFR Document Drafting Handbook (2018, rev. 2.2), ch. 2, DATES",
    "label": "Count from publication",
    "url": "https://www.archives.gov/files/federal-register/write/handbook/ddh.pdf"
  },
  {
    "text": "Use Correct to fix a clerical or typographical error in a recently published document.",
    "head": null,
    "src": "OFR Document Drafting Handbook (2018, rev. 2.2), ch. 2, Correct",
    "label": "Publish a correction",
    "url": "https://www.archives.gov/files/federal-register/write/handbook/ddh.pdf"
  },
  {
    "text": "Proper names, signatures, figures, foreign words, and technical terms should be written plainly.",
    "head": null,
    "src": "GPO Style Manual (2016), 1.5",
    "label": "Write figures plainly",
    "url": "https://www.govinfo.gov/content/pkg/GPO-STYLEMANUAL-2016/pdf/GPO-STYLEMANUAL-2016.pdf"
  },
  {
    "text": "Colombia South American country that we frequently misspell as “Columbia”",
    "head": "Colombia",
    "src": "Guardian and Observer style guide, “Colombia”",
    "label": "Colombia, not Columbia",
    "url": "https://www.theguardian.com/guardian-observer-style-guide-c"
  },
  {
    "text": "…we have had complaints from readers that it is disrespectful to foreign readers to, in effect, misspell their names",
    "head": null,
    "src": "Guardian and Observer style guide, “foreign accents”",
    "label": "Respect foreign names",
    "url": "https://www.theguardian.com/guardian-observer-style-guide-f"
  },
  {
    "text": "(a) the terminal letter ‘e’ in names of parent hydrides or endings ‘ene’ and ‘yne’ when followed by a suffix or ending beginning with ‘a’, ‘e’, ‘i’, ‘o’, ‘u’, or ‘y’;",
    "head": null,
    "src": "IUPAC Nomenclature of Organic Chemistry (2013), P-16.7.1(a)",
    "label": "Elide e before vowels",
    "url": "https://iupac.qmul.ac.uk/BlueBook/P1.html"
  },
  {
    "text": "A conjunction (and, or, nor) should follow the penultimate item in a list using commas or semicolons after each list item, but not otherwise.",
    "head": null,
    "src": "GPO Style Manual (2016), 8.28",
    "label": "Conjunction placement",
    "url": "https://www.govinfo.gov/content/pkg/GPO-STYLEMANUAL-2016/pdf/GPO-STYLEMANUAL-2016.pdf"
  }
];
