// outreach-data.js: GENERATED by /tmp/sdr-ad.b5acc09b/tools/gen-data.b5acc09b.mjs from research/facts.json
// (2026-09-29T13:13:18Z) and research/rulings.b5acc09b.txt. Do not hand-edit: change the generator and re-run it.
// EVERYTHING the Outreach desk (outreach.js) and the chat's sign-in card (beats/signin.js) put on screen. outreach.js
// holds no copy of its own: every label, HUD line, email / voicemail / note text and count on screen is read from here
// or counted from the arrays below. Provenance for every record is its `src` url (and ../../img/CREDITS.txt).
//
// ---------------------------------------------------------------------------------------------------------------
// EXPORT SHAPE (the contract outreach.js reads)
//   PLACEHOLDER  false
//   SEAT         { user, initials, role, mailbox, phone, signature }  the seat is the viewer: 'You', no personal name,
//                  no phone digits (bullets), mailbox on example.com (not shown).
//   ACCOUNTS     [{ id, company, domain, industry, hq, buyerTitle, trigger: { kind, date, headline, quote, url,
//                   publisher, amount }, src, titleSrc }]
//                  buyerTitle: the title the account's own release gives (shown title-only). trigger.headline: a plain
//                  fact line composed from the sourced headline (never a release headline that names a person);
//                  trigger.quote: verbatim, or '' when it would need redaction. trigger.date ISO (shown 'Sep 16, 2026').
//   TASKS        [{ account, type, stepType, sequence, step, localTime, due, detail, src }]  12 rows, list order.
//                  type: 'email' | 'call' | 'linkedin' | 'action'; stepType: Outreach's documented step-type name
//                  (flow header); detail: the Details column text after '<type>: '. Rows 0, 1, 2 are the three worked
//                  on screen: an email, a call, a LinkedIn connection request.
//   EMAIL        { subject, body, src }       task row 0; {{variables}} render as chips; '\n' is a line break.
//   CALL         { phone, durationSec, script, notes, disposition, purpose, sequenceAction, src }  task row 1.
//                  notes: the voicemail as left, typed into Call notes; script '' hides the script card; purpose ''
//                  hides the Purpose select.
//   LINKEDIN     { noteLimit, note, src }     task row 2; counter reads '<typed>/<noteLimit>'.
//   FINDINGS     [{ id, stat, text, publisher, date, sample, src }]  LEARN rows; the row shows the year of date and
//                  the dataset size (sample) where the finding has one.
//   RULES        [{ text, finding, src }]     chips extracted on LEARN (finding: a FINDINGS id).
//   OUTREACH     { stepTypes, tileTypes, dispositions, purposes, sequenceActions, taskStates, dialer, variables, ui, src }
//   HUD, SIGNIN  superbot's HUD lines and the chat's sign-in card; '{n}' is replaced by a count computed from the
//                  arrays above, never typed.
// Copy rules for every on-screen string: no em or en dashes; U+00A0 between a number and its unit; actions are
// one-sided (a prospect never replies and no meeting is ever booked); no person named.
// ---------------------------------------------------------------------------------------------------------------

export const PLACEHOLDER = false;

export const SEAT = {
  "user": "You",
  "initials": "SD",
  "role": "Sales Development Rep",
  "mailbox": "you@example.com",
  "phone": "•••\u00a0•••\u00a0••••",
  "signature": "{{sender.first_name}}"
};

export const ACCOUNTS = [
  {
    "id": "hyro",
    "company": "Hyro",
    "domain": "hyro.ai",
    "industry": "Healthcare AI (agentic patient communications)",
    "hq": "",
    "buyerTitle": "Vice President of Sales Development",
    "trigger": {
      "kind": "leader",
      "date": "2026-07-29",
      "headline": "Named a new VP of Sales Development",
      "quote": "",
      "url": "https://www.prnewswire.com/news-releases/hyro-expands-go-to-market-leadership-with-brant-castellow-as-chief-revenue-officer-and-yehuda-berkowitz-as-vp-of-sales-development-302836717.html",
      "publisher": "PR Newswire",
      "amount": ""
    },
    "src": "https://www.prnewswire.com/news-releases/hyro-expands-go-to-market-leadership-with-brant-castellow-as-chief-revenue-officer-and-yehuda-berkowitz-as-vp-of-sales-development-302836717.html",
    "titleSrc": "acct-hyro-cro"
  },
  {
    "id": "abstract-security",
    "company": "Abstract",
    "domain": "abstract.security",
    "industry": "Security operations (cybersecurity)",
    "hq": "",
    "buyerTitle": "Chief Revenue Officer",
    "trigger": {
      "kind": "leader",
      "date": "2026-09-14",
      "headline": "Named its first Chief Revenue Officer",
      "quote": "",
      "url": "https://www.prnewswire.com/news-releases/abstract-names-jonathan-eller-chief-revenue-officer-302877181.html",
      "publisher": "PR Newswire",
      "amount": ""
    },
    "src": "https://www.prnewswire.com/news-releases/abstract-names-jonathan-eller-chief-revenue-officer-302877181.html",
    "titleSrc": "acct-abstract-cro"
  },
  {
    "id": "constructconnect",
    "company": "ConstructConnect",
    "domain": "constructconnect.com",
    "industry": "Construction preconstruction software",
    "hq": "Cincinnati, US",
    "buyerTitle": "EVP, Chief Revenue Officer",
    "trigger": {
      "kind": "leader",
      "date": "2026-09-01",
      "headline": "Named a new EVP, Chief Revenue Officer",
      "quote": "",
      "url": "https://www.prnewswire.com/news-releases/jay-rouse-joins-constructconnect-as-evp-chief-revenue-officer-to-accelerate-next-phase-of-growth-302862894.html",
      "publisher": "PR Newswire",
      "amount": ""
    },
    "src": "https://www.prnewswire.com/news-releases/jay-rouse-joins-constructconnect-as-evp-chief-revenue-officer-to-accelerate-next-phase-of-growth-302862894.html",
    "titleSrc": "acct-constructconnect-cro"
  },
  {
    "id": "alliancehcm",
    "company": "AllianceHCM",
    "domain": "alliancehcm.com",
    "industry": "HCM software (HR & payroll)",
    "hq": "The Woodlands, US",
    "buyerTitle": "Chief Revenue Officer",
    "trigger": {
      "kind": "leader",
      "date": "2026-09-28",
      "headline": "Named a new Chief Revenue Officer",
      "quote": "",
      "url": "https://www.prnewswire.com/news-releases/alliancehcm-accelerates-growth-trajectory-with-executive-leadership-expansion-and-upcoming-product-innovation-302891045.html",
      "publisher": "PR Newswire",
      "amount": ""
    },
    "src": "https://www.prnewswire.com/news-releases/alliancehcm-accelerates-growth-trajectory-with-executive-leadership-expansion-and-upcoming-product-innovation-302891045.html",
    "titleSrc": "acct-alliancehcm-cro"
  },
  {
    "id": "backops",
    "company": "BackOps",
    "domain": "backops.ai",
    "industry": "Supply chain AI software",
    "hq": "San Francisco, United States",
    "buyerTitle": "Co-founder and CEO",
    "trigger": {
      "kind": "funding",
      "date": "2026-09-16",
      "headline": "Raised $42M Series B",
      "quote": "BackOps will use the funding to expand its resolution layer to support additional processes and grow its product, engineering and go-to-market teams to meet growing customer demand.",
      "url": "https://www.prnewswire.com/news-releases/backops-raises-42m-series-b-to-scale-its-ai-resolution-layer-for-supply-chain-operations-302879927.html",
      "publisher": "PR Newswire",
      "amount": ""
    },
    "src": "https://www.prnewswire.com/news-releases/backops-raises-42m-series-b-to-scale-its-ai-resolution-layer-for-supply-chain-operations-302879927.html",
    "titleSrc": "acct-backops-pr"
  },
  {
    "id": "dili",
    "company": "Dili",
    "domain": "dili.com",
    "industry": "Compliance software for energy, infrastructure and construction",
    "hq": "New York, United States",
    "buyerTitle": "Co-founder and CEO",
    "trigger": {
      "kind": "funding",
      "date": "2026-07-30",
      "headline": "Raised $21.7m\u00a0in total funding",
      "quote": "The new funding will go toward hiring across engineering, product, and go-to-market as Dili expands beyond prevailing wage and apprenticeship compliance into broader audit and waste detection",
      "url": "https://www.globenewswire.com/news-release/2026/07/30/3336377/0/en/dili-raises-21-7m-from-khosla-ventures-to-bring-ai-powered-assurance-to-america-s-infrastructure-boom.html",
      "publisher": "GlobeNewswire",
      "amount": ""
    },
    "src": "https://www.globenewswire.com/news-release/2026/07/30/3336377/0/en/dili-raises-21-7m-from-khosla-ventures-to-bring-ai-powered-assurance-to-america-s-infrastructure-boom.html",
    "titleSrc": "acct-dili-gnw"
  },
  {
    "id": "probook",
    "company": "Probook",
    "domain": "probook.ai",
    "industry": "Home services software",
    "hq": "New York, United States",
    "buyerTitle": "CEO and co-founder",
    "trigger": {
      "kind": "funding",
      "date": "2026-06-23",
      "headline": "Raised $40M\u00a0to scale its go-to-market team",
      "quote": "Probook will use the capital to scale its go-to-market team against surging demand, and grow engineering and customer success to deliver on it.",
      "url": "https://www.globenewswire.com/news-release/2026/06/23/3316215/0/en/probook-raises-40m-from-andreessen-horowitz-and-sequoia-to-scale-the-ai-operating-system-for-home-services.html",
      "publisher": "GlobeNewswire",
      "amount": ""
    },
    "src": "https://www.globenewswire.com/news-release/2026/06/23/3316215/0/en/probook-raises-40m-from-andreessen-horowitz-and-sequoia-to-scale-the-ai-operating-system-for-home-services.html",
    "titleSrc": "acct-probook-gnw"
  },
  {
    "id": "passionfroot",
    "company": "Passionfroot",
    "domain": "passionfroot.me",
    "industry": "B2B creator marketing platform",
    "hq": "Berlin, Germany",
    "buyerTitle": "Co-founder and CEO",
    "trigger": {
      "kind": "funding",
      "date": "2026-07-22",
      "headline": "Raised $15M Series A led by Insight Partners",
      "quote": "The funding will go toward making their AI Agent Zest run more of every campaign, deepening the Creator Graph, and scaling GTM in the US.",
      "url": "https://www.prnewswire.com/news-releases/passionfroot-raises-15m-series-a-led-by-insight-partners-to-power-creator-led-growth-in-the-ai-era-302831506.html",
      "publisher": "PR Newswire",
      "amount": ""
    },
    "src": "https://www.prnewswire.com/news-releases/passionfroot-raises-15m-series-a-led-by-insight-partners-to-power-creator-led-growth-in-the-ai-era-302831506.html",
    "titleSrc": "acct-passionfroot-pr"
  },
  {
    "id": "clinch",
    "company": "Clinch",
    "domain": "clinch.co",
    "industry": "Advertising technology (omnichannel campaign orchestration)",
    "hq": "",
    "buyerTitle": "VP of Growth, EMEA",
    "trigger": {
      "kind": "expansion",
      "date": "2026-09-09",
      "headline": "Opened a new central office in London",
      "quote": "The London office will serve as Clinch's base for continued expansion across the UK and continental Europe.",
      "url": "https://www.prnewswire.com/news-releases/clinch-expands-london-presence-with-new-central-office-and-appointment-of-colin-cherry-as-vp-of-growth-emea-302871700.html",
      "publisher": "PR Newswire",
      "amount": ""
    },
    "src": "https://www.prnewswire.com/news-releases/clinch-expands-london-presence-with-new-central-office-and-appointment-of-colin-cherry-as-vp-of-growth-emea-302871700.html",
    "titleSrc": "acct-clinch-london"
  },
  {
    "id": "chargeflow",
    "company": "Chargeflow",
    "domain": "chargeflow.io",
    "industry": "Fintech (automated chargeback management)",
    "hq": "",
    "buyerTitle": "VP of Sales",
    "trigger": {
      "kind": "expansion",
      "date": "2026-04-09",
      "headline": "Opened a new NYC office at Rockefeller Plaza",
      "quote": "today announced the expansion of its North American operations with a new office at 1 Rockefeller Plaza in New York City.",
      "url": "https://www.prnewswire.com/news-releases/chargeflow-expands-north-american-presence-with-new-nyc-office-at-rockefeller-plaza-302737754.html",
      "publisher": "PR Newswire",
      "amount": ""
    },
    "src": "https://www.prnewswire.com/news-releases/chargeflow-expands-north-american-presence-with-new-nyc-office-at-rockefeller-plaza-302737754.html",
    "titleSrc": "acct-chargeflow-nyc"
  },
  {
    "id": "legora",
    "company": "Legora",
    "domain": "legora.com",
    "industry": "Legal tech (agentic AI for legal work)",
    "hq": "",
    "buyerTitle": "CEO and Co-Founder",
    "trigger": {
      "kind": "expansion",
      "date": "2026-06-10",
      "headline": "Opened offices in Madrid, Milan and Paris",
      "quote": "The Madrid, Milan, and Paris offices will serve as regional hubs for customer success, go to market functions, and legal engineering in three of the largest legal markets in Europe.",
      "url": "https://legora.com/newsroom/legora-opens-in-madrid-milan-and-paris-and-establishes-london-engineering-base-as-european-customer-demand-accelerates",
      "publisher": "Legora",
      "amount": ""
    },
    "src": "https://legora.com/newsroom/legora-opens-in-madrid-milan-and-paris-and-establishes-london-engineering-base-as-european-customer-demand-accelerates",
    "titleSrc": "acct-legora-news"
  },
  {
    "id": "assured",
    "company": "Assured",
    "domain": "withassured.com",
    "industry": "Healthcare provider operations software",
    "hq": "New York, United States",
    "buyerTitle": "Co-founder & CEO",
    "trigger": {
      "kind": "funding",
      "date": "2026-07-30",
      "headline": "Raised $19M Series A led by Insight Partners",
      "quote": "The Series A will also support growth across the company's product, engineering, and go-to-market teams.",
      "url": "https://www.globenewswire.com/news-release/2026/07/30/3335854/0/en/assured-raises-19m-series-a-led-by-insight-partners-to-automate-healthcare-provider-operations-with-ai-agents.html",
      "publisher": "GlobeNewswire",
      "amount": ""
    },
    "src": "https://www.globenewswire.com/news-release/2026/07/30/3335854/0/en/assured-raises-19m-series-a-led-by-insight-partners-to-automate-healthcare-provider-operations-with-ai-agents.html",
    "titleSrc": "acct-assured-gnw"
  }
];

export const TASKS = [
  {
    "account": "backops",
    "type": "email",
    "stepType": "Manual Email",
    "sequence": "Funding announced",
    "step": 1,
    "localTime": "7:05\u00a0AM",
    "due": "Today",
    "detail": "Manual Email",
    "src": "https://support.outreach.io/support/solutions/articles/159000425524-outreach-sequence-overview"
  },
  {
    "account": "alliancehcm",
    "type": "call",
    "stepType": "Phone Call",
    "sequence": "New revenue leader",
    "step": 2,
    "localTime": "9:05\u00a0AM",
    "due": "Today",
    "detail": "Phone Call",
    "src": "https://support.outreach.io/support/solutions/articles/159000425524-outreach-sequence-overview"
  },
  {
    "account": "clinch",
    "type": "linkedin",
    "stepType": "LinkedIn: Send Connection Request",
    "sequence": "New office opened",
    "step": 1,
    "localTime": "",
    "due": "Today",
    "detail": "Send Connection Request",
    "src": "https://support.outreach.io/support/solutions/articles/159000425747-how-to-manage-outreach-linkedin-tasks"
  },
  {
    "account": "hyro",
    "type": "linkedin",
    "stepType": "LinkedIn: View a Profile",
    "sequence": "New revenue leader",
    "step": 1,
    "localTime": "",
    "due": "Today",
    "detail": "View a Profile",
    "src": "https://support.outreach.io/support/solutions/articles/159000425747-how-to-manage-outreach-linkedin-tasks"
  },
  {
    "account": "dili",
    "type": "call",
    "stepType": "Phone Call",
    "sequence": "Funding announced",
    "step": 2,
    "localTime": "10:05\u00a0AM",
    "due": "Today",
    "detail": "Phone Call",
    "src": "https://support.outreach.io/support/solutions/articles/159000425524-outreach-sequence-overview"
  },
  {
    "account": "abstract-security",
    "type": "email",
    "stepType": "Manual Email",
    "sequence": "New revenue leader",
    "step": 3,
    "localTime": "",
    "due": "Today",
    "detail": "Manual Email",
    "src": "https://support.outreach.io/support/solutions/articles/159000425524-outreach-sequence-overview"
  },
  {
    "account": "passionfroot",
    "type": "linkedin",
    "stepType": "LinkedIn: Send Connection Request",
    "sequence": "Funding announced",
    "step": 3,
    "localTime": "4:05\u00a0PM",
    "due": "Today",
    "detail": "Send Connection Request",
    "src": "https://support.outreach.io/support/solutions/articles/159000425747-how-to-manage-outreach-linkedin-tasks"
  },
  {
    "account": "chargeflow",
    "type": "email",
    "stepType": "Manual Email",
    "sequence": "New office opened",
    "step": 2,
    "localTime": "",
    "due": "Today",
    "detail": "Manual Email",
    "src": "https://support.outreach.io/support/solutions/articles/159000425524-outreach-sequence-overview"
  },
  {
    "account": "constructconnect",
    "type": "call",
    "stepType": "Phone Call",
    "sequence": "New revenue leader",
    "step": 2,
    "localTime": "10:05\u00a0AM",
    "due": "Today",
    "detail": "Phone Call",
    "src": "https://support.outreach.io/support/solutions/articles/159000425524-outreach-sequence-overview"
  },
  {
    "account": "probook",
    "type": "email",
    "stepType": "Manual Email",
    "sequence": "Funding announced",
    "step": 4,
    "localTime": "10:05\u00a0AM",
    "due": "Today",
    "detail": "Manual Email",
    "src": "https://support.outreach.io/support/solutions/articles/159000425524-outreach-sequence-overview"
  },
  {
    "account": "legora",
    "type": "action",
    "stepType": "Generic Task",
    "sequence": "New office opened",
    "step": 4,
    "localTime": "",
    "due": "Today",
    "detail": "Generic Task",
    "src": "https://support.outreach.io/support/solutions/articles/159000425524-outreach-sequence-overview"
  },
  {
    "account": "assured",
    "type": "email",
    "stepType": "Manual Email",
    "sequence": "Funding announced",
    "step": 1,
    "localTime": "10:05\u00a0AM",
    "due": "Today",
    "detail": "Manual Email",
    "src": "https://support.outreach.io/support/solutions/articles/159000425524-outreach-sequence-overview"
  }
];

export const EMAIL = {
  "subject": "GTM hiring",
  "body": "Hi {{first_name}},\n\nSaw BackOps announced a $42M Series B on Sep\u00a016 to grow its go-to-market team.\n\nHow are you ramping the new hires?\n\nHappy to compare notes on a short call next week.\n\n{{sender.first_name}}",
  "src": "https://www.prnewswire.com/news-releases/backops-raises-42m-series-b-to-scale-its-ai-resolution-layer-for-supply-chain-operations-302879927.html"
};

export const CALL = {
  "phone": "Direct dial •••\u00a0•••\u00a0••••",
  "durationSec": 38,
  "script": "",
  "notes": "Hi {{first_name}}, it's {{sender.first_name}}. Calling about your new CRO role at AllianceHCM, announced Sep\u00a028. Email to follow; call back anytime.",
  "disposition": "Voicemail Left",
  "purpose": "",
  "sequenceAction": "Automatic",
  "src": "https://www.prnewswire.com/news-releases/alliancehcm-accelerates-growth-trajectory-with-executive-leadership-expansion-and-upcoming-product-innovation-302891045.html"
};

export const LINKEDIN = {
  "noteLimit": 200,
  "note": "Saw Clinch's Sep\u00a09 news on its new central London office. Congrats on the EMEA growth role. Glad to connect.",
  "src": "https://www.prnewswire.com/news-releases/clinch-expands-london-presence-with-new-central-office-and-appointment-of-colin-cherry-as-vp-of-growth-emea-302871700.html"
};

export const FINDINGS = [
  {
    "id": "gong-reason-for-call",
    "stat": "2.1X",
    "text": "Opening with the reason for your call lifts success rate 2.1X",
    "publisher": "Gong Labs",
    "date": "2018-04-19",
    "sample": "90,380\u00a0cold calls",
    "src": "https://www.gong.io/blog/cold-call-opening-lines/"
  },
  {
    "id": "gong-how-have-you-been",
    "stat": "6.6X",
    "text": "“How have you been?” opener: 6.6X\u00a0higher success than baseline",
    "publisher": "Gong Labs",
    "date": "2018-04-19",
    "sample": "90,380\u00a0cold calls",
    "src": "https://www.gong.io/blog/cold-call-opening-lines/"
  },
  {
    "id": "gong-heard-the-name-opener",
    "stat": "11.24%",
    "text": "“Heard the name tossed around” opener wins at 11.24%\u00a0success rate",
    "publisher": "Gong × 30 Minutes to President's\u00a0Club",
    "date": "2024-07-24",
    "sample": "300M+ cold calls",
    "src": "https://www.gong.io/blog/the-best-and-worst-cold-call-openers-backed-by-data-from-300m-calls"
  },
  {
    "id": "30mpc-successful-call-length",
    "stat": "4.8\u00a0min",
    "text": "The median successful call is 4.8\u00a0minutes",
    "publisher": "30 Minutes to President's\u00a0Club",
    "date": "2026-04-15",
    "sample": "300M+ cold calls",
    "src": "https://www.30mpc.com/interactive-resources/how-to-master-cold-calls-data-from-300m-calls-30mpc"
  },
  {
    "id": "gong-talk-55-percent",
    "stat": "55%",
    "text": "In successful cold calls, reps talk 55%\u00a0of the time",
    "publisher": "Gong",
    "date": "2021-08-16",
    "sample": "thousands of cold calls",
    "src": "https://www.gong.io/blog/cold-call-stats"
  },
  {
    "id": "lavender-email-25-50-words",
    "stat": "25\u00a0to 50",
    "text": "Optimal cold email length: between 25\u00a0and 50\u00a0words",
    "publisher": "Lavender",
    "date": "2023-01-08",
    "sample": "",
    "src": "https://www.lavender.ai/blog/best-length-cold-email"
  },
  {
    "id": "lavender-subject-two-words",
    "stat": "17.5%",
    "text": "Going from a 2\u00a0word to a 4\u00a0word subject line cuts replies 17.5%",
    "publisher": "Lavender",
    "date": "2023-05-04",
    "sample": "",
    "src": "https://www.lavender.ai/blog/cold-email-subject-line-tips"
  },
  {
    "id": "belkins-personalization-reply-133",
    "stat": "133%",
    "text": "Personalization lifts reply rates from 3%\u00a0to 7%, a 133%\u00a0increase",
    "publisher": "Belkins",
    "date": "2025-08-06",
    "sample": "5.5\u00a0million emails",
    "src": "https://belkins.io/blog/b2b-cold-email-subject-line-statistics"
  },
  {
    "id": "belkins-followups-58-6",
    "stat": "58.6%",
    "text": "Follow up emails collectively account for 58.6%\u00a0of all replies",
    "publisher": "Belkins",
    "date": "2026-06-26",
    "sample": "7,530,489\u00a0sent emails",
    "src": "https://belkins.io/blog/sales-follow-up-statistics"
  },
  {
    "id": "30mpc-best-time-9-11am",
    "stat": "9\u00a0to 11am",
    "text": "Call between 9\u00a0and 11am; rates drop steadily after noon",
    "publisher": "30 Minutes to President's\u00a0Club",
    "date": "2026-04-15",
    "sample": "300M+ cold calls",
    "src": "https://www.30mpc.com/interactive-resources/how-to-master-cold-calls-data-from-300m-calls-30mpc"
  },
  {
    "id": "30mpc-voicemail-email-reply",
    "stat": "+115%",
    "text": "Email reply rate after a voicemail: 5.87%\u00a0vs 2.73%\u00a0without (+115%)",
    "publisher": "30 Minutes to President's\u00a0Club",
    "date": "2026-04-15",
    "sample": "300M+ cold calls",
    "src": "https://www.30mpc.com/interactive-resources/how-to-master-cold-calls-data-from-300m-calls-30mpc"
  },
  {
    "id": "belkins-linkedin-reply-17-6",
    "stat": "17.6%",
    "text": "17.6%\u00a0of connected LinkedIn prospects replied to follow up messaging",
    "publisher": "Belkins",
    "date": "2026-06-29",
    "sample": "14,077\u00a0individual contact records",
    "src": "https://belkins.io/blog/linkedin-outreach-study"
  }
];

export const RULES = [
  {
    "text": "Personalize with a real trigger",
    "finding": "belkins-personalization-reply-133",
    "src": "https://belkins.io/blog/b2b-cold-email-subject-line-statistics"
  },
  {
    "text": "Reason for the call first",
    "finding": "gong-reason-for-call",
    "src": "https://www.gong.io/blog/cold-call-opening-lines/"
  },
  {
    "text": "Call 9 to 11am their time",
    "finding": "30mpc-best-time-9-11am",
    "src": "https://www.30mpc.com/interactive-resources/how-to-master-cold-calls-data-from-300m-calls-30mpc"
  },
  {
    "text": "Voicemail, then email",
    "finding": "30mpc-voicemail-email-reply",
    "src": "https://www.30mpc.com/interactive-resources/how-to-master-cold-calls-data-from-300m-calls-30mpc"
  },
  {
    "text": "Email under 50\u00a0words",
    "finding": "lavender-email-25-50-words",
    "src": "https://www.lavender.ai/blog/best-length-cold-email"
  },
  {
    "text": "Two-word subject line",
    "finding": "lavender-subject-two-words",
    "src": "https://www.lavender.ai/blog/cold-email-subject-line-tips"
  }
];

// ---------- the real Outreach vocabulary and chrome labels ----------
export const OUTREACH = {
  "stepTypes": {
    "email": "Email",
    "call": "Call",
    "linkedin": "LinkedIn",
    "action": "Action item"
  },
  "tileTypes": [
    [
      "total",
      "Total"
    ],
    [
      "action",
      "Action item"
    ],
    [
      "email",
      "Email"
    ],
    [
      "call",
      "Call"
    ],
    [
      "meet",
      "Meet in person"
    ],
    [
      "linkedin",
      "LinkedIn"
    ]
  ],
  "dispositions": [
    "Voicemail Left",
    "No Answer",
    "Busy"
  ],
  "purposes": [],
  "sequenceActions": [
    "Automatic",
    "Advance",
    "Finish"
  ],
  "taskStates": {
    "pending": "Pending",
    "active": "In progress",
    "done": "Completed"
  },
  "dialer": {
    "offline": "Offline",
    "available": "Available",
    "calling": "Calling…",
    "ringing": "Ringing",
    "voicemail": "Voicemail",
    "leaveVm": "Leave Voicemail and Hang Up",
    "ended": "Call ended",
    "personalized": "Voicemail Drop"
  },
  "variables": [
    "{{first_name}}",
    "{{sender.first_name}}"
  ],
  "ui": {
    "page": "Tasks",
    "nav": [
      "Home",
      "Pipeline summary",
      "Prospects",
      "Accounts",
      "Opportunities",
      "Kaia",
      "Revenue agents",
      "Forecasting",
      "More records",
      "Activity"
    ],
    "activity": [
      "Email outbox",
      "Calls",
      "Meetings",
      "Tasks",
      "Sequence states"
    ],
    "navTail": [
      "Content",
      "Reports"
    ],
    "newTask": "Task",
    "view": "My tasks",
    "saveView": "Save view",
    "results": "{n} results",
    "search": "Search",
    "chips": [
      [
        "Owner",
        "is you"
      ],
      [
        "Due",
        "is today"
      ]
    ],
    "addFilter": "Add filter",
    "startTasks": "Start tasks",
    "sort": "Due",
    "cols": [
      "Type",
      "Contact",
      "Local time",
      "Details",
      "Due",
      "State"
    ],
    "stepOf": "Step {n} of",
    "stepHash": "Step #{n} of",
    "allLoaded": "All results loaded",
    "flowOf": "{i} of {n} Tasks",
    "tabs": [
      "Task",
      "Activity",
      "Prospect",
      "Account"
    ],
    "research": "Personalization",
    "researchSub": "Inputs used for personalization:",
    "buyerData": "Buyer data",
    "to": "To",
    "ccbcc": "Cc Bcc",
    "subject": "Subject",
    "send": "Send & Complete",
    "sent": "Sent",
    "schedule": "Schedule",
    "yourPhone": "Your phone number",
    "vmScript": "Voicemail script",
    "callNotes": "Call notes",
    "disposition": "Disposition",
    "purpose": "Purpose",
    "sequenceAction": "Sequence action",
    "logComplete": "Log Call & Complete",
    "logged": "Logged",
    "liTitle": "LinkedIn: Send Connection Request",
    "liHint": "Copy the note, then Connect in LinkedIn and add it to the invite.",
    "liNote": "Personal note",
    "markComplete": "Mark Complete",
    "completed": "Completed",
    "dueToday": "Due today",
    "learnTitle": "Cold outreach research",
    "learnCount": "findings read",
    "learnCols": [
      "Finding",
      "Source"
    ]
  },
  "src": {
    "stepTypes": "https://support.outreach.io/support/solutions/articles/159000425632-how-to-create-an-outreach-sequence",
    "taskTypes": "https://support.outreach.io/support/solutions/articles/159000425783-how-to-manage-outreach-tasks",
    "taskUi": "https://support.outreach.io/support/solutions/articles/159000425783-how-to-manage-outreach-tasks",
    "dispositions": "https://support.outreach.io/support/solutions/articles/159000426249",
    "variables": "https://support.outreach.io/support/solutions/articles/159000425990-outreach-variables-overview",
    "dialer": "https://support.outreach.io/support/solutions/articles/159000426083-outreach-dialer-overview",
    "voicemailDrop": "https://support.outreach.io/support/solutions/articles/159000426362-how-to-leave-a-voicemail-drop-beta-",
    "linkedinTasks": "https://support.outreach.io/support/solutions/articles/159000425747-how-to-manage-outreach-linkedin-tasks"
  }
};

// ---------- superbot's HUD (the desk's overlay). '{n}' is filled from the arrays above ----------
export const HUD = {
  "connect": "Signing in to Outreach",
  "connected": "Dialer on · inbox synced",
  "voice": "Matching your voice",
  "voiced": "Voice matched",
  "learn": "Reading {n} published findings",
  "work": "Working your tasks",
  "land": "Tasks clear · {n} done",
  "steps": [
    "Signed in to Outreach",
    "Voice matched",
    "Learned from {n} findings",
    "Working your tasks"
  ],
  "laneYou": "You",
  "laneSb": "Superbot",
  "match": "Voice match",
  "rules": "What the research says",
  "stats": [
    "done",
    "emails",
    "calls"
  ]
};

// ---------- the chat's sign-in card ----------
export const SIGNIN = {
  "chips": [
    [
      "Signing in to Outreach",
      "Signed in to Outreach"
    ],
    [
      "Opening your tasks",
      "{n} tasks due today"
    ]
  ],
  "product": "Outreach",
  "sub": "Tasks · Outreach Voice",
  "seat": "Signed in as you",
  "seatNote": "working as you",
  "tiles": [
    [
      "{n}",
      "tasks due today"
    ],
    [
      "{n}",
      "sequences"
    ]
  ],
  "pill": [
    "Connecting to Outreach",
    "Connected to Outreach"
  ]
};
