/* data.js - the six desks that pass the filter, plus the numbers the page is built from.
   Every figure here is a lot number in a listing, not decoration: the sheet, the compare panel
   and the hub aggregation card all read the same objects.
   Sellers and models are fictional. Photos are sourced (see CREDITS.txt). */

export const query = {
  ask: 'Find me a standing desk under $400 on Amazon with 4+ stars',
  read: 212,
  cap: 400,
  floor: 4.0,
  reviewsRead: 30680,
  readAt: '09:42 today',
  url: 'amazon.com',
};

export const desks = [
  {
    id: 'halden',
    rank: 1,
    brand: 'Halden',
    model: 'H47 Pro',
    name: 'Halden H47 Pro electric standing desk',
    sub: 'Electric sit to stand, 4 presets, cable tray',
    price: 379,
    saving: 0,
    rating: 4.6,
    reviews: 9412,
    thumb: './img/halden.jpg',
    hero: './img/hero-halden.jpg',
    height: [28.3, 47.6],
    travel: 19.3,
    motors: 'Dual',
    load: 265,
    topWidth: 47.2,
    topDepth: 23.6,
    noise: 41.7,
    presets: 4,
    warranty: 7,
    frame: 'Steel, 3 stage',
    dist: [0.79, 0.15, 0.03, 0.02, 0.01],
    badge: 'Top pick',
    verdict: 'Widest lift range in the pass list, 12 lb more load than the next desk, and the quietest dual motor measured here.',
    passed: ['Dual motor at this price', 'Top reaches 47.6 in', 'Noise under 42 dB', 'Frame rated 7 years'],
    slipped: ['Ships in 3 pieces', 'Controller sits under the right edge'],
  },
  {
    id: 'corva',
    rank: 2,
    brand: 'Corva',
    model: 'L55 Dual',
    name: 'Corva L55 Dual motor standing desk',
    sub: 'Electric sit to stand, 2 presets, memory pad',
    price: 349,
    saving: 30,
    rating: 4.5,
    reviews: 6180,
    thumb: './img/corva.jpg',
    hero: './img/corva.jpg',
    height: [27.5, 46.2],
    travel: 18.7,
    motors: 'Dual',
    load: 253,
    topWidth: 55.1,
    topDepth: 27.6,
    noise: 44.1,
    presets: 2,
    warranty: 5,
    frame: 'Steel, 3 stage',
    dist: [0.74, 0.18, 0.05, 0.02, 0.01],
    badge: 'Widest top',
    verdict: '7.9 in more desk width than the winner and $30 less, if your room has the space for a 55 in top.',
    passed: ['55.1 in top at this price', 'Dual motor', '2 sets of legs ship as one box'],
    slipped: ['44.1 dB, the loudest dual motor here', 'Presets reset after a power cut'],
  },
  {
    id: 'orin',
    rank: 3,
    brand: 'Orin',
    model: '3 Basic',
    name: 'Orin 3 Basic single motor standing desk',
    sub: 'Single motor, 2 presets, no tray',
    price: 229,
    saving: 150,
    rating: 4.4,
    reviews: 5905,
    thumb: './img/orin.jpg',
    hero: './img/orin.jpg',
    height: [27.9, 44.5],
    travel: 16.6,
    motors: 'Single',
    load: 154,
    topWidth: 43.3,
    topDepth: 23.6,
    noise: 47.8,
    presets: 2,
    warranty: 3,
    frame: 'Steel, 2 stage',
    dist: [0.68, 0.2, 0.07, 0.03, 0.02],
    badge: 'Cheapest pass',
    verdict: 'Cheapest desk that still clears 4.0 stars and 154 lb. The single motor is the trade.',
    passed: ['$229 shipped', '44.5 in top height', 'Four legs on every order'],
    slipped: ['47.8 dB under load', '154 lb, so one monitor arm and a laptop'],
  },
  {
    id: 'arbor',
    rank: 4,
    brand: 'Arbor',
    model: '48 E1',
    name: 'Arbor 48 E1 standing desk with drawer',
    sub: 'Dual motor, 1 drawer, 3 presets',
    price: 299,
    saving: 80,
    rating: 4.3,
    reviews: 3762,
    thumb: './img/arbor.jpg',
    hero: './img/arbor.jpg',
    height: [28.0, 45.9],
    travel: 17.9,
    motors: 'Dual',
    load: 176,
    topWidth: 48.0,
    topDepth: 24.0,
    noise: 46.4,
    presets: 3,
    warranty: 5,
    frame: 'Steel, 3 stage',
    dist: [0.63, 0.23, 0.08, 0.04, 0.02],
    badge: 'Only one with a drawer',
    verdict: 'The drawer and 3 presets make it a desk you sit at, not just a top that moves. 176 lb is its limit.',
    passed: ['Drawer in the frame, not bolted on', '3 presets', '$299'],
    slipped: ['176 lb is thin for two monitors', '46.4 dB', 'Wobbles at full height on carpet'],
  },
  {
    id: 'tessel',
    rank: 5,
    brand: 'Tessel',
    model: 'K140',
    name: 'Tessel K140 tall standing desk',
    sub: 'Dual motor, 6 presets, 50.4 in max',
    price: 339,
    saving: 40,
    rating: 4.6,
    reviews: 1980,
    thumb: './img/tessel.jpg',
    hero: './img/tessel.jpg',
    height: [25.6, 50.4],
    travel: 24.8,
    motors: 'Dual',
    load: 220,
    topWidth: 55.1,
    topDepth: 27.6,
    noise: 43.2,
    presets: 6,
    warranty: 6,
    frame: 'Steel, 3 stage',
    dist: [0.81, 0.12, 0.04, 0.02, 0.01],
    badge: 'Highest top',
    verdict: 'Reaches 50.4 in, which is 2.8 in past the winner and enough for anyone over 6 ft 2. Only 1,980 ratings so far.',
    passed: ['50.4 in max height', '24.8 in of travel', '4.6 stars over 1,980 ratings'],
    slipped: ['Lowest review count of the six', '25.6 in minimum is high for a chair'],
  },
  {
    id: 'norel',
    rank: 6,
    brand: 'Norel',
    model: 'S2',
    name: 'Norel S2 standing desk, 40 in top',
    sub: 'Single motor, 2 presets, 40 in top',
    price: 189,
    saving: 190,
    rating: 4.2,
    reviews: 3441,
    thumb: './img/norel.jpg',
    hero: './img/norel.jpg',
    height: [28.7, 44.1],
    travel: 15.4,
    motors: 'Single',
    load: 132,
    topWidth: 39.4,
    topDepth: 19.7,
    noise: 49.6,
    presets: 2,
    warranty: 3,
    frame: 'Steel, 2 stage',
    dist: [0.58, 0.25, 0.09, 0.05, 0.03],
    badge: 'Smallest footprint',
    verdict: '39.4 in by 19.7 in fits a hallway desk. 132 lb and 49.6 dB are the floor of the pass list.',
    passed: ['$189', '39.4 in top fits a small room'],
    slipped: ['132 lb load', '49.6 dB is loud on camera', '4.2 stars is the lowest that passes'],
  },
];

/** the hub aggregation card reads these: first four to six items with a source id */
export const items = desks.map((d) => ({
  img: d.thumb,
  title: d.name,
  price: '$' + d.price,
  meta: d.rating.toFixed(1) + ' stars · ' + d.reviews.toLocaleString('en-US') + ' ratings · ' + d.topWidth + ' in wide',
  source: 'amazon',
}));

/** the six rows of the sheet the compare view puts side by side */
export const compare = {
  left: 'halden',
  right: 'corva',
  rows: [
    { k: 'Price', field: 'price', fmt: 'usd', better: 'right', note: '$30 less' },
    { k: 'Top height', field: 'height', fmt: 'range', better: 'left', note: '1.4 in more headroom' },
    { k: 'Travel', field: 'travel', fmt: 'in', better: 'left', note: '0.6 in more travel' },
    { k: 'Motors', field: 'motors', fmt: 'text', better: null, note: 'Both dual' },
    { k: 'Load', field: 'load', fmt: 'lb', better: 'left', note: '12 lb more' },
    { k: 'Top width', field: 'topWidth', fmt: 'in', better: 'right', note: '7.9 in wider' },
    { k: 'Top depth', field: 'topDepth', fmt: 'in', better: 'right', note: '4.0 in deeper' },
    { k: 'Noise under load', field: 'noise', fmt: 'db', better: 'left', note: '2.4 dB quieter' },
    { k: 'Presets', field: 'presets', fmt: 'n', better: 'left', note: '2 more' },
    { k: 'Frame warranty', field: 'warranty', fmt: 'yr', better: 'left', note: '2 more years' },
  ],
  verdict: 'Halden wins on headroom, load and noise. Corva gives you a 7.9 in wider top for $30 less. If you run two monitors and a 55 in top fits the room, take Corva. If you work standing most of the day and the room is tight, take Halden.',
};

/** what the filter did, stated on the page */
export const criteria = [
  { label: 'Price', value: 'under $400' },
  { label: 'Rating', value: '4.0 stars and up' },
  { label: 'Reviews', value: '500 and up' },
  { label: 'Type', value: 'electric sit to stand' },
  { label: 'Ships', value: 'Prime, in stock' },
];

export const rejects = [
  { why: 'Over $400', n: 138 },
  { why: 'Under 4.0 stars', n: 44 },
  { why: 'Fewer than 500 ratings', n: 19 },
  { why: 'Hand crank, not electric', n: 5 },
];

export const verdict = {
  head: 'Standing desks, compared',
  dek: '212 listings on amazon.com read against the ask, 30,680 reviews read across them. Six desks clear the filter. One wins.',
  footnote: 'Prices and ratings copied from amazon.com listings today at 09:42. Review counts are as listed.',
};

/** the winner's rating column, read out loud */
export const ratingRead = {
  head: 'How the 9,412 ratings land',
  bars: [
    { star: 5, pct: 79 },
    { star: 4, pct: 15 },
    { star: 3, pct: 3 },
    { star: 2, pct: 2 },
    { star: 1, pct: 1 },
  ],
  notes: [
    'Reviews that name the height range: 3,180',
    'Reviews that name wobble at full height: 214',
    'Reviews that name the app pairing giving up: 96',
  ],
};