// Listing data for the "Leather, size M" moodboard.
// Every label, seller and city is invented. Prices, measurements and wear notes are representative
// resale values, not scraped records. Photos are sourced stock, credited in CREDITS.txt.
// aspect is the shape the plate is cut to on the board: seller photos come in every shape, so the
// board keeps them in the shape they were shot in rather than cropping them all to one box.

export const brief = {
  ask: 'Find me a vintage leather jacket in size M on every resale app',
  size: 'M',
  era: 'Pre 2000',
  budget: 'Under $700',
  criteria: [
    'Size M in the flat pit to pit',
    'Made before 2000',
    'No split seams or missing hardware',
    'Photo checked front, back and collar',
  ],
};

export const board = {
  masthead: 'LEATHER',
  mastheadSub: 'SIZE M',
  kicker: 'Six resale apps read',
  head: 'The rack',
  hint: 'Sorted by how close the flat pit to pit sits to 21 inches, which is what size M measures in a leather cut.',
  dek: '318 jackets in size M whose photos show a cut, a collar and hardware that match the decade the seller claims. Photos are seller photos, pinned to the board in the shape they arrived.',
  histHead: 'What each app asks',
  histDek: 'Size M vintage leather, grouped into $100 bands. Counts are listings kept for size M, not raw hits.',
  histFine: 'Grailed sits at the top of the range because two thirds of what it keeps here is 1970s horsehide and small label work. Vinted sits at the bottom because most of its size M is 1990s mall leather with lined sleeves.',
  tray: 'kept on the board',
  footHead: 'What was searched',
  footSum: '3,318 listings read across six apps. 140 were the same jacket posted twice, on a second app, with the same photos. 318 held size M and a label older than 2000.',
  footMethod: 'How a jacket got kept',
  footMethods: [
    'Pit to pit 20.5 to 22 inches flat, which is what size M measures in a leather cut.',
    'Made before 2000: label, zip maker and lining tell the decade better than the seller does.',
    'Seams, zip, collar and lining read in the photos before the listing reached the board.',
    'Asking price compared with the last 90 days of size M asks on the same app.',
  ],
  footSign: 'Assembled by',
};

export const tags = {
  era: [
    { key: '70s', label: '1970s', note: 'Steer or horsehide. Maker letters stamped inside the collar. Brass hardware until the middle of the decade, then nickel.' },
    { key: '80s', label: '1980s', note: 'Cut close at the shoulder. Aniline dye gone patchy in the sun, which is what that finish does.' },
    { key: '90s', label: '1990s', note: 'Heavier cowhide on the small labels. Boxy body, elastic at the waist on the moto cut.' },
  ],
  condition: [
    { key: 'broken', label: 'Broken in', note: 'Creased at the elbows and the front hem. Collar softened, no loss at the cuffs.' },
    { key: 'worn', label: 'Worn well', note: 'Rub at the collar edge, scuffed sleeve ends, lining intact. Reads as a jacket someone lived in.' },
    { key: 'solid', label: 'Solid', note: 'Even surface, no rub through, hardware all present and working.' },
    { key: 'crisp', label: 'Crisp', note: 'Stiff and faintly glossy, barely worn. The leather has not learned a shoulder yet.' },
  ],
};

export const priceBands = ['under $100', '$100 to 200', '$200 to 300', '$300 to 450', '$450 to 700', '$700 and up'];

export const priceBySource = {
  ebay: { counts: [22, 30, 26, 20, 11, 5], median: 185 },
  depop: { counts: [20, 25, 21, 12, 6, 2], median: 168 },
  vinted: { counts: [16, 19, 12, 6, 2, 1], median: 142 },
  poshmark: { counts: [6, 8, 6, 4, 2, 1], median: 225 },
  grailed: { counts: [1, 3, 5, 6, 5, 3], median: 520 },
  mercari: { counts: [2, 4, 3, 2, 1, 0], median: 196 },
};

export const sourceNotes = {
  ebay: 'Single photos and estate lots. Ask prices are all over the place, and the title carries the size, not the label.',
  depop: 'Younger sellers, more shots of the jacket being worn, sizes guessed from a try on. Cropped motos and 1990s workwear.',
  vinted: 'Cheapest asks of the six. Often no measurements at all, so the flat pit to pit had to be asked for.',
  poshmark: 'Fewest in size M. Sellers price high and take offers, so the ask is not the price.',
  grailed: 'Small label and archive work. Correct measurements, collar and zip photos, and the highest asks by far.',
  mercari: 'Thin for leather. A handful in size M, several left up after the jacket sold.',
};

export const trayLine = 'Nineteen of the 318 are pinned here. The spread at the bottom of the page is what each app asks for the same size and decade.';

export const items = [
  {
    img: './img/jk-01.webp',
    title: 'Black double rider, laid flat',
    price: '$430',
    meta: '1970s · Size M · Brass hardware',
    source: 'grailed',
    era: '1970s',
    eraKey: '70s',
    condition: 'Broken in',
    condKey: 'broken',
    seller: 'Rook Vintage',
    city: 'Portland, OR',
    pit: '21 in',
    length: '25 in',
    zip: 'YKK, brass, replaced pull',
    note: 'Steerhide with the belt and buckle still on it. Creasing at both elbows, grain opened up across the back, supple everywhere. Seller shot it on the floor because a hanger will not hold the weight.',
    listed: '4 days',
    terms: 'Ships in 2 days',
    retail: '$1,240',
    aspect: '3 / 2',
  },
  {
    img: './img/jk-02.webp',
    title: 'Black biker, studio shots',
    price: '$295',
    meta: '1980s · Size M · Fitted shoulder',
    source: 'ebay',
    era: '1980s',
    eraKey: '80s',
    condition: 'Solid',
    condKey: 'solid',
    seller: 'second_light',
    city: 'Leeds',
    pit: '21.5 in',
    length: '24 in',
    zip: 'Lightning, serviceable',
    note: 'Photographed on a form with the collar down, which is the only way to read this cut. Shoulders narrow, body short. Lining sound, no rub at the cuffs. Nickelled hardware.',
    listed: '11 days',
    terms: 'Open to offers',
    retail: '$520',
    aspect: '3 / 4',
  },
  {
    img: './img/jk-03.webp',
    title: 'Black rider, soft with age',
    price: '$236',
    meta: '1980s · Size M · Size stamp in collar',
    source: 'depop',
    era: '1980s',
    eraKey: '80s',
    condition: 'Broken in',
    condKey: 'broken',
    seller: 'harlowvintage',
    city: 'Brooklyn, NY',
    pit: '22 in',
    length: '26 in',
    zip: 'YKK, black',
    note: 'Held up for the photo and it hangs like cloth, which is what 30 years of wearing does to steerhide. The lapels fall open on their own. Lining replaced in cotton sheeting at some point.',
    listed: '2 days',
    terms: 'Ships next day',
    retail: '$340',
    aspect: '4 / 5',
  },
  {
    img: './img/jk-04.webp',
    title: 'Black rider with club patches',
    price: '$340',
    meta: '1980s · Size M · Two patches',
    source: 'ebay',
    era: '1980s',
    eraKey: '80s',
    condition: 'Worn well',
    condKey: 'worn',
    seller: 'northshore_pick',
    city: 'Duluth, MN',
    pit: '21 in',
    length: '25 in',
    zip: 'YKK, brass',
    note: 'Two patches sewn on, both of them there for decades: the stitches have rusted into the leather. Stud work across the lapels. Scuff at the right sleeve end, no split in it.',
    listed: '5 days',
    terms: 'Ships in 3 days',
    retail: '$430',
    aspect: '1 / 1',
  },
  {
    img: './img/jk-05.webp',
    title: 'Black blouson, plain front',
    price: '$168',
    meta: '1990s · Size M · Full lining',
    source: 'vinted',
    era: '1990s',
    eraKey: '90s',
    condition: 'Crisp',
    condKey: 'crisp',
    seller: 'Marek Sidlo',
    city: 'Brno',
    pit: '21 in',
    length: '25.5 in',
    zip: 'Talon, smooth',
    note: 'Cowl neck with a two way zip and no belt, no epaulets. Barely worn, still glossy, cuffs square. Priced under the racers because the cut is plain, not because anything is wrong with it.',
    listed: '6 days',
    terms: 'Ships from Brno',
    retail: '$210',
    aspect: '4 / 3',
  },
  {
    img: './img/jk-06.webp',
    title: 'Brown flight jacket, museum label',
    price: '$498',
    meta: '1970s · Size M · Photographed in a case',
    source: 'ebay',
    era: '1970s',
    eraKey: '70s',
    condition: 'Worn well',
    condKey: 'worn',
    seller: 'wren_and_ash',
    city: 'Edinburgh',
    pit: '21 in',
    length: '24.5 in',
    zip: 'Crown, original',
    note: 'A-2 cut in brown steer, knit cuffs and waist both rebuilt in the same shade. The seller photographed it inside a display case, so glare across the left shoulder is the glass, not the leather.',
    listed: '8 days',
    terms: 'No returns',
    retail: '$640',
    aspect: '2 / 3',
  },
  {
    img: './img/jk-07.webp',
    title: 'Brown suede blouson, worn in town',
    price: '$189',
    meta: '1980s · Size M · Suede, unlined',
    source: 'depop',
    era: '1980s',
    eraKey: '80s',
    condition: 'Broken in',
    condKey: 'broken',
    seller: 'mila.rack',
    city: 'Manchester',
    pit: '21 in',
    length: '25 in',
    zip: 'YKK, brass',
    note: 'Shot on a street in the rain, which is where it has lived. Nap rubbed smooth along the sleeve tops and the collar stand. Snap front, all snaps seat. Lining is cotton, no holes.',
    listed: '1 day',
    terms: 'Tracked shipping',
    retail: '$160',
    aspect: '2 / 1',
  },
  {
    img: './img/jk-08.webp',
    title: 'Cognac racer, patched at the collar',
    price: '$368',
    meta: '1970s · Size M · Band collar',
    source: 'mercari',
    era: '1970s',
    eraKey: '70s',
    condition: 'Broken in',
    condKey: 'broken',
    seller: 'Sana Okada',
    city: 'Osaka',
    pit: '21 in',
    length: '25 in',
    zip: 'Unbranded, waxed',
    note: 'Cognac that has gone darker at the collar and the hem, and lighter where the sun reaches the chest. No belt on this cut. One inch of the collar edge has been re stitched by hand, visible up close.',
    listed: '10 days',
    terms: 'Offers welcome',
    retail: '$540',
    aspect: '3 / 4',
  },
  {
    img: './img/jk-09.webp',
    title: 'Mid brown trucker, and its twin',
    price: '$262',
    meta: '1980s · Size M · Two jackets in one listing',
    source: 'ebay',
    era: '1980s',
    eraKey: '80s',
    condition: 'Solid',
    condKey: 'solid',
    seller: 'field_and_foundry',
    city: 'Toronto, ON',
    pit: '22 in',
    length: '27 in',
    zip: 'Two way, works',
    note: 'Four pocket trucker in mid brown, photographed with a black jacket from the same rack. Snaps all seat, storm cuffs inside. The brown one is the listing. Body long enough to wear over knit.',
    listed: '12 days',
    terms: 'Ships boxed, 2 days',
    retail: '$390',
    aspect: '4 / 3',
  },
  {
    img: './img/jk-10.webp',
    title: 'Black cafe racer, plain front',
    price: '$325',
    meta: '1980s · Size M · No belt, no epaulets',
    source: 'grailed',
    era: '1980s',
    eraKey: '80s',
    condition: 'Solid',
    condKey: 'solid',
    seller: 'Cold Storage Vtg',
    city: 'Montreal, QC',
    pit: '21 in',
    length: '25 in',
    zip: 'YKK, black',
    note: 'The plain version: no belt, no epaulets, one chest zip. Aniline finish worn matte across the shoulders. Lining replaced in grey cotton. Photographed on a hanger against denim so the cut reads.',
    listed: '7 days',
    terms: 'Ships from Montreal',
    retail: '$470',
    aspect: '4 / 3',
  },
  {
    img: './img/jk-11.webp',
    title: 'Khaki suede, collar and pocket',
    price: '$142',
    meta: '1990s · Size M · Draped shot',
    source: 'vinted',
    era: '1990s',
    eraKey: '90s',
    condition: 'Worn well',
    condKey: 'worn',
    seller: 'Ines Kalnina',
    city: 'Riga',
    pit: '20.5 in',
    length: '26 in',
    zip: 'Buttons, one resewn',
    note: 'Draped over a rail so the seller could show the shoulder without a model. Thin suede, soft through the body. One button resewn with brown thread on a khaki placket, which shows.',
    listed: '5 days',
    terms: 'Ships in 5 days',
    retail: '$150',
    aspect: '3 / 4',
  },
  {
    img: './img/jk-12.webp',
    title: 'Tan suede, collar up on a chair',
    price: '$452',
    meta: '1970s · Size M · Small label work',
    source: 'grailed',
    era: '1970s',
    eraKey: '70s',
    condition: 'Solid',
    condKey: 'solid',
    seller: 'Burrow Archive',
    city: 'Chicago, IL',
    pit: '20.5 in',
    length: '24.5 in',
    zip: 'Talon, mint',
    note: 'Thick tan suede with the collar stood up, shot on a chair in daylight, which is the only way this colour reads true. Hip pockets without flaps. Barely worn: suede still even across the front.',
    listed: '2 days',
    terms: 'Offers, ships insured',
    retail: '$760',
    aspect: '3 / 4',
  },
  {
    img: './img/jk-13.webp',
    title: 'Zip and seam detail, black cowhide',
    price: '$98',
    meta: '1980s · Size M · Detail shot',
    source: 'mercari',
    era: '1980s',
    eraKey: '80s',
    condition: 'Worn well',
    condKey: 'worn',
    seller: 'Dana Whitlock',
    city: 'Columbus, OH',
    pit: '21 in',
    length: '24 in',
    zip: 'Unbranded, stiff',
    note: 'The listing photo is the seam, because the seam is the story: grain opened along the shoulder line, stitches intact the whole length. Zip needs wax. Cheapest keeper on the board and priced for the zip.',
    listed: '21 days',
    terms: 'No returns, as seen',
    retail: '$180',
    aspect: '3 / 2',
  },
  {
    img: './img/jk-14.webp',
    title: 'Front placket and pockets, close up',
    price: '$118',
    meta: '1990s · Size M · Detail shot',
    source: 'vinted',
    era: '1990s',
    eraKey: '90s',
    condition: 'Solid',
    condKey: 'solid',
    seller: 'Loic Bertin',
    city: 'Nantes',
    pit: '21.5 in',
    length: '26 in',
    zip: 'YKK, brass',
    note: 'Two zipped side pockets and a brass tape photographed at close range. Panels line up across the placket, which is what the seller shot first before anything else. Chest measurement sent on request.',
    listed: '14 days',
    terms: 'Ships from Nantes',
    retail: '$150',
    aspect: '3 / 2',
  },
  {
    img: './img/jk-15.webp',
    title: 'Grain and zip tape, black',
    price: '$205',
    meta: '1990s · Size M · Suede and leather mix',
    source: 'poshmark',
    era: '1990s',
    eraKey: '90s',
    condition: 'Worn well',
    condKey: 'worn',
    seller: 'Juniper Closet',
    city: 'Austin, TX',
    pit: '21.5 in',
    length: '26 in',
    zip: 'YKK, black tape',
    note: 'Black suede front panels to a hairsheep back, which is how this era kept a jacket light. Grain photographed against the zip tape so a buyer can see the nap. Sits at the hip, collar unmarked.',
    listed: '3 days',
    terms: 'Smoke free home',
    retail: '$295',
    aspect: '16 / 9',
  },
  {
    img: './img/jk-16.webp',
    title: 'Suede zip and buckle, tan',
    price: '$285',
    meta: '1970s · Size M · Brass buckle',
    source: 'ebay',
    era: '1970s',
    eraKey: '70s',
    condition: 'Broken in',
    condKey: 'broken',
    seller: 'wren_and_ash',
    city: 'Bath',
    pit: '21 in',
    length: '25 in',
    zip: 'Brass, stiff',
    note: 'Buckle, keeper and zip photographed together because the hardware is original and that is the thing to check on a 1970s suede. Nap worn bare in a ring around the buckle. Cuffs even, no rub through.',
    listed: '9 days',
    terms: 'Ships from Bath',
    retail: '$420',
    aspect: '8 / 5',
  },
  {
    img: './img/jk-18.webp',
    title: 'Black biker, seller photo from 1984',
    price: '$395',
    meta: '1980s · Size M · Period photo included',
    source: 'poshmark',
    era: '1980s',
    eraKey: '80s',
    condition: 'Solid',
    condKey: 'solid',
    seller: 'Hemlock Trading',
    city: 'San Diego, CA',
    pit: '21.5 in',
    length: '25 in',
    zip: 'Talon, original',
    note: 'Third photo in the listing is a print the seller kept from 1984, when the jacket was new. Chrome hardware, studs on the lapel, black over brown dye so the wear goes brown. Wears short, sits at the belt.',
    listed: '4 days',
    terms: 'Ships from San Diego',
    retail: '$480',
    aspect: '3 / 2',
  },
  {
    img: './img/jk-19.webp',
    title: 'Black leather, worn on a bike',
    price: '$226',
    meta: '1990s · Size M · Worn shot',
    source: 'depop',
    era: '1990s',
    eraKey: '90s',
    condition: 'Solid',
    condKey: 'solid',
    seller: 'warden.vtg',
    city: 'Melbourne',
    pit: '21 in',
    length: '24 in',
    zip: 'YKK, black',
    note: 'Worn on the seller with the collar closed so the shoulder line reads. Lamb, so it drapes and creases shallow. Zip clean, cuffs square. Ships folded in a box, not on a hanger.',
    listed: '6 days',
    terms: 'No returns',
    retail: '$310',
    aspect: '3 / 4',
  },
  {
    img: './img/jk-20.webp',
    title: 'Black jacket with big buttons',
    price: '$378',
    meta: '1990s · Size M · Button front',
    source: 'poshmark',
    era: '1990s',
    eraKey: '90s',
    condition: 'Broken in',
    condKey: 'broken',
    seller: 'Juniper Closet',
    city: 'Austin, TX',
    pit: '21.5 in',
    length: '25 in',
    zip: 'None, button front',
    note: 'Button front with four large buttons, so the placket is the whole design. Leather gone dull at the hips where a bag sits. Lining sound, one button re stitched. Worn open in the photo by choice.',
    listed: '3 days',
    terms: 'Tracked, ships 2 days',
    retail: '$450',
    aspect: '3 / 2',
  },
];
