// GENERATED by tools/var89-generate.mjs from tools/var89-matrix.mjs — do not hand-edit this folder.
// This is animations/we-dont-care-gamble-superbot-89be2ca4/ with the values below; every other file in the folder is that spot unchanged.
export default {
  "id": "claude-memecoins-superbot-cae00e04",
  "voice": "Claude",
  "introLine": "Claude says you shouldn't gamble",
  "redWord": "gamble",
  "slamLine": "WE DONT CARE!",
  "ask": "Make a website of all my memecoin wins",
  "say": "On it. Pulling every memecoin you ever exited green.",
  "workTitle": "Memecoin wins site",
  "site": {
    "slug": "sams-memecoins.site",
    "hero": "All my memecoin wins",
    "sub": "1,940 trades · three wallets · every memecoin you held",
    "totalDisplay": "$186,400",
    "chartLabel": "REALIZED P&L",
    "hitsLabel": "TOP TRADES",
    "hitsTitle": "Best exits",
    "rows": [
      [
        "DOGE - 2021 run",
        61200
      ],
      [
        "WIF - month one",
        34800
      ],
      [
        "PEPE - the bag you forgot",
        28900
      ],
      [
        "BONK - round trip",
        17400
      ],
      [
        "POPCAT - wave three",
        9300
      ]
    ],
    "night": {
      "label": "The PEPE week",
      "amount": 19800,
      "sub": "Four days, one green candle after another"
    }
  },
  "steps": [
    "Pulled 1,940 trades from your three wallets",
    "Priced every exit against live quotes",
    "Ranked the wins above the paper hands",
    "Built and deployed sams-memecoins.site"
  ]
};
