/* data.js - the mailbox superbot sorted, reduced to the 12 threads that need a person.
   items[]: the 6+ emails that need you (9 need a reply, 3 need a payment).
   The hub card reads img / title / price / meta / source; the rest is for site.js. */

export const items = [
  {
    img: './brand/av-maya.svg',
    title: 'Lease signed, keys Friday?',
    price: 'Reply drafted',
    meta: 'Maya Okafor · 8:12 AM',
    source: 'gmail',
    from: 'Maya Okafor',
    snippet: 'Countersigned this morning. Can you come by Friday at 9 for the keys?',
    draft: 'Friday at 9 works. I will bring the signed copy and the deposit check to the Lakeview office.',
  },
  {
    img: './brand/av-dana.svg',
    title: 'Hiring loop for the design role',
    price: 'Reply drafted',
    meta: 'Dana Whitfield · 8:26 AM',
    source: 'gmail',
    from: 'Dana Whitfield',
    snippet: 'Two of the three interviewers are free Thursday. Does 2pm work for you?',
    draft: 'Book Thursday at 2. I will send the updated scorecard to the panel tonight.',
  },
  {
    img: './brand/av-ava.svg',
    title: 'Can we move the Northwind kickoff?',
    price: 'Reply drafted',
    meta: 'Ava Lindqvist · 8:34 AM',
    source: 'gmail',
    from: 'Ava Lindqvist',
    snippet: 'Our tech lead is out Monday. Tuesday morning is wide open on our side.',
    draft: 'Tuesday at 10 is good for kickoff. I will share the onboarding checklist and the deck today.',
  },
  {
    img: './brand/notion.svg',
    title: 'Dana shared the Q3 planning doc',
    price: 'Reply drafted',
    meta: 'Notion · 8:47 AM',
    source: 'gmail',
    from: 'Notion',
    snippet: 'Dana mentioned you on the pricing page and left two questions open.',
    draft: 'Read it. I left notes on the pricing section and put owners on the two open hiring lines.',
  },
  {
    img: './brand/av-priya.svg',
    title: 'Invoice 0042 and the September retainer',
    price: 'Reply drafted',
    meta: 'Priya Raman · 9:02 AM',
    source: 'gmail',
    from: 'Priya Raman',
    snippet: 'Invoice 0042 went out Monday. The retainer renews on the 1st.',
    draft: 'Payment goes out Friday. Keep the retainer as is and send the September hours by the 30th.',
  },
  {
    img: './brand/figma.svg',
    title: 'Two comments on Inbox v4',
    price: 'Reply drafted',
    meta: 'Figma · 9:15 AM',
    source: 'gmail',
    from: 'Figma',
    snippet: 'Ana left comments on the lane spacing and the numbers in the KPI row.',
    draft: 'Both threads are answered. Lane spacing is 16px now and the KPI row uses tabular numbers.',
  },
  {
    img: './brand/av-harbor.svg',
    title: 'Claim form needs your signature',
    price: 'Reply drafted',
    meta: 'Harbor Health · 9:22 AM',
    source: 'gmail',
    from: 'Harbor Health',
    snippet: 'The visit on Aug 14 still needs a signed claim form, due within 7 days.',
    draft: 'Signed and uploaded the form this morning. Aug 14 is the only visit still missing one.',
  },
  {
    img: './brand/av-lincoln.svg',
    title: 'Field trip form due Friday',
    price: 'Reply drafted',
    meta: 'Lincoln School · 9:31 AM',
    source: 'gmail',
    from: 'Lincoln School',
    snippet: 'One form per child. The bus leaves at 7:40am on the 12th.',
    draft: 'Signed and sent both forms. Bus both ways is fine, pickup stays at the usual door.',
  },
  {
    img: './brand/av-tom.svg',
    title: 'Guitar is ready, pickup any time',
    price: 'Reply drafted',
    meta: 'Tom Aldridge · 9:40 AM',
    source: 'gmail',
    from: 'Tom Aldridge',
    snippet: 'The neck is set and the electronics are quiet now. Saturday is best for me.',
    draft: 'Saturday morning works. I will come by around 10 with the case.',
  },
  {
    img: './brand/av-lakeview.svg',
    title: 'October rent, due Oct 1',
    price: '$1,850.00',
    meta: 'Lakeview Property · 7:05 AM',
    source: 'gmail',
    from: 'Lakeview Property',
    due: 'Oct 1',
    snippet: 'Same amount as September. Autopay is still off for this unit.',
  },
  {
    img: './brand/av-baypower.svg',
    title: 'September power bill, due Sep 29',
    price: '$146.20',
    meta: 'Bay Power · Sep 22',
    source: 'gmail',
    from: 'Bay Power',
    due: 'Sep 29',
    snippet: 'Usage was up 4 percent. Budget billing stays at $152.',
  },
  {
    img: './brand/av-northline.svg',
    title: 'Card statement, due Oct 2',
    price: '$412.66',
    meta: 'Northline Bank · Sep 21',
    source: 'gmail',
    from: 'Northline Bank',
    due: 'Oct 2',
    snippet: 'Nothing carried over from August. Minimum due is $35.',
  },
];

/* what superbot did with the rest of the 2,431 unread */
export const handled = [
  { label: 'Archived', count: 1688, note: 'Shipping alerts and read threads, no reply needed' },
  { label: 'Labeled', count: 476, note: 'Deals, Travel and Hiring, with rules you can edit' },
  { label: 'Filed to Receipts', count: 214, note: 'Invoices and PDFs, folder 2026 / Receipts' },
];

/* the senders superbot cut (41) */
export const unsubscribed = {
  count: 41,
  senders: [
    'Design Weekly',
    'Backend Notes',
    'The Daily Standup',
    'Pixel Picks',
    'Indie Hustle',
    'SaaS Benchmarks',
    'Cooking Fast',
    'Trail Routes',
    'Weekend Reads',
    'Kitchen Deals',
    'Stock Snapshot',
    'AI Roundup',
    'Hiring Wire',
    'Web Perf Digest',
    'Coffee Dispatch',
    'City Bites',
    'Home and Garden Now',
    'Deal Drop',
    'Fitness Five',
    'Type Foundry Weekly',
    'Growth Notes',
    'Sound and Vision',
    'Weekend Flights',
    'Cold Start',
    'Parent Teacher Notes',
    'Local Sports Wire',
    'Photo School',
    'Weekly Weather Wrap',
    'Board Games Digest',
    'Electric Car Report',
    'Guitar Monthly',
    'Book Club Reminder',
    'Pottery Studio News',
    'Recycling Schedule',
    'Meal Kit Weekly',
    'Running Club Notes',
    'Neighborhood Watch',
    'Streaming Guide',
    'Cinema Listings',
    'Warehouse Deals',
    'Museum Events',
  ],
};

export const summary = {
  unread: 2431,
  needYou: 12,
  handled: 2419,
  repliesDrafted: 9,
  receiptsFiled: 214,
  sendersCut: 41,
};