// GENERATED by tools/var89-generate.mjs from tools/var89-matrix.mjs — do not hand-edit this folder.
// This is animations/we-dont-care-gamble-superbot-89be2ca4/ with the values below; every other file in the folder is that spot unchanged.
export default {
  "id": "chatgpt-memebot-superbot-cae00e0d",
  "voice": "ChatGPT",
  "introLine": "ChatGPT says you shouldn't gamble",
  "redWord": "gamble",
  "slamLine": "WE DONT CARE!",
  "ask": "make me a memecoin trading bot",
  "say": "On it. Wiring the signal, the wallet and the sell ladder.",
  "workTitle": "Memecoin trading bot",
  "site": {
    "slug": "sams-memebot.site",
    "hero": "Memecoin trading bot, live",
    "sub": "412 pairs watched · one signal · sells laddered",
    "totalDisplay": "$31,480",
    "chartLabel": "EQUITY, 30 DAYS",
    "hitsLabel": "OPEN POSITIONS",
    "hitsTitle": "Open positions",
    "rows": [
      [
        "WIF, entry 2.41",
        6820
      ],
      [
        "POPCAT, entry 0.79",
        5140
      ],
      [
        "BONK, entry 0.028",
        3760
      ],
      [
        "MUMU, entry 0.0031",
        2140
      ],
      [
        "Realized, last 30 days",
        13620
      ]
    ],
    "night": {
      "label": "Best day",
      "amount": 4110,
      "sub": "Three sells into the first green candle"
    }
  },
  "steps": [
    "Read 412 pairs on Solana and Base",
    "Backtested the signal on 90 days of candles",
    "Wired the wallet, the take-profit ladder and the kill switch",
    "Deployed sams-memebot.site"
  ]
};
