// GENERATED by tools/var89-generate.mjs from tools/var89-matrix.mjs — do not hand-edit this folder.
// This is animations/we-dont-care-gamble-superbot-89be2ca4/ with the values below; every other file in the folder is that spot unchanged.
export default {
  "id": "grok-polywins-superbot-cae00e0b",
  "voice": "Grok",
  "introLine": "Grok says you shouldn't gamble",
  "redWord": "gamble",
  "slamLine": "WE DONT CARE!",
  "ask": "Make a website of all my Polymarket wins",
  "say": "On it. Every market you called, priced at settlement.",
  "workTitle": "Polymarket wins site",
  "site": {
    "slug": "sams-polywins.site",
    "hero": "All my Polymarket wins",
    "sub": "318 positions · every resolved market · settlement priced",
    "totalDisplay": "$21,340",
    "chartLabel": "CUMULATIVE WINS",
    "hitsLabel": "TOP MARKETS",
    "hitsTitle": "Calls that landed",
    "rows": [
      [
        "Fed cuts in September",
        8200
      ],
      [
        "Chiefs win the Super Bowl",
        5600
      ],
      [
        "BTC above $150k by December",
        3150
      ],
      [
        "Best picture, Oppenheimer",
        2400
      ],
      [
        "Election night sweep",
        1990
      ]
    ],
    "night": {
      "label": "Election night",
      "amount": 6400,
      "sub": "Three markets, all called before midnight"
    }
  },
  "steps": [
    "Read 318 positions from your Polymarket history",
    "Settled every resolved market at final payout",
    "Kept the calls you got right",
    "Built and deployed sams-polywins.site"
  ]
};
