// gh-data.js: the GitHub desk's content (the repo, the 12 issues assigned to you with their closing pull requests,
// the worked issues' root cause, diff, checks, deployment and review decision, the repo's own rules, and the Code tab's
// root listing). GENERATED by /tmp/webdev-ad.80a211a0/tools/gen-ghdata.80a211a0.mjs from
// /tmp/webdev-ad.80a211a0/research/research.json and research/src/supplement-{counts,code}.json; never hand-edited.
// gh.js derives every count on screen from it. research.json's credits[] and legal{} are internal (img/CREDITS.txt).
export const PLACEHOLDER = false;
export const DATA = {
 "fetchedAt": "2026-09-29T11:02:23Z",
 "repo": {
  "fullName": "excalidraw/excalidraw",
  "url": "https://github.com/excalidraw/excalidraw",
  "description": "Virtual whiteboard for sketching hand-drawn like diagrams",
  "stars": 133212,
  "forks": 15517,
  "countsFetchedAt": "2026-09-29T11:02:23Z",
  "license": "MIT",
  "defaultBranch": "master",
  "headSha": "5a406e51875157bece389b9bc92d41ff241d5f3d",
  "openIssues": 2101,
  "openPulls": 1171,
  "openCountsFetchedAt": "2026-09-29T11:29:41Z"
 },
 "day": {
  "iso": "2026-09-26",
  "label": "Sat, Sept. 26, 2026",
  "weekday": "Saturday",
  "issuesClosedByMergedPr": 10,
  "queueIssuesClosedThisDay": 3,
  "basis": "Day with the most issues closed by a merged PR (timeline ClosedEvent closer) between 2026-07-01 and 2026-09-28. Those closes come from only 3 PRs, so the 12-issue queue spans a window instead."
 },
 "window": {
  "from": "2026-08-04T14:31:38Z",
  "to": "2026-09-28T18:51:46Z"
 },
 "issues": [
  {
   "num": 11800,
   "title": "Excalidraw crashes when selecting context menu: \"Edit arrow\"",
   "url": "https://github.com/excalidraw/excalidraw/issues/11800",
   "createdAt": "2026-07-31T12:37:15Z",
   "closedAt": "2026-08-04T14:31:38Z",
   "stateReason": "COMPLETED",
   "labels": [],
   "comments": 0,
   "quotes": [
    "Right click the created arrow and select \"Edit arrow\"",
    "Excalidraw crashes."
   ],
   "hero": false,
   "closedByMerge": true,
   "pr": {
    "num": 11814,
    "title": "fix(editor): prevent crash when editing arrow with bound text",
    "url": "https://github.com/excalidraw/excalidraw/pull/11814",
    "baseRef": "master",
    "mergedAt": "2026-08-04T14:31:37Z",
    "mergeCommitSha": "ab0255f21eb40b5408f3e9ed9725474108eda9e6",
    "additions": 46,
    "deletions": 10,
    "changedFiles": 2,
    "commits": 1,
    "files": [
     {
      "path": "packages/element/tests/linearElementEditor.test.tsx",
      "additions": 40,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/actions/actionLinearEditor.tsx",
      "additions": 6,
      "deletions": 10
     }
    ],
    "headRef": "fix/edit-arrow-crash"
   }
  },
  {
   "num": 11817,
   "title": "Error when selecting \"Change arrow\" from context menu immediately after pasting an arrow",
   "url": "https://github.com/excalidraw/excalidraw/issues/11817",
   "createdAt": "2026-08-04T08:21:41Z",
   "closedAt": "2026-08-04T21:40:29Z",
   "stateReason": "COMPLETED",
   "labels": [],
   "comments": 1,
   "quotes": [
    "Immediately right-click the pasted arrow.",
    "An error occurs after clicking \"Change arrow\"."
   ],
   "hero": false,
   "closedByMerge": false,
   "pr": {
    "num": 11803,
    "title": "fix(editor): initialize selectedLinearElement after pasting arrows",
    "url": "https://github.com/excalidraw/excalidraw/pull/11803",
    "baseRef": "master",
    "mergedAt": "2026-08-04T21:38:15Z",
    "mergeCommitSha": "46c42a6cb0bfc8c096ac4f232d427e10c2d943d1",
    "additions": 2,
    "deletions": 14,
    "changedFiles": 1,
    "commits": 1,
    "files": [
     {
      "path": "packages/excalidraw/components/App.tsx",
      "additions": 2,
      "deletions": 14
     }
    ],
    "headRef": "fix/pasted-arrow-linear-editor"
   }
  },
  {
   "num": 10867,
   "title": "[BUG] Eyedropper applies wrong color in dark theme",
   "url": "https://github.com/excalidraw/excalidraw/issues/10867",
   "createdAt": "2026-03-01T00:51:53Z",
   "closedAt": "2026-08-08T21:17:28Z",
   "stateReason": "COMPLETED",
   "labels": [],
   "comments": 0,
   "quotes": [
    "In dark theme, applied color can differ from sampled visual color.",
    "The applied color should match what was visually sampled under cursor."
   ],
   "hero": false,
   "closedByMerge": true,
   "pr": {
    "num": 11859,
    "title": "feat(editor): eyedropper fixes and improvements",
    "url": "https://github.com/excalidraw/excalidraw/pull/11859",
    "baseRef": "master",
    "mergedAt": "2026-08-08T21:17:27Z",
    "mergeCommitSha": "cf212b2f3354c09bd6f960b53a9cfb0a3ecbfa58",
    "additions": 234,
    "deletions": 47,
    "changedFiles": 11,
    "commits": 4,
    "files": [
     {
      "path": "packages/common/src/colors.test.ts",
      "additions": 19,
      "deletions": 0
     },
     {
      "path": "packages/common/src/colors.ts",
      "additions": 48,
      "deletions": 13
     },
     {
      "path": "packages/excalidraw/actions/actionProperties.tsx",
      "additions": 1,
      "deletions": 2
     },
     {
      "path": "packages/excalidraw/components/App.bucketFill.ts",
      "additions": 26,
      "deletions": 5
     },
     {
      "path": "packages/excalidraw/components/App.cursor.ts",
      "additions": 10,
      "deletions": 11
     },
     {
      "path": "packages/excalidraw/components/EyeDropper.scss",
      "additions": 5,
      "deletions": 5
     },
     {
      "path": "packages/excalidraw/components/EyeDropper.tsx",
      "additions": 39,
      "deletions": 5
     },
     {
      "path": "packages/excalidraw/components/icons.tsx",
      "additions": 8,
      "deletions": 2
     },
     {
      "path": "packages/excalidraw/tests/bucketFill.test.tsx",
      "additions": 1,
      "deletions": 2
     },
     {
      "path": "packages/excalidraw/tests/eyeDropper.test.tsx",
      "additions": 76,
      "deletions": 2
     },
     {
      "path": "packages/excalidraw/types.ts",
      "additions": 1,
      "deletions": 0
     }
    ],
    "headRef": "eyedropper-improvements"
   }
  },
  {
   "num": 11809,
   "title": "Select on \"wrap\" vs \"overlap\" for FREEFORM lasso tool",
   "url": "https://github.com/excalidraw/excalidraw/issues/11809",
   "createdAt": "2026-08-01T23:14:49Z",
   "closedAt": "2026-08-10T11:09:45Z",
   "stateReason": "COMPLETED",
   "labels": [],
   "comments": 4,
   "quotes": [
    "I use the freeform lasso tool almost exclusively, and I want to be able to make the tool select on wrap rather than select on overlap."
   ],
   "hero": false,
   "closedByMerge": true,
   "pr": {
    "num": 11862,
    "title": "fix(editor): respect boxSelectionMode ('contain' vs 'overlap') in lasso tool",
    "url": "https://github.com/excalidraw/excalidraw/pull/11862",
    "baseRef": "master",
    "mergedAt": "2026-08-10T11:09:44Z",
    "mergeCommitSha": "c5a50d223feb5fceaebc916ad75f2dcecb399467",
    "additions": 715,
    "deletions": 60,
    "changedFiles": 4,
    "commits": 7,
    "files": [
     {
      "path": "packages/excalidraw/lasso/index.ts",
      "additions": 2,
      "deletions": 22
     },
     {
      "path": "packages/excalidraw/lasso/utils.ts",
      "additions": 292,
      "deletions": 35
     },
     {
      "path": "packages/excalidraw/tests/lasso.test.tsx",
      "additions": 415,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/tests/selection.test.tsx",
      "additions": 6,
      "deletions": 3
     }
    ],
    "headRef": "fix/lasso-box-selection-mode"
   }
  },
  {
   "num": 11876,
   "title": "\"Sign up\" menu item is hardcoded and not localizable (English in every locale)",
   "url": "https://github.com/excalidraw/excalidraw/issues/11876",
   "createdAt": "2026-08-12T23:21:52Z",
   "closedAt": "2026-08-16T13:20:17Z",
   "stateReason": "COMPLETED",
   "labels": [],
   "comments": 0,
   "quotes": [
    "This is not a missing translation: the string is not registered in the i18n system at all, so translators cannot fix it on Crowdin."
   ],
   "hero": true,
   "closedByMerge": true,
   "pr": {
    "num": 11893,
    "title": "fix(app): localize hardcoded \"Sign up\"/\"Sign in\" menu labels",
    "url": "https://github.com/excalidraw/excalidraw/pull/11893",
    "baseRef": "master",
    "mergedAt": "2026-08-16T13:20:16Z",
    "mergeCommitSha": "884225b1c7ba08d2cd506e487f5f699a52bd821b",
    "additions": 6,
    "deletions": 2,
    "changedFiles": 3,
    "commits": 1,
    "files": [
     {
      "path": "excalidraw-app/components/AppMainMenu.tsx",
      "additions": 3,
      "deletions": 1
     },
     {
      "path": "excalidraw-app/components/AppWelcomeScreen.tsx",
      "additions": 1,
      "deletions": 1
     },
     {
      "path": "packages/excalidraw/locales/en.json",
      "additions": 2,
      "deletions": 0
     }
    ],
    "headRef": "fix/localize-signup-signin-labels"
   }
  },
  {
   "num": 9338,
   "title": "Allow moving arrow label along arrow length",
   "url": "https://github.com/excalidraw/excalidraw/issues/9338",
   "createdAt": "2025-04-04T08:09:27Z",
   "closedAt": "2026-09-03T15:21:14Z",
   "stateReason": "COMPLETED",
   "labels": [
    {
     "name": "UX/UI",
     "color": "f9d0c4"
    }
   ],
   "comments": 9,
   "quotes": [
    "The only missing feature for me in Excalidraw is being able to move the label on an arrow along the length of an arrow."
   ],
   "hero": false,
   "closedByMerge": true,
   "pr": {
    "num": 10947,
    "title": "feat(editor): allow for dragging bound text along an arrow's path",
    "url": "https://github.com/excalidraw/excalidraw/pull/10947",
    "baseRef": "master",
    "mergedAt": "2026-09-03T15:21:13Z",
    "mergeCommitSha": "214cd6e6e8ac3ad6b68486aa7aa7241abdf9445f",
    "additions": 1290,
    "deletions": 205,
    "changedFiles": 26,
    "commits": 45,
    "files": [
     {
      "path": "packages/element/src/__tests__/__snapshots__/transform.test.ts.snap",
      "additions": 28,
      "deletions": 3
     },
     {
      "path": "packages/element/src/linearElementEditor.ts",
      "additions": 314,
      "deletions": 8
     },
     {
      "path": "packages/element/src/newElement.ts",
      "additions": 2,
      "deletions": 0
     },
     {
      "path": "packages/element/src/textElement.ts",
      "additions": 2,
      "deletions": 0
     },
     {
      "path": "packages/element/src/transform.ts",
      "additions": 7,
      "deletions": 1
     },
     {
      "path": "packages/element/src/types.ts",
      "additions": 7,
      "deletions": 0
     },
     {
      "path": "packages/element/src/utils.ts",
      "additions": 40,
      "deletions": 7
     },
     {
      "path": "packages/element/tests/binding.test.tsx",
      "additions": 3,
      "deletions": 0
     },
     {
      "path": "packages/element/tests/linearElementEditor.test.tsx",
      "additions": 366,
      "deletions": 11
     },
     {
      "path": "packages/element/tests/resize.test.tsx",
      "additions": 63,
      "deletions": 25
     },
     {
      "path": "packages/excalidraw/actions/actionBoundText.tsx",
      "additions": 5,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/actions/actionFinalize.tsx",
      "additions": 5,
      "deletions": 1
     },
     {
      "path": "packages/excalidraw/components/App.arrowText.ts",
      "additions": 123,
      "deletions": 8
     },
     {
      "path": "packages/excalidraw/components/App.cursor.ts",
      "additions": 35,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/components/App.tsx",
      "additions": 102,
      "deletions": 67
     },
     {
      "path": "packages/excalidraw/data/restore.ts",
      "additions": 9,
      "deletions": 1
     },
     {
      "path": "packages/excalidraw/renderer/staticSvgScene.ts",
      "additions": 14,
      "deletions": 4
     },
     {
      "path": "packages/excalidraw/tests/__snapshots__/export.test.tsx.snap",
      "additions": 1,
      "deletions": 1
     },
     {
      "path": "packages/excalidraw/tests/__snapshots__/history.test.tsx.snap",
      "additions": 27,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/tests/data/__snapshots__/restore.test.ts.snap",
      "additions": 2,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/tests/scene/export.test.ts",
      "additions": 54,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/tests/selection.test.tsx",
      "additions": 2,
      "deletions": 2
     },
     {
      "path": "packages/excalidraw/types.ts",
      "additions": 4,
      "deletions": 0
     },
     {
      "path": "packages/math/src/curve.ts",
      "additions": 30,
      "deletions": 31
     },
     {
      "path": "packages/math/src/segment.ts",
      "additions": 40,
      "deletions": 31
     },
     {
      "path": "packages/math/tests/curve.test.ts",
      "additions": 5,
      "deletions": 4
     }
    ],
    "headRef": "feat/boundText_arrow_move_proto"
   }
  },
  {
   "num": 7332,
   "title": "Poor dark mode drawing performance in Firefox - 116.0.2 on Ubuntu/Linux",
   "url": "https://github.com/excalidraw/excalidraw/issues/7332",
   "createdAt": "2023-11-23T12:24:34Z",
   "closedAt": "2026-09-07T09:52:24Z",
   "stateReason": "COMPLETED",
   "labels": [
    {
     "name": "bug",
     "color": "d73a4a"
    },
    {
     "name": "high priority",
     "color": "d73a4a"
    }
   ],
   "comments": 8,
   "quotes": [
    "I am experiencing very poor performance using dark mode under Firefox",
    "Dark mode : ~5-10 fps drawing changes,"
   ],
   "hero": true,
   "closedByMerge": true,
   "pr": {
    "num": 12050,
    "title": "perf(editor): stop inverting the interactive canvas via CSS filter in dark mode",
    "url": "https://github.com/excalidraw/excalidraw/pull/12050",
    "baseRef": "master",
    "mergedAt": "2026-09-07T09:52:23Z",
    "mergeCommitSha": "f1a79b73df5b9883f940417861a4f5fb879a3f02",
    "additions": 157,
    "deletions": 85,
    "changedFiles": 10,
    "commits": 1,
    "files": [
     {
      "path": "packages/common/src/colors.ts",
      "additions": 13,
      "deletions": 0
     },
     {
      "path": "packages/element/src/renderElement.ts",
      "additions": 4,
      "deletions": 1
     },
     {
      "path": "packages/excalidraw/clients.ts",
      "additions": 1,
      "deletions": 4
     },
     {
      "path": "packages/excalidraw/components/canvases/InteractiveCanvas.tsx",
      "additions": 2,
      "deletions": 6
     },
     {
      "path": "packages/excalidraw/css/styles.scss",
      "additions": 0,
      "deletions": 3
     },
     {
      "path": "packages/excalidraw/css/theme.scss",
      "additions": 1,
      "deletions": 1
     },
     {
      "path": "packages/excalidraw/lasso/index.ts",
      "additions": 10,
      "deletions": 3
     },
     {
      "path": "packages/excalidraw/renderer/helpers.ts",
      "additions": 12,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/renderer/interactiveScene.ts",
      "additions": 105,
      "deletions": 62
     },
     {
      "path": "packages/excalidraw/renderer/renderSnaps.ts",
      "additions": 9,
      "deletions": 5
     }
    ],
    "headRef": "interactive-canvas-dark-colors"
   }
  },
  {
   "num": 10189,
   "title": "[BUG] Text editor shifts canvas and creates white space when editing near edges",
   "url": "https://github.com/excalidraw/excalidraw/issues/10189",
   "createdAt": "2025-10-17T22:32:26Z",
   "closedAt": "2026-09-26T21:00:31Z",
   "stateReason": "COMPLETED",
   "labels": [],
   "comments": 2,
   "quotes": [
    "Observe that the canvas shifts and white space appears.",
    "The text editor’s position exceeds the visible canvas area, causing unwanted canvas movement and white space to appear."
   ],
   "hero": false,
   "closedByMerge": true,
   "pr": {
    "num": 12175,
    "title": "fix(editor): pan the canvas to follow the caret instead of shifting the UI",
    "url": "https://github.com/excalidraw/excalidraw/pull/12175",
    "baseRef": "master",
    "mergedAt": "2026-09-26T21:00:28Z",
    "mergeCommitSha": "f3d99c42e905706c1899bd887cfec59f2e92f425",
    "additions": 696,
    "deletions": 46,
    "changedFiles": 11,
    "commits": 9,
    "files": [
     {
      "path": "packages/common/src/constants.ts",
      "additions": 3,
      "deletions": 0
     },
     {
      "path": "packages/element/src/newElement.ts",
      "additions": 33,
      "deletions": 1
     },
     {
      "path": "packages/element/tests/__snapshots__/linearElementEditor.test.tsx.snap",
      "additions": 1,
      "deletions": 1
     },
     {
      "path": "packages/excalidraw/components/App.tsx",
      "additions": 75,
      "deletions": 2
     },
     {
      "path": "packages/excalidraw/components/App.viewport.ts",
      "additions": 39,
      "deletions": 4
     },
     {
      "path": "packages/excalidraw/css/styles.scss",
      "additions": 17,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/tests/clipboard.test.tsx",
      "additions": 58,
      "deletions": 1
     },
     {
      "path": "packages/excalidraw/tests/viewport.test.ts",
      "additions": 76,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/viewport.ts",
      "additions": 57,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/wysiwyg/textWysiwyg.test.tsx",
      "additions": 235,
      "deletions": 5
     },
     {
      "path": "packages/excalidraw/wysiwyg/textWysiwyg.tsx",
      "additions": 102,
      "deletions": 32
     }
    ],
    "headRef": "fix-caret-overflow"
   }
  },
  {
   "num": 12176,
   "title": "Instant replacement when drag-and-drop'ing a .excaildraw file",
   "url": "https://github.com/excalidraw/excalidraw/issues/12176",
   "createdAt": "2026-09-26T17:18:15Z",
   "closedAt": "2026-09-26T22:18:03Z",
   "stateReason": "COMPLETED",
   "labels": [],
   "comments": 2,
   "quotes": [
    "Is this the expected behavior?",
    "I lost all my previous work due to this issue."
   ],
   "hero": false,
   "closedByMerge": true,
   "pr": {
    "num": 12177,
    "title": "feat(editor): file drop overlay & shift-to-merge imported scene",
    "url": "https://github.com/excalidraw/excalidraw/pull/12177",
    "baseRef": "master",
    "mergedAt": "2026-09-26T22:18:02Z",
    "mergeCommitSha": "d29d864884782305950122439f54f8dbb5c1bcb0",
    "additions": 799,
    "deletions": 27,
    "changedFiles": 10,
    "commits": 10,
    "files": [
     {
      "path": "packages/excalidraw/components/App.tsx",
      "additions": 80,
      "deletions": 22
     },
     {
      "path": "packages/excalidraw/components/FileDropOverlay.scss",
      "additions": 167,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/components/FileDropOverlay.tsx",
      "additions": 188,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/components/Modal.scss",
      "additions": 1,
      "deletions": 1
     },
     {
      "path": "packages/excalidraw/css/styles.scss",
      "additions": 1,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/css/theme.scss",
      "additions": 2,
      "deletions": 2
     },
     {
      "path": "packages/excalidraw/hooks/useCreatePortalContainer.ts",
      "additions": 16,
      "deletions": 1
     },
     {
      "path": "packages/excalidraw/locales/en.json",
      "additions": 9,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/tests/__snapshots__/history.test.tsx.snap",
      "additions": 5,
      "deletions": 1
     },
     {
      "path": "packages/excalidraw/tests/fileDrop.test.tsx",
      "additions": 330,
      "deletions": 0
     }
    ],
    "headRef": "dnd-overlay"
   }
  },
  {
   "num": 11914,
   "title": "Cmd/Ctrl+Shift+S does nothing while editing text",
   "url": "https://github.com/excalidraw/excalidraw/issues/11914",
   "createdAt": "2026-08-19T17:48:15Z",
   "closedAt": "2026-09-26T22:38:05Z",
   "stateReason": "COMPLETED",
   "labels": [],
   "comments": 2,
   "quotes": [
    "Shift variant: nothing happens. Editor stays open, no save dialog.",
    "Plain variant: commits the text and saves, as expected."
   ],
   "hero": true,
   "closedByMerge": true,
   "pr": {
    "num": 11922,
    "title": "fix(editor): handle the save-as shortcut while editing text",
    "url": "https://github.com/excalidraw/excalidraw/pull/11922",
    "baseRef": "master",
    "mergedAt": "2026-09-26T22:38:04Z",
    "mergeCommitSha": "afed9e6e27dd1cd5cc52857a405f7bea5312d813",
    "additions": 30,
    "deletions": 2,
    "changedFiles": 2,
    "commits": 3,
    "files": [
     {
      "path": "packages/excalidraw/wysiwyg/textWysiwyg.test.tsx",
      "additions": 24,
      "deletions": 0
     },
     {
      "path": "packages/excalidraw/wysiwyg/textWysiwyg.tsx",
      "additions": 6,
      "deletions": 2
     }
    ],
    "headRef": "fix/save-as-shortcut-in-text-editor"
   }
  },
  {
   "num": 11761,
   "title": "Docs: Remove obsolete CodeSandbox contribution workflow",
   "url": "https://github.com/excalidraw/excalidraw/issues/11761",
   "createdAt": "2026-07-25T03:56:15Z",
   "closedAt": "2026-09-27T20:53:19Z",
   "stateReason": "COMPLETED",
   "labels": [],
   "comments": 0,
   "quotes": [
    "I have observed that  https://codesandbox.io/p/github/excalidraw/excalidraw is no more functional."
   ],
   "hero": false,
   "closedByMerge": true,
   "pr": {
    "num": 11908,
    "title": "docs(repo): remove obsolete CodeSandbox contribution workflow",
    "url": "https://github.com/excalidraw/excalidraw/pull/11908",
    "baseRef": "master",
    "mergedAt": "2026-09-27T20:53:18Z",
    "mergeCommitSha": "438d89861f53d8a90ad566113ecac1b83761098f",
    "additions": 0,
    "deletions": 17,
    "changedFiles": 2,
    "commits": 2,
    "files": [
     {
      "path": "dev-docs/docs/introduction/contributing.mdx",
      "additions": 0,
      "deletions": 11
     },
     {
      "path": "dev-docs/docs/introduction/development.mdx",
      "additions": 0,
      "deletions": 6
     }
    ],
    "headRef": "docs/remove-obsolete-codesandbox-workflow"
   }
  },
  {
   "num": 12182,
   "title": "Typo in Mermaid input placeholder: \"defintion\" should be \"definition\"",
   "url": "https://github.com/excalidraw/excalidraw/issues/12182",
   "createdAt": "2026-09-27T13:35:50Z",
   "closedAt": "2026-09-28T18:51:46Z",
   "stateReason": "COMPLETED",
   "labels": [],
   "comments": 2,
   "quotes": [
    "The English Mermaid input placeholder contains a small spelling mistake."
   ],
   "hero": true,
   "closedByMerge": false,
   "pr": {
    "num": 12186,
    "title": "fix(app): correct typo in Mermaid input placeholder",
    "url": "https://github.com/excalidraw/excalidraw/pull/12186",
    "baseRef": "master",
    "mergedAt": "2026-09-28T22:18:03Z",
    "mergeCommitSha": "5a406e51875157bece389b9bc92d41ff241d5f3d",
    "additions": 1,
    "deletions": 1,
    "changedFiles": 1,
    "commits": 1,
    "files": [
     {
      "path": "packages/excalidraw/locales/en.json",
      "additions": 1,
      "deletions": 1
     }
    ],
    "headRef": "fix/mermaid-placeholder-typo"
   }
  }
 ],
 "heroes": {
  "7332": {
   "pr": 12050,
   "cause": "In dark mode the full-viewport interactive canvas was drawn through a CSS invert filter (filter: var(--theme-filter)) on every repaint; the fix removes that filter.",
   "diff": [
    {
     "path": "packages/excalidraw/css/styles.scss",
     "hunkHeader": "@@ -115,9 +115,6 @@ body.excalidraw-cursor-resize * {",
     "lines": [
      [
       " ",
       ""
      ],
      [
       " ",
       "    &.interactive {"
      ],
      [
       " ",
       "      z-index: var(--zIndex-interactiveCanvas);"
      ],
      [
       "-",
       "      // Apply theme filter only to interactive canvas for UI elements"
      ],
      [
       "-",
       "      // (resize handles, selection boxes, etc.)"
      ],
      [
       "-",
       "      filter: var(--theme-filter);"
      ],
      [
       " ",
       "    }"
      ],
      [
       " ",
       ""
      ],
      [
       " ",
       "    // Remove the main canvas from document flow to avoid resizeObserver"
      ]
     ]
    }
   ],
   "checks": [
    {
     "kind": "check_run",
     "name": "Analyze (actions)",
     "workflow": "PR #12050",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 34,
     "latestForName": true,
     "event": "dynamic"
    },
    {
     "kind": "check_run",
     "name": "Analyze (javascript-typescript)",
     "workflow": "PR #12050",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 93,
     "latestForName": true,
     "event": "dynamic"
    },
    {
     "kind": "check_run",
     "name": "cancel",
     "workflow": "Cancel previous runs",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 3,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "coverage",
     "workflow": "Test Coverage PR",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 311,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "lint",
     "workflow": "Lint",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 116,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "semantic",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 4,
     "latestForName": false,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "label-scope",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 3,
     "latestForName": false,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "CodeQL",
     "workflow": "GitHub Advanced Security",
     "app": "github-advanced-security",
     "conclusion": "success",
     "secs": 3,
     "latestForName": true,
     "summary": "No new alerts in code changed by this pull request"
    },
    {
     "kind": "check_run",
     "name": "semantic",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 4,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "label-scope",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 3,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "commit_status",
     "name": "CodeRabbit",
     "workflow": null,
     "app": null,
     "conclusion": "success",
     "secs": 0,
     "latestForName": true,
     "description": "Review skipped: automatic reviews are disabled"
    },
    {
     "kind": "commit_status",
     "name": "Vercel – excalidraw",
     "workflow": null,
     "app": null,
     "conclusion": "success",
     "secs": 0,
     "latestForName": true,
     "description": "Deployment has completed"
    }
   ],
   "deployment": {
    "provider": "Vercel",
    "environment": "Preview – excalidraw",
    "state": "success",
    "createdAt": "2026-09-06T14:32:32Z",
    "url": "https://excalidraw-d087cd0d3-excalidraw.vercel.app",
    "description": "Deployment has completed"
   },
   "reviewDecision": "REVIEW_REQUIRED"
  },
  "11876": {
   "pr": 11893,
   "cause": "The main menu rendered the hardcoded English strings \"Sign in\" and \"Sign up\" instead of looking them up with t(), so no locale could translate them.",
   "diff": [
    {
     "path": "excalidraw-app/components/AppMainMenu.tsx",
     "hunkHeader": "@@ -56,7 +58,7 @@ export const AppMainMenu: React.FC<{",
     "lines": [
      [
       " ",
       "        }?utm_source=signin&utm_medium=app&utm_content=hamburger`}"
      ],
      [
       " ",
       "        className=\"highlighted\""
      ],
      [
       " ",
       "      >"
      ],
      [
       "-",
       "        {isExcalidrawPlusSignedUser ? \"Sign in\" : \"Sign up\"}"
      ],
      [
       "+",
       "        {isExcalidrawPlusSignedUser ? t(\"labels.signIn\") : t(\"labels.signUp\")}"
      ],
      [
       " ",
       "      </MainMenu.ItemLink>"
      ],
      [
       " ",
       "      {isDevEnv() && ("
      ],
      [
       " ",
       "        <MainMenu.Item"
      ]
     ]
    }
   ],
   "checks": [
    {
     "kind": "check_run",
     "name": "cancel",
     "workflow": "Cancel previous runs",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 4,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "coverage",
     "workflow": "Test Coverage PR",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 241,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "lint",
     "workflow": "Lint",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 106,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "semantic",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "failure",
     "secs": 4,
     "latestForName": false,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "label-scope",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "skipped",
     "secs": 0,
     "latestForName": false,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "semantic",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 6,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "label-scope",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "skipped",
     "secs": 0,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "commit_status",
     "name": "CodeRabbit",
     "workflow": null,
     "app": null,
     "conclusion": "success",
     "secs": 0,
     "latestForName": true,
     "description": "Review skipped: automatic reviews are disabled"
    },
    {
     "kind": "commit_status",
     "name": "Vercel – excalidraw",
     "workflow": null,
     "app": null,
     "conclusion": "success",
     "secs": 0,
     "latestForName": true,
     "description": "Deployment has completed"
    }
   ],
   "deployment": {
    "provider": "Vercel",
    "environment": "Preview – excalidraw",
    "state": "success",
    "createdAt": "2026-08-16T08:59:19Z",
    "url": "https://excalidraw-cfin69zl6-excalidraw.vercel.app",
    "description": "Deployment has completed"
   },
   "reviewDecision": "APPROVED"
  },
  "11914": {
   "pr": 11922,
   "cause": "The text editor keydown handler had a branch for Cmd/Ctrl+S (actionSaveToActiveFile) but none for the save-as shortcut (actionSaveFileToDisk), so it did nothing.",
   "diff": [
    {
     "path": "packages/excalidraw/wysiwyg/textWysiwyg.tsx",
     "hunkHeader": "@@ -651,7 +651,11 @@ export const textWysiwyg = ({",
     "lines": [
      [
       " ",
       "    } else if (actionSaveToActiveFile.keyTest(event)) {"
      ],
      [
       " ",
       "      event.preventDefault();"
      ],
      [
       " ",
       "      handleSubmit();"
      ],
      [
       "-",
       "      app.actionManager.executeAction(actionSaveToActiveFile);"
      ],
      [
       "+",
       "      app.actionManager.executeAction(actionSaveToActiveFile, \"keyboard\");"
      ],
      [
       "+",
       "    } else if (actionSaveFileToDisk.keyTest(event)) {"
      ],
      [
       "+",
       "      event.preventDefault();"
      ],
      [
       "+",
       "      handleSubmit();"
      ],
      [
       "+",
       "      app.actionManager.executeAction(actionSaveFileToDisk, \"keyboard\");"
      ],
      [
       " ",
       "    } else if (event.key === KEYS.ENTER && event[KEYS.CTRL_OR_CMD]) {"
      ],
      [
       " ",
       "      event.preventDefault();"
      ],
      [
       " ",
       "      if (event.isComposing || event.keyCode === 229) {"
      ]
     ]
    }
   ],
   "checks": [
    {
     "kind": "check_run",
     "name": "cancel",
     "workflow": "Cancel previous runs",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 4,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "coverage",
     "workflow": "Test Coverage PR",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 355,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "semantic",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 5,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "lint",
     "workflow": "Lint",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 121,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "label-scope",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "skipped",
     "secs": 0,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "commit_status",
     "name": "CodeRabbit",
     "workflow": null,
     "app": null,
     "conclusion": "success",
     "secs": 0,
     "latestForName": true,
     "description": "Review skipped: automatic reviews are disabled"
    },
    {
     "kind": "commit_status",
     "name": "Vercel – excalidraw",
     "workflow": null,
     "app": null,
     "conclusion": "success",
     "secs": 0,
     "latestForName": true,
     "description": "Deployment has completed"
    }
   ],
   "deployment": {
    "provider": "Vercel",
    "environment": "Preview – excalidraw",
    "state": "success",
    "createdAt": "2026-09-26T22:32:27Z",
    "url": "https://excalidraw-7mqc7miws-excalidraw.vercel.app",
    "description": "Deployment has completed"
   },
   "reviewDecision": "APPROVED"
  },
  "12182": {
   "pr": 12186,
   "cause": "The en.json placeholder string for the Mermaid input misspelled \"definition\" as \"defintion\".",
   "diff": [
    {
     "path": "packages/excalidraw/locales/en.json",
     "hunkHeader": "@@ -675,7 +675,7 @@",
     "lines": [
      [
       " ",
       "    \"syntax\": \"Mermaid Syntax\","
      ],
      [
       " ",
       "    \"preview\": \"Preview\","
      ],
      [
       " ",
       "    \"label\": \"Mermaid\","
      ],
      [
       "-",
       "    \"inputPlaceholder\": \"Write Mermaid diagram defintion here...\","
      ],
      [
       "+",
       "    \"inputPlaceholder\": \"Write Mermaid diagram definition here...\","
      ],
      [
       " ",
       "    \"autoFixAvailable\": \"Auto-fix is available\""
      ],
      [
       " ",
       "  },"
      ],
      [
       " ",
       "  \"ttd\": {"
      ]
     ]
    }
   ],
   "checks": [
    {
     "kind": "check_run",
     "name": "cancel",
     "workflow": "Cancel previous runs",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 5,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "coverage",
     "workflow": "Test Coverage PR",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 262,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "lint",
     "workflow": "Lint",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 124,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "semantic",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "failure",
     "secs": 3,
     "latestForName": false,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "label-scope",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "skipped",
     "secs": 0,
     "latestForName": false,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "semantic",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 3,
     "latestForName": false,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "semantic",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "success",
     "secs": 5,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "label-scope",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "skipped",
     "secs": 0,
     "latestForName": false,
     "event": "pull_request"
    },
    {
     "kind": "check_run",
     "name": "label-scope",
     "workflow": "Semantic PR title",
     "app": "github-actions",
     "conclusion": "skipped",
     "secs": 0,
     "latestForName": true,
     "event": "pull_request"
    },
    {
     "kind": "commit_status",
     "name": "CodeRabbit",
     "workflow": null,
     "app": null,
     "conclusion": "success",
     "secs": 0,
     "latestForName": true,
     "description": "Review skipped: automatic reviews are disabled"
    },
    {
     "kind": "commit_status",
     "name": "Vercel – excalidraw",
     "workflow": null,
     "app": null,
     "conclusion": "success",
     "secs": 0,
     "latestForName": true,
     "description": "Deployment has completed"
    }
   ],
   "deployment": {
    "provider": "Vercel",
    "environment": "Preview – excalidraw",
    "state": "success",
    "createdAt": "2026-09-27T18:44:21Z",
    "url": "https://excalidraw-8wxudq358-excalidraw.vercel.app",
    "description": "Deployment has completed"
   },
   "reviewDecision": "APPROVED"
  }
 },
 "rules": [
  {
   "file": "dev-docs/docs/introduction/contributing.mdx",
   "url": "https://github.com/excalidraw/excalidraw/blob/5a406e51875157bece389b9bc92d41ff241d5f3d/dev-docs/docs/introduction/contributing.mdx#L30",
   "line": 30,
   "text": "Make sure the title starts with a semantic prefix:"
  },
  {
   "file": "dev-docs/docs/introduction/contributing.mdx",
   "url": "https://github.com/excalidraw/excalidraw/blob/5a406e51875157bece389b9bc92d41ff241d5f3d/dev-docs/docs/introduction/contributing.mdx#L33",
   "line": 33,
   "text": "- **fix**: A bug fix"
  },
  {
   "file": "dev-docs/docs/introduction/contributing.mdx",
   "url": "https://github.com/excalidraw/excalidraw/blob/5a406e51875157bece389b9bc92d41ff241d5f3d/dev-docs/docs/introduction/contributing.mdx#L48",
   "line": 48,
   "text": "For example, it's good practice to create a test for each bug you fix which ensures that we don't regress the code in the future."
  },
  {
   "file": "dev-docs/docs/introduction/contributing.mdx",
   "url": "https://github.com/excalidraw/excalidraw/blob/5a406e51875157bece389b9bc92d41ff241d5f3d/dev-docs/docs/introduction/contributing.mdx#L50",
   "line": 50,
   "text": "Finally - always manually test your changes using the convenient staging environment deployed for each pull request."
  },
  {
   "file": ".github/workflows/semantic-pr-title.yml",
   "url": "https://github.com/excalidraw/excalidraw/blob/5a406e51875157bece389b9bc92d41ff241d5f3d/.github/workflows/semantic-pr-title.yml#L32",
   "line": 32,
   "text": "requireScope: true"
  },
  {
   "file": "package.json",
   "url": "https://github.com/excalidraw/excalidraw/blob/5a406e51875157bece389b9bc92d41ff241d5f3d/package.json#L72",
   "line": 72,
   "text": "\"test:typecheck\": \"tsc\","
  },
  {
   "file": "package.json",
   "url": "https://github.com/excalidraw/excalidraw/blob/5a406e51875157bece389b9bc92d41ff241d5f3d/package.json#L70",
   "line": 70,
   "text": "\"test:code\": \"eslint --max-warnings=0 --ext .js,.ts,.tsx .\","
  },
  {
   "file": "package.json",
   "url": "https://github.com/excalidraw/excalidraw/blob/5a406e51875157bece389b9bc92d41ff241d5f3d/package.json#L80",
   "line": 80,
   "text": "\"fix\": \"yarn fix:other && yarn fix:code\","
  },
  {
   "file": ".eslintrc.json",
   "url": "https://github.com/excalidraw/excalidraw/blob/5a406e51875157bece389b9bc92d41ff241d5f3d/.eslintrc.json#L54",
   "line": 54,
   "text": "Do not import from the barrel 'index.tsx' files. Use direct relative imports to the specific module instead."
  },
  {
   "file": ".editorconfig",
   "url": "https://github.com/excalidraw/excalidraw/blob/5a406e51875157bece389b9bc92d41ff241d5f3d/.editorconfig#L9",
   "line": 9,
   "text": "indent_size = 2"
  },
  {
   "file": "index.json",
   "url": "https://github.com/excalidraw/prettier-config/blob/44adfaf84f73a125c81f2f60c647087ec198fba1/index.json#L4",
   "line": 4,
   "text": "\"trailingComma\": \"all\","
  }
 ],
 "code": {
  "commit": {
   "sha": "792ea3a06c60079229f36819d8695af7d563832a",
   "message": "feat(editor): bucket fill (#11799)",
   "date": "2026-08-04T14:25:16Z"
  },
  "basis": "excalidraw/excalidraw at 792ea3a06c60079229f36819d8695af7d563832a, the parent of ab0255f21eb40b5408f3e9ed9725474108eda9e6 (the merge of #11814, the earliest fix in the queue)",
  "entries": [
   {
    "name": ".codesandbox",
    "dir": true,
    "message": "chore(docker): bump node (#11208)",
    "date": "2026-04-20T20:07:00Z",
    "sha": "b1c6bfcf40cba255d208d8d525060684b10cb3cc"
   },
   {
    "name": ".github",
    "dir": true,
    "message": "ci(repo): skip docs & example deployments in CI (#11674)",
    "date": "2026-07-16T14:36:11Z",
    "sha": "344878b0b5f34daf013cc5656bd78c72dfdd61d6"
   },
   {
    "name": ".husky",
    "dir": true,
    "message": "build: temporarily disable pre-commit (#6132)",
    "date": "2023-01-19T12:50:42Z",
    "sha": "d0b33d35db37f695f3962ac463c10c1c7fbe1a9c"
   },
   {
    "name": "dev-docs",
    "dir": true,
    "message": "ci(repo): skip docs & example deployments in CI (#11674)",
    "date": "2026-07-16T14:36:11Z",
    "sha": "344878b0b5f34daf013cc5656bd78c72dfdd61d6"
   },
   {
    "name": "examples",
    "dir": true,
    "message": "ci(repo): skip docs & example deployments in CI (#11674)",
    "date": "2026-07-16T14:36:11Z",
    "sha": "344878b0b5f34daf013cc5656bd78c72dfdd61d6"
   },
   {
    "name": "excalidraw-app",
    "dir": true,
    "message": "feat(packages/excalidraw):  add `props.ui.enabled.zoom/scrollBackToContent` (#11677)",
    "date": "2026-07-16T17:50:19Z",
    "sha": "93dd51060a305108450b18b87b39f1b3b2125995"
   },
   {
    "name": "firebase-project",
    "dir": true,
    "message": "fix: update `storage.rules` (#5020)",
    "date": "2022-04-17T20:47:00Z",
    "sha": "7431ca81d1f4cf53242d749f25b80295719e7a08"
   },
   {
    "name": "packages",
    "dir": true,
    "message": "feat(editor): bucket fill (#11799)",
    "date": "2026-08-04T14:25:16Z",
    "sha": "792ea3a06c60079229f36819d8695af7d563832a"
   },
   {
    "name": "public",
    "dir": true,
    "message": "feat(editor): tweak sidebar promo style (#11181)",
    "date": "2026-07-09T09:41:13Z",
    "sha": "f790bf7abdba43cda99440bdc74ba19cb338ea27"
   },
   {
    "name": "scripts",
    "dir": true,
    "message": "fix: Fractional index validation (#11258)",
    "date": "2026-05-04T09:37:17Z",
    "sha": "3004c642dab239b4e060f7da5c3ac12d2dc9691d"
   },
   {
    "name": ".dockerignore",
    "dir": false,
    "message": "fix: Docker build in CI (#8312)",
    "date": "2024-08-06T11:21:20Z",
    "sha": "8d530cf10266414078cfd483b8daad963f1954f1"
   },
   {
    "name": ".editorconfig",
    "dir": false,
    "message": "add editorconfig (#1198)",
    "date": "2020-04-03T17:19:01Z",
    "sha": "8dccc793eebd13eb080fd42d80631ef8a8422d4e"
   },
   {
    "name": ".env.development",
    "dir": false,
    "message": "feat: TextToDiagram v2 (#10530)",
    "date": "2026-01-15T18:15:41Z",
    "sha": "a0b98a944f1ddedba090b8a6908ff38b9132177e"
   },
   {
    "name": ".env.production",
    "dir": false,
    "message": "Fix import.meta.env.MODE being undefined in host apps",
    "date": "2025-05-22T13:25:48Z",
    "sha": "14d512f32136b376707ed2a3f5af90d6c262d461"
   },
   {
    "name": ".env.test",
    "dir": false,
    "message": "test(repo): less noisy test output (#11505)",
    "date": "2026-06-15T16:19:20Z",
    "sha": "28a9b1711dc0625b8ab5d643dc871810ee13642f"
   },
   {
    "name": ".eslintignore",
    "dir": false,
    "message": "feat: canvas search (#8438)",
    "date": "2024-09-09T15:12:07Z",
    "sha": "6959a363f0ba8d0e8b05442f4c8f3cc4a2e00ca6"
   },
   {
    "name": ".eslintrc.json",
    "dir": false,
    "message": "feat(packages/excalidraw): state tracking, api hook, and others (#10870)",
    "date": "2026-03-08T22:15:18Z",
    "sha": "21dd1cfacc6beb5d259fdda5c50582a1d9b29894"
   },
   {
    "name": ".gitattributes",
    "dir": false,
    "message": "Add gitattributes (#2164)",
    "date": "2020-09-15T19:59:00Z",
    "sha": "c8149179270e964e121f2f091fa9c153d855fb2c"
   },
   {
    "name": ".gitignore",
    "dir": false,
    "message": "chore: init CLAUDE.md (#9563)",
    "date": "2025-05-25T19:23:40Z",
    "sha": "cc571c46810452f1ffdff8db40c0a26bcaf4dcde"
   },
   {
    "name": ".lintstagedrc.js",
    "dir": false,
    "message": "Keep errors, elements and comments consistent (#2340)",
    "date": "2020-11-05T17:06:18Z",
    "sha": "5d295415db00b68a5c86aac7d93bb4bf2d3b8f55"
   },
   {
    "name": ".npmrc",
    "dir": false,
    "message": "feat: color picker redesign (#6216)",
    "date": "2023-05-18T14:06:27Z",
    "sha": "5b7596582f44f951147886152966672ba876660c"
   },
   {
    "name": ".prettierignore",
    "dir": false,
    "message": "Change target branch of coverage and pretty print (#1850)",
    "date": "2020-07-01T09:05:21Z",
    "sha": "89cf826555e60b237589b54ef8f4799a079f20df"
   },
   {
    "name": ".watchmanconfig",
    "dir": false,
    "message": "Don't reset cache while zooming using a gesture (#1103)",
    "date": "2020-03-28T23:59:36Z",
    "sha": "24fa657093755734432684aed98892785ae0e4d8"
   },
   {
    "name": "CLAUDE.md",
    "dir": false,
    "message": "chore: init CLAUDE.md (#9563)",
    "date": "2025-05-25T19:23:40Z",
    "sha": "cc571c46810452f1ffdff8db40c0a26bcaf4dcde"
   },
   {
    "name": "CONTRIBUTING.md",
    "dir": false,
    "message": "docs: migrating dev docs to docusaurus :) (#6073)",
    "date": "2023-02-01T14:27:54Z",
    "sha": "f23cdc47ee6518db96439c9ef70525e59deab332"
   },
   {
    "name": "Dockerfile",
    "dir": false,
    "message": "ci(docker): fix docker dep bundling and pin remaining actions (#11398)",
    "date": "2026-05-25T12:39:21Z",
    "sha": "c08be69618dcac9386817bced03d2d79883e50b6"
   },
   {
    "name": "LICENSE",
    "dir": false,
    "message": "Add MIT License (#176)",
    "date": "2020-01-05T21:09:29Z",
    "sha": "6f33d72e3564fbaadb3c0ebc773852d325dccc13"
   },
   {
    "name": "README.md",
    "dir": false,
    "message": "Fix typo in Discord badge URL parameter (#11096)",
    "date": "2026-04-02T08:37:02Z",
    "sha": "e18c1dd213000dde0ae94ef7eb00aab537b39708"
   },
   {
    "name": "crowdin.yml",
    "dir": false,
    "message": "build: decouple package deps and introduce yarn workspaces (#7415)",
    "date": "2023-12-12T06:02:51Z",
    "sha": "d6cd8b78f11742e9107dd4cd9cee564120ae599b"
   },
   {
    "name": "docker-compose.yml",
    "dir": false,
    "message": "build: Docker compose version removed (#10074)",
    "date": "2025-10-05T12:48:54Z",
    "sha": "98e0cd9078feab548c0af13f462195c4dbf10135"
   },
   {
    "name": "package.json",
    "dir": false,
    "message": "feat(editor): LaserPointer based freedraw (#11507)",
    "date": "2026-06-24T07:16:22Z",
    "sha": "cd514d72d6350082c7f173f7147607c7dc4cb523"
   },
   {
    "name": "setupTests.ts",
    "dir": false,
    "message": "test(repo): less noisy test output (#11505)",
    "date": "2026-06-15T16:19:20Z",
    "sha": "28a9b1711dc0625b8ab5d643dc871810ee13642f"
   },
   {
    "name": "tsconfig.json",
    "dir": false,
    "message": "fix(editor): Modern TS require imports from rootDir (#11552)",
    "date": "2026-06-24T10:52:56Z",
    "sha": "070df27e4d18cdc9265c9a9692089fe90b6019da"
   },
   {
    "name": "vercel.json",
    "dir": false,
    "message": "feat(editor): LaserPointer based freedraw (#11507)",
    "date": "2026-06-24T07:16:22Z",
    "sha": "cd514d72d6350082c7f173f7147607c7dc4cb523"
   },
   {
    "name": "vitest.config.mts",
    "dir": false,
    "message": "feat(editor): LaserPointer based freedraw (#11507)",
    "date": "2026-06-24T07:16:22Z",
    "sha": "cd514d72d6350082c7f173f7147607c7dc4cb523"
   },
   {
    "name": "yarn.lock",
    "dir": false,
    "message": "feat(editor): LaserPointer based freedraw (#11507)",
    "date": "2026-06-24T07:16:22Z",
    "sha": "cd514d72d6350082c7f173f7147607c7dc4cb523"
   }
  ]
 },
 "stats": {
  "issues": 12,
  "prsMerged": 12,
  "additions": 3976,
  "deletions": 516,
  "filesChanged": 83,
  "checksPassed": 28,
  "checksPassedBasis": "hero PRs only: latest check run per name with conclusion success, plus commit statuses with state success"
 }
};
export const REPO = DATA.repo;
export const DAY = DATA.day;
export const ISSUES = DATA.issues;
export const HEROES = DATA.heroes;
export const RULES = DATA.rules;
export const CODE = DATA.code;
export const STATS = DATA.stats || {};
