// clio-data.js: everything static the Clio Manage matter desk (clio.js) shows, plus its UI icon set.
// The content is REAL and sourced: federal dockets on CourtListener (RECAP), real ECF entries, and the presiding
// judges' posted standing orders. Each record carries `src`, the URL it was taken from; every docket and rule URL is
// also listed in ../../img/CREDITS.txt. Generated by gen-data.py (kept with the reference material outside the repo)
// from the research pass and the string-by-string verification pass.
// Docket text, order quotes and rule text are verbatim. The deadline line and its cite, the action labels, the draft
// lines, the task names and the queue dispositions are the ad's own copy, each a plain restatement of the entry it
// sits on (no fact in them that the entry does not state).
// The tIn / tAns / tRes timings on NOTICES are the call-center queue's, copied exactly: they are motion, not
// content, and must not change. The icons are UI chrome drawn by hand in Clio's outline style (1.8px round
// stroke), not marks of any product; the only third-party artwork is the Clio logo in ../../img.
// Copy rules: no em or en dashes in on-screen text; U+00A0 between a number and its unit.

const NB = ' ';

const sol = (dd) => `<svg class="cl-i cl-s" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="${dd}"/></svg>`;
const ico = (inner, w = 1.8) => `<svg class="cl-i" viewBox="0 0 24 24" aria-hidden="true" style="--sw:${w}">${inner}</svg>`;

// ---------- icons (left nav, top bar, cards) ----------
export const I = {
  chevron: ico('<path d="m6 9 6 6 6-6"/>', 2),
  search: ico('<circle cx="11" cy="11" r="6.6"/><path d="m20.5 20.5-4.4-4.4"/>', 2),
  plus: ico('<path d="M12 5v14"/><path d="M5 12h14"/>', 2.4),
  play: sol('M7 4.5v15l12-7.5Z'),
  help: ico('<circle cx="12" cy="12" r="8.6"/><path d="M9.6 9.4a2.5 2.5 0 0 1 4.8.9c0 1.7-2.4 2.2-2.4 3.6"/><path d="M12 17v.1"/>'),
  bell: sol('M12 2.5a1.4 1.4 0 0 1 1.4 1.4v.8A6.3 6.3 0 0 1 18.3 11v3.6l2 2.6v1.3H3.7v-1.3l2-2.6V11a6.3 6.3 0 0 1 4.9-6.3v-.8A1.4 1.4 0 0 1 12 2.5ZM9.6 19.8h4.8a2.4 2.4 0 0 1-4.8 0Z'),
  avatar: ico('<circle cx="12" cy="8.6" r="3.9"/><path d="M4.6 20.4a7.6 7.6 0 0 1 14.8 0"/>'),
  caret: '<svg class="cl-caret" viewBox="0 0 10 6" aria-hidden="true"><path d="M0 0h10L5 6z" fill="currentColor"/></svg>',
  clock: sol('M12 2.5a9.5 9.5 0 1 1 0 19 9.5 9.5 0 0 1 0-19Zm-1 4v6.4l4.4 2.7 1-1.6-3.4-2.1V6.5Z'),
  // left nav and top bar: solid glyphs, as Clio draws them (Font Awesome solid style); hand-drawn, not FA's paths
  dashboard: sol('M12 3 2.5 11.2h2.6v9.3h5.2v-6h3.4v6h5.2v-9.3h2.6Z'),
  calendar: sol('M7 2.5h2.2V5h5.6V2.5H17V5h2.4A1.6 1.6 0 0 1 21 6.6V9H3V6.6A1.6 1.6 0 0 1 4.6 5H7ZM3 10.6h18v8.8a1.6 1.6 0 0 1-1.6 1.6H4.6A1.6 1.6 0 0 1 3 19.4Z'),
  tasks: sol('M3 5h3.2v3.2H3ZM8.4 5.6H21v2H8.4ZM3 10.4h3.2v3.2H3ZM8.4 11H21v2H8.4ZM3 15.8h3.2V19H3ZM8.4 16.4H21v2H8.4Z'),
  matters: sol('M9 3.4h6a1.6 1.6 0 0 1 1.6 1.6v1.5h3.8A1.6 1.6 0 0 1 22 8.1v4.2H2V8.1a1.6 1.6 0 0 1 1.6-1.6h3.8V5A1.6 1.6 0 0 1 9 3.4Zm.3 1.9v1.2h5.4V5.3ZM2 13.8h8.2v1.6h3.6v-1.6H22v5.1a1.6 1.6 0 0 1-1.6 1.6H3.6A1.6 1.6 0 0 1 2 18.9Z'),
  contacts: sol('M5 2.5h12.6a1.6 1.6 0 0 1 1.6 1.6v15.8a1.6 1.6 0 0 1-1.6 1.6H5a1.6 1.6 0 0 1-1.6-1.6V4.1A1.6 1.6 0 0 1 5 2.5Zm6.3 4.3a2.7 2.7 0 1 0 0 5.4 2.7 2.7 0 0 0 0-5.4Zm-4.6 10.8h9.2a4.6 4.6 0 0 0-9.2 0ZM20.4 5h1.6v3.2h-1.6ZM20.4 10.2h1.6v3.2h-1.6Z'),
  activities: sol('M12 2.5a9.5 9.5 0 1 1 0 19 9.5 9.5 0 0 1 0-19Zm-1 4v6.4l4.4 2.7 1-1.6-3.4-2.1V6.5Z'),
  billing: sol('M5 2.5h14v19l-2.3-1.6-2.4 1.6-2.3-1.6-2.3 1.6-2.4-1.6L5 21.5ZM8 7v1.8h8V7Zm0 3.6v1.8h8v-1.8Zm0 3.6V16h5v-1.8Z'),
  payments: sol('M4 4.5h16a1.6 1.6 0 0 1 1.6 1.6v1.6H2.4V6.1A1.6 1.6 0 0 1 4 4.5ZM2.4 10h19.2v7.9a1.6 1.6 0 0 1-1.6 1.6H4a1.6 1.6 0 0 1-1.6-1.6Zm2.8 4.4V16h5v-1.6Z'),
  accounts: sol('M12 2 2.5 7.2v2h19v-2ZM4 10.6h3v7H4Zm6.5 0h3v7h-3Zm6.5 0h3v7h-3ZM2.5 19h19v2.5h-19Z'),
  documents: sol('M2.5 5.5A1.6 1.6 0 0 1 4.1 4h5.2l2 2h6.4a1.6 1.6 0 0 1 1.6 1.6V9H7.1a2 2 0 0 0-1.9 1.4L2.5 18ZM6.6 10.6h15.9l-3 9H3.6Z'),
  communications: sol('M3.1 3.8h10.8a1.6 1.6 0 0 1 1.6 1.6v6a1.6 1.6 0 0 1-1.6 1.6H8.2l-3.6 3v-3H3.1a1.6 1.6 0 0 1-1.6-1.6v-6a1.6 1.6 0 0 1 1.6-1.6ZM17 8h3.9a1.6 1.6 0 0 1 1.6 1.6v6a1.6 1.6 0 0 1-1.6 1.6h-.9v3l-3.6-3h-5.3a1.6 1.6 0 0 1-1.6-1.6v-.9h4.5a3 3 0 0 0 3-3Z'),
  reports: sol('M4 12h3.6v8.5H4Zm6.2-8h3.6v16.5h-3.6Zm6.2 4.5H20v12h-3.6Z'),
  apps: sol('M12 2.5 16.6 10H7.4ZM6.8 12.4a4 4 0 1 1 0 8 4 4 0 0 1 0-8ZM13.4 12.6h7.6v7.6h-7.6Z'),
  settings: '<svg class="cl-i" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="5.4" fill="none" stroke="currentColor" stroke-width="3.4"/><path d="M12 1.9v3.4M12 18.7v3.4M1.9 12h3.4M18.7 12h3.4M4.9 4.9l2.4 2.4M16.7 16.7l2.4 2.4M4.9 19.1l2.4-2.4M16.7 7.3l2.4-2.4" fill="none" stroke="currentColor" stroke-width="3.6"/></svg>',
  collapse: ico('<path d="m14.5 7-5 5 5 5"/>', 2.4),
  // cards
  check: ico('<path d="M4.8 12.6 9 16.8 19.2 6.6"/>', 2.6),
  gavel: ico('<path d="m13.6 3.8 6.6 6.6"/><path d="m10.6 6.8 6.6 6.6"/><path d="m12.1 5.3 4.6 4.6"/><path d="M13.9 11.1 5 20"/><path d="M3.6 20.5h8"/>'),
  doc: ico('<path d="M6 3.5h8.4L19 8v12.5H6z"/><path d="M14.2 3.5V8H19"/><path d="M9 12.4h6"/><path d="M9 16h4"/>'),
  more: ico('<circle cx="5.5" cy="12" r="1.1" fill="currentColor"/><circle cx="12" cy="12" r="1.1" fill="currentColor"/><circle cx="18.5" cy="12" r="1.1" fill="currentColor"/>'),
  filter: ico('<path d="M4 5.5h16l-6.2 7.3v5.4l-3.6 1.8v-7.2Z"/>'),
};

// ---------- the desk's own date line ----------
// the day every notice below was entered on its docket (2026-09-28)
export const DESK = { date: "Sep 28, 2026", weekday: "Monday" };

// ---------- the three matters the main pane works through, in order ----------
// Each one drives: the matter header, the Docket entry card (ECF no., entered, type, verbatim text), the Deadline
// line and its cite, the pressed action pill, the two related entries, the ORDER (verbatim) / YOUR DRAFT lines, the
// calendar task that flips from OPEN to CALENDARED, and the disposition its notice row lands on. districtJudge /
// magistrateJudge / natureOfSuit may be null: the header then drops that field (a magistrate judge presiding alone
// is shown as "Presiding"). `cite` is how the matter's lawyers cite the entry (D. Del. practice is "D.I.").
export const MATTERS = [
  {
    "captionShort": "AFGE v. OMB",
    "captionFull": "American Federation of Government Employees, AFL-CIO, et al. v. United States Office of Management and Budget, et al.",
    "caseNo": "3:25-cv-08302-SI",
    "court": "U.S. District Court, N.D. Cal.",
    "courtAbbrev": "NDCA",
    "districtJudge": "Hon. Susan Illston",
    "magistrateJudge": null,
    "natureOfSuit": "899 Other Statutes: Administrative Procedures Act/Review or Appeal of Agency Decision",
    "caseFiled": "Sep 30, 2025",
    "entry": {
      "ecf": 199,
      "entered": "Sep 28, 2026",
      "entryType": "Order",
      "text": "Order by Judge Susan Illston granting 198 Administrative Motion to Hold in Abeyance Pursuant to Settlement Agreement. Joint Status Report due by 12/4/2026. Status Conference set for 12/11/2026 at 03:00 PM in San Francisco, - Videoconference Only before Judge Susan Illston.(ec, COURT STAFF) (Filed on 9/28/2026) (Entered: 09/28/2026)"
    },
    "deadline": {
      "date": "Dec 4, 2026",
      "what": "Joint status report due by noon PST",
      "basis": "Order, ECF No. 199"
    },
    "cite": "ECF No. 199",
    "actions": [
      "Calendar deadline",
      "Draft status report",
      "Email opposing counsel"
    ],
    "press": 0,
    "quote": "A joint status report is due by 12/4/2026 by noon PST.",
    "draft": "Per ECF No. 199, the joint status report is due December 4 by noon PST. Draft attached.",
    "related": [
      [
        "ECF No. 198",
        "Administrative Motion to Hold in Abeyance Pursuant to Settlement Agreement",
        "Sep 25, 2026"
      ],
      [
        "ECF No. 196",
        "Order by Judge Susan Illston granting 195 Motion to Stay. Motion to Dismiss Hearing CONTINUED TO 10/16/2026 at 10:00 AM in San Francisco, Courtroom 01, 17th Floor before Judge Susan Illston.",
        "Sep 8, 2026"
      ]
    ],
    "task": "File joint status report",
    "disposition": "Due Dec 4",
    "src": "https://www.courtlistener.com/docket/71502325/199/american-federation-of-government-employees-afl-cio-v-united-states/"
  },
  {
    "captionShort": "Oracle v. Procore",
    "captionFull": "Oracle America, Inc., et al. v. Procore Technologies, Inc., et al.",
    "caseNo": "4:24-cv-07457-JST",
    "court": "U.S. District Court, N.D. Cal.",
    "courtAbbrev": "NDCA",
    "districtJudge": "Hon. Jon S. Tigar",
    "magistrateJudge": "Hon. Laurel Beeler",
    "natureOfSuit": "880 Defend Trade Secrets Act (of 2016)",
    "caseFiled": "Oct 25, 2024",
    "entry": {
      "ecf": 433,
      "entered": "Sep 28, 2026",
      "entryType": "Order",
      "text": "ORDER RE: JOINT STIPULATION AND PROPOSED ORDER REGARDING PUBLIC VERSION OF SUMMARY JUDGMENT HEARING TRANSCRIPT by Judge Jon S. Tigar re 429 STIPULATION WITH PROPOSED ORDER Regarding Public Version of August 20, 2026 Summary Judgement Hearing Transcript filed by Oracle America, Inc., Oracle International Corporation, Textura Corporation. Transcript with Proposed Redactions due by 10/5/2026. (dms, COURT STAFF) (Filed on 9/28/2026) (Entered: 09/28/2026)"
    },
    "deadline": {
      "date": "Oct 5, 2026",
      "what": "Transcript with proposed redactions due",
      "basis": "Order, ECF No. 433"
    },
    "cite": "ECF No. 433",
    "actions": [
      "Calendar deadline",
      "Mark redactions",
      "Email opposing counsel"
    ],
    "press": 0,
    "quote": "Accordingly, the parties shall file the transcript containing their proposed redactions within seven days of the date of this order.",
    "draft": "Per ECF No. 433, the transcript with the parties' proposed redactions is due October 5.",
    "related": [
      [
        "ECF No. 429",
        "STIPULATION WITH PROPOSED ORDER Regarding Public Version of August 20, 2026 Summary Judgement Hearing Transcript",
        "Sep 23, 2026"
      ],
      [
        "ECF No. 426",
        "ORDER ON STIPULATION by Judge Jon S. Tigar granting 425 Stipulation.",
        "Sep 9, 2026"
      ]
    ],
    "task": "File transcript with proposed redactions",
    "disposition": "Due Oct 5",
    "src": "https://www.courtlistener.com/docket/69314070/433/oracle-america-inc-v-procore-technologies-inc/"
  },
  {
    "captionShort": "Nielsen v. TVision",
    "captionFull": "Nielsen Company (US), LLC v. TVision Insights, Inc.",
    "caseNo": "1:25-cv-00575-CJB",
    "court": "U.S. District Court, D. Del.",
    "courtAbbrev": "DDE",
    "districtJudge": null,
    "magistrateJudge": "Hon. Christopher J. Burke",
    "natureOfSuit": "830 Patent",
    "caseFiled": "May 9, 2025",
    "entry": {
      "ecf": 163,
      "entered": "Sep 28, 2026",
      "entryType": "So Ordered",
      "text": "SO ORDERED, D.I. 162 Joint PROPOSED Amended Schedule re 24 Scheduling Order filed by Nielsen Company (US), LLC. (Fact Discovery completed by 2/5/2027, Opening Expert Reports due by 2/26/2027, Rebuttal Expert Reports due by 4/16/2027, Reply Expert Reports due by 5/14/2027, Expert Discovery due by 6/11/2027, Dispositive Motions due by 7/23/2027, An Oral Argument is set for 10/22/2027 at 11:00 AM in Courtroom 2A before Judge Christopher J. Burke, Proposed Pretrial Order due by 2/25/2028, A Pretrial Conference is set for 3/10/2028 at 11:00 AM in Courtroom 2A before Judge Christopher J. Burke, A 5-day Jury Trial is set for 3/20/2028 at 09:30/09:00 AM in Courtroom 2A before Judge Christopher J. Burke. See Stipulation for further details and deadlines.) Signed by Judge Christopher J. Burke on 09/28/2026. (sam) (Entered: 09/28/2026)"
    },
    "deadline": {
      "date": "Feb 5, 2027",
      "what": "Fact discovery closes",
      "basis": "So-ordered schedule, D.I. 163"
    },
    "cite": "D.I. 163",
    "actions": [
      "Calendar all 10 dates",
      "Draft team update",
      "Update discovery plan"
    ],
    "press": 0,
    "quote": "SO ORDERED, D.I. 162 Joint PROPOSED Amended Schedule re 24 Scheduling Order filed by Nielsen Company (US), LLC.",
    "draft": "Per D.I. 163, fact discovery now closes February 5, 2027. All ten dates are calendared.",
    "related": [
      [
        "ECF No. 162",
        "Joint PROPOSED ORDER [Proposed] Amended Schedule re 24 Scheduling Order",
        "Sep 25, 2026"
      ],
      [
        "ECF No. 161",
        "Oral Order denying Nielsen's motion to stay TVision's antitrust counterclaims",
        "Sep 23, 2026"
      ]
    ],
    "task": "Complete fact discovery",
    "disposition": "Due Feb 5",
    "src": "https://www.courtlistener.com/docket/70238228/163/nielsen-company-us-llc-v-tvision-insights-inc/"
  },
];

// ---------- the ECF notices queue: 12 notices, newest first ----------
// tIn / tAns / tRes are seconds on the desk clock, copied exactly from the call-center QUEUE (clio.js ANSWER / WINS;
// rows 0-2 carry `matter` and are read exactly when their matter takes the main pane and calendared when its task
// flips). Every row arrives New, is Reading, and lands Calendared with its disposition; a notice that sets no
// deadline (`noDeadline`) lands Reviewed instead and is not counted as a calendared deadline.
export const NOTICES = [
  {"courtAbbrev": "NDCA", "captionShort": "AFGE v. OMB", "entryType": "Order", "ecf": 199, "tIn": 8.70, "tAns": 8.90, "tRes": 11.06, "disp": "Due Dec 4", "matter": 0, "src": "https://www.courtlistener.com/docket/71502325/199/american-federation-of-government-employees-afl-cio-v-united-states/"},
  {"courtAbbrev": "NDCA", "captionShort": "Oracle v. Procore", "entryType": "Order", "ecf": 433, "tIn": 9.30, "tAns": 11.60, "tRes": 13.52, "disp": "Due Oct 5", "matter": 1, "src": "https://www.courtlistener.com/docket/69314070/433/oracle-america-inc-v-procore-technologies-inc/"},
  {"courtAbbrev": "DDE", "captionShort": "Nielsen v. TVision", "entryType": "So Ordered", "ecf": 163, "tIn": 9.90, "tAns": 14.00, "tRes": 15.68, "disp": "Due Feb 5", "matter": 2, "src": "https://www.courtlistener.com/docket/70238228/163/nielsen-company-us-llc-v-tvision-insights-inc/"},
  {"courtAbbrev": "NDAL", "captionShort": "Southeastern Conf. v. LSU", "entryType": "Text Order", "ecf": 28, "tIn": 10.40, "tAns": 10.95, "tRes": 12.60, "disp": "Due Oct 13", "src": "https://www.courtlistener.com/docket/74745193/28/the-southeastern-conference-v-louisiana-state-university/"},
  {"courtAbbrev": "CDCA", "captionShort": "Disney v. Midjourney", "entryType": "Transcript", "ecf": 210, "tIn": 10.90, "tAns": 11.35, "tRes": 13.10, "disp": "Due Oct 19", "src": "https://www.courtlistener.com/docket/70513159/210/disney-enterprises-inc-v-midjourney-inc/"},
  {"courtAbbrev": "WDWA", "captionShort": "FTC v. Amazon", "entryType": "Motion to Seal", "ecf": 91, "tIn": 11.40, "tAns": 11.80, "tRes": 13.45, "disp": "Noting date Oct 19", "src": "https://www.courtlistener.com/docket/74725379/91/federal-trade-commission-v-amazoncom-inc/"},
  {"courtAbbrev": "SDIA", "captionShort": "Penguin Random House v. Robbins", "entryType": "Motion to Dismiss", "ecf": 154, "tIn": 11.90, "tAns": 12.30, "tRes": 14.20, "disp": "Due Oct 13", "src": "https://www.courtlistener.com/docket/68048039/154/penguin-random-house-llc-v-robbins/"},
  {"courtAbbrev": "DDE", "captionShort": "Nokia v. Acer", "entryType": "Oral Order", "ecf": 95, "tIn": 12.40, "tAns": 12.85, "tRes": 14.55, "disp": "Due Sep 30", "src": "https://www.courtlistener.com/docket/71266654/95/nokia-of-america-corporation-v-acer-inc/"},
  {"courtAbbrev": "DDE", "captionShort": "Caltech v. Zoom", "entryType": "Opening Brief", "ecf": 29, "tIn": 12.90, "tAns": 13.35, "tRes": 15.20, "disp": "Due Oct 13", "src": "https://www.courtlistener.com/docket/72349967/29/the-california-institute-of-technology-v-zoom-communications-inc/"},
  {"courtAbbrev": "SDNY", "captionShort": "Seattle Times v. OpenAI", "entryType": "Stipulation and Order", "ecf": 19, "tIn": 13.40, "tAns": 13.85, "tRes": 15.60, "disp": "Case stayed", "noDeadline": true, "src": "https://www.courtlistener.com/docket/74754553/19/the-seattle-times-company-v-openai-inc/"},
  {"courtAbbrev": "CDIL", "captionShort": "PCMA v. Gillespie", "entryType": "Motion for Reconsideration", "ecf": 36, "tIn": 13.90, "tAns": 14.35, "tRes": 15.92, "disp": "Due Oct 13", "src": "https://www.courtlistener.com/docket/73493138/36/pharmaceutical-care-management-association-v-gillespie/"},
  {"courtAbbrev": "CDCA", "captionShort": "Wilus v. TP-Link", "entryType": "Waiver of Service Executed", "ecf": 35, "tIn": 14.40, "tAns": 14.75, "tRes": 16.02, "disp": "Due Nov 16", "src": "https://www.courtlistener.com/docket/74694036/35/wilus-institute-of-standards-and-technology-inc-v-tp-link-corporation-pte/"},
];

// ---------- the judges' individual rules superbot reads on the LEARN beat ----------
// [judge, document, section, requirement (verbatim), src]: the document as its title reads (the Tigar and Burke
// titles shortened to their leading words), the section as numbered in the document
export const RULES = [
  ["Hon. Susan Illston", "Judge Illston's Standing Order", "1. Scheduling Days", "Initial and further CMCs will take place over Zoom.", "https://cand.uscourts.gov/sites/default/files/standing-orders/JudgeIllston_Standing-Order-9-23-2025.pdf"],
  ["Hon. Susan Illston", "Judge Illston's Standing Order", "3. Discovery Disputes", "If, after a good faith effort, the parties have not resolved their dispute, they shall prepare a concise joint statement of 5 pages or less, stating the nature and status of their dispute.", "https://cand.uscourts.gov/sites/default/files/standing-orders/JudgeIllston_Standing-Order-9-23-2025.pdf"],
  ["Hon. Susan Illston", "Judge Illston's Standing Order", "4. Paper Courtesy Copies", "Notwithstanding Civil Local Rule 5-1(d)(7), one set of paper courtesy copies (“chambers copies”) is required for any filing exceeding ten pages in length.", "https://cand.uscourts.gov/sites/default/files/standing-orders/JudgeIllston_Standing-Order-9-23-2025.pdf"],
  ["Hon. Susan Illston", "Judge Illston's Standing Order", "4. Paper Courtesy Copies", "Courtesy copies shall be delivered to the Clerk’s Office no later than noon 2 days after filing of the document.", "https://cand.uscourts.gov/sites/default/files/standing-orders/JudgeIllston_Standing-Order-9-23-2025.pdf"],
  ["Hon. Jon S. Tigar", "Standing Order for All Civil Cases", "C. Court Schedule", "All filing deadlines are at 5:00 p.m. unless otherwise ordered.", "https://cand.uscourts.gov/sites/default/files/standing-orders/JST-CivilStandingOrder-06.03.26.pdf"],
  ["Hon. Jon S. Tigar", "Standing Order for All Civil Cases", "F.6 Discovery Disputes", "If the parties are unable to reach a resolution through this process, they must file a joint letter brief of five pages or less that describes each disputed issue.", "https://cand.uscourts.gov/sites/default/files/standing-orders/JST-CivilStandingOrder-06.03.26.pdf"],
  ["Hon. Jon S. Tigar", "Standing Order for All Civil Cases", "K. Requests to Extend Deadlines or Continue Hearing Dates", "Requests to extend deadlines or continue hearing dates should be filed at least three business days prior to the deadline or hearing sought to be extended or continued.", "https://cand.uscourts.gov/sites/default/files/standing-orders/JST-CivilStandingOrder-06.03.26.pdf"],
  ["Hon. Jon S. Tigar", "Standing Order for All Civil Cases", "L.1 Page Limits", "For all other types of motions, the opening and opposition briefs must be no more than 15 pages, and the reply brief must be no more than 10 pages.", "https://cand.uscourts.gov/sites/default/files/standing-orders/JST-CivilStandingOrder-06.03.26.pdf"],
  ["Hon. Christopher J. Burke", "Standing Order Regarding Courtesy Copies", "¶ 1", "Unless a specific Order to the contrary is entered in a case, all parties shall provide to the Court two (2) courtesy copies of all briefs (including letter briefs), as well as any documents filed in support of such briefs (i.e., appendices, exhibits, declarations, affidavits, tutorials, etc.).", "https://www.ded.uscourts.gov/sites/ded/files/CJBCC2022.pdf"],
  ["Hon. Christopher J. Burke", "Standing Order Regarding Courtesy Copies", "¶ 1", "Unless ordered differently by the Court, such copies must be provided to the Court by no later than noon the business day after the filing is made electronically.", "https://www.ded.uscourts.gov/sites/ded/files/CJBCC2022.pdf"],
  ["Hon. Christopher J. Burke", "Guidelines for Discovery Disputes", "¶ 2", "The moving party should attach a proposed order to its letter brief as an exhibit.", "https://www.ded.uscourts.gov/sites/ded/files/Guidelines%20for%20Discovery%20Disputes-CJB.pdf"],
  ["Hon. Christopher J. Burke", "Scheduling Order, Patent Cases", "¶ 8(a) Motions to Amend", "Any motion to amend a pleading shall NOT be accompanied by an opening brief but shall, instead, be accompanied by a letter, not to exceed three (3) single-spaced pages, describing the basis for the requested relief, and shall attach the proposed amended pleading as well as a “blackline” comparison to the prior pleading.", "https://www.ded.uscourts.gov/sites/ded/files/chambers/Rule%2016%20Scheduling%20Order%20-%20Patent%20-%20Revised%203.2025.pdf"],
];

// what the HUD lifts out of those rows on the LEARN beat (provision ids as in the research JSON: TG-1, TG-3, IL-3, CJB-1 + CJB-2)
export const REQUIREMENTS = ["Filings due by 5:00 p.m.", "Extensions: file 3 business days ahead", "Chambers copy if over 10 pages", "2 courtesy copies by noon next business day"];

// the four HUD checklist rows
export const STEPS = ['Connected to Clio', 'Writing style matched', 'Read your judges’ rules', 'Working your docket'];

// the Dashboard tab the matter page carries before a notice is opened: calendar entries and tasks already on
// these matters before today's notices (the Oct 16 hearing is the one ECF No. 199 vacates)
export const IDLE = {
  title: 'No matter open',
  sub: 'Open an ECF notice to load its matter',
  agenda: [
    ["Oct 2", "Oracle v. Procore: stipulated redacted proposed order due (ECF No. 432)"],
    ["Oct 16", "AFGE v. OMB: motion to dismiss hearing (ECF No. 196)"],
  ],
  tasks: [
    ["Nielsen v. TVision: propose date to supplement contentions (D.I. 159)", "Due Sep 25"],
    ["Oracle v. Procore: file stipulated redacted transcript (ECF No. 426)", "Due Sep 23"],
  ],
};

// the older tasks already on the matters, under this session's new ones: [name, matter and cite, due]
export const OLD_TASKS = [
  ["Replies due: motion to dismiss revised second amended complaint", "AFGE v. OMB, ECF No. 194", "Sep 8, 2026"],
  ["File stipulated redacted transcript", "Oracle v. Procore, ECF No. 426", "Sep 23, 2026"],
];

export const NBSP = NB;
