// wp-data.js: everything static the WordPress desk (wp.js) shows: the day's story budget, the three stories superbot
// writes in the block editor, and the AP Stylebook entries it reads on the LEARN beat.
//
// Researched data, generated by /tmp/jr-ad.f8795b48/tools/gen-wpdata.f8795b48.mjs from
// /tmp/jr-ad.f8795b48/research/research.json (every source saved in research/src). Do not hand-edit: change the
// research or the generator, regenerate, then run research/verify-final.f8795b48.mjs, which traces every number,
// date, time and name below to a verbatim span in a saved source and every rule quote to AP's own words.
//
// Schema (fixed):
//   DAY      { iso, label }
//   STORIES  12, release-time order: { slug, org, orgShort, beat, release, at, url, head, main }
//            release = the release's own title, at = release time ET ('8:30 a.m.'), head = the filed headline,
//            main = 0 | 1 | 2 (the MAIN entry written in the editor) or null
//   MAIN     3: { story, dateline, category, tags, says: [s1, s2], options: [h1, h2, h3], press, lede, graf2,
//            quote: { text, who } | null, fixes: [{ from, to, rule }], facts: [{ text, span }] }
//            story indexes STORIES; says is the release verbatim; options[press] is the headline filed (= head);
//            every fix's `to` and every fact's `text` occurs verbatim in the story; fix.rule is a STYLE id;
//            fact.span is the release's own words the number is checked against
//   STYLE    12: { id, entry, quote, label, url }  entry = the Stylebook entry name, quote = its words verbatim,
//            label = the HUD's short form
// Every count the desk shows (stories, facts, fixes, rules) is derived from these arrays.
// Copy rules: no em or en dashes in anything on screen.

export const PLACEHOLDER = false;

// ---------- DATA ----------
export const DAY = { iso: '2026-09-24', label: 'Thu, Sept. 24, 2026' };

export const STORIES = [
  { slug: 'current-account-deficit-widens', org: 'U.S. Bureau of Economic Analysis', orgShort: 'BEA', beat: 'economy', release: 'U.S. International Transactions and Investment Position, 2nd Quarter 2026', at: '8:30 a.m.', url: 'https://www.bea.gov/news/2026/us-international-transactions-and-investment-position-2nd-quarter-2026', head: 'US current-account deficit widens to $246B in second quarter', main: 0 },
  { slug: 'jobless-claims-197000', org: 'U.S. Department of Labor, Employment and Training Administration', orgShort: 'DOL', beat: 'labor', release: 'Unemployment Insurance Weekly Claims', at: '8:30 a.m.', url: 'https://www.dol.gov/newsroom/releases/eta/eta20260924', head: 'Initial jobless claims fall by 1,000 to 197,000', main: null },
  { slug: 'new-home-sales-rise', org: 'U.S. Census Bureau and U.S. Department of Housing and Urban Development', orgShort: 'Census', beat: 'housing', release: 'Monthly New Residential Sales, August 2026', at: '10 a.m.', url: 'https://www.census.gov/construction/nrs/current/index.html', head: 'New home sales rise 6.4% in August to 684,000 annual rate', main: null },
  { slug: 'median-employee-tenure-rises', org: 'U.S. Bureau of Labor Statistics', orgShort: 'BLS', beat: 'employment', release: 'Employee Tenure in 2026', at: '10 a.m.', url: 'https://www.bls.gov/news.release/tenure.nr0.htm', head: 'Median employee tenure rises to 4.1 years, BLS says', main: null },
  { slug: 'flexible-schedules-57-percent', org: 'U.S. Bureau of Labor Statistics', orgShort: 'BLS', beat: 'workplace', release: 'Job Flexibilities and Work Schedules 2024-2025: Data from the American Time Use Survey', at: '10 a.m.', url: 'https://www.bls.gov/news.release/flex2.nr0.htm', head: '57% of workers had a flexible schedule in 2024-25, BLS says', main: null },
  { slug: 'natural-gas-storage-up', org: 'U.S. Energy Information Administration', orgShort: 'EIA', beat: 'energy', release: 'Weekly Natural Gas Storage Report', at: '10:30 a.m.', url: 'https://ir.eia.gov/ngs/ngs.html', head: 'Natural gas in storage rises 53 billion cubic feet, EIA says', main: null },
  { slug: 'mortgage-rate-7-percent', org: 'Freddie Mac', orgShort: 'Freddie', beat: 'mortgages', release: 'Primary Mortgage Market Survey', at: 'noon', url: 'https://www.freddiemac.com/pmms', head: '30-year mortgage rate rises to 7.03%, Freddie Mac says', main: null },
  { slug: 'fed-stablecoin-proposals', org: 'Board of Governors of the Federal Reserve System', orgShort: 'Fed', beat: 'banking', release: 'Federal Reserve Board requests public comment on two proposals related to establishing a regulatory framework for Board-supervised payment stablecoin issuers under the GENIUS Act', at: '2:30 p.m.', url: 'https://www.federalreserve.gov/newsevents/pressreleases/bcreg20260924a.htm', head: 'Federal Reserve seeks comment on 2 stablecoin proposals', main: null },
  { slug: 'hog-inventory-down-2-percent', org: 'U.S. Department of Agriculture, National Agricultural Statistics Service', orgShort: 'USDA', beat: 'agriculture', release: 'United States hog inventory down 2% (Quarterly Hogs and Pigs, September 2026)', at: '3 p.m.', url: 'https://www.nass.usda.gov/Newsroom/2026/09-24-2026.php', head: 'US hog inventory down 2% from a year earlier, USDA says', main: 1 },
  { slug: 'costco-fourth-quarter-sales', org: 'Costco Wholesale Corporation', orgShort: 'Costco', beat: 'business', release: 'Costco Wholesale Corporation Reports Fourth Quarter and Fiscal Year 2026 Operating Results', at: '4:15 p.m.', url: 'https://investor.costco.com/news/news-details/2026/Costco-Wholesale-Corporation-Reports-Fourth-Quarter-and-Fiscal-Year-2026-Operating-Results/default.aspx', head: 'Costco fourth-quarter net sales rise 11.2% to $93.9B', main: 2 },
  { slug: 'nasa-crew-14-assignments', org: 'National Aeronautics and Space Administration', orgShort: 'NASA', beat: 'space', release: 'NASA Shares SpaceX Crew-14 Assignments for Space Station Mission (Release 26-077)', at: '5:15 p.m.', url: 'https://www.nasa.gov/news-release/nasa-shares-spacex-crew-14-assignments-for-space-station-mission/', head: 'NASA assigns 4 crew members to SpaceX Crew-14 mission', main: null },
  { slug: 'artemis-accords-75th-signatory', org: 'National Aeronautics and Space Administration', orgShort: 'NASA', beat: 'space', release: 'NASA Welcomes Côte d’Ivoire as Newest Artemis Accords Signatory', at: '5:27 p.m.', url: 'https://www.nasa.gov/organizations/oiir/nasa-welcomes-cote-divoire-as-newest-artemis-accords-signatory/', head: 'Côte d’Ivoire becomes 75th Artemis Accords signatory', main: null },
];

export const MAIN = [
  {
    story: 0,
    dateline: 'WASHINGTON',
    category: 'Economy',
    tags: ['international trade', 'current account', 'Bureau of Economic Analysis'],
    says: [
      'The second-quarter deficit was 3.0 percent of current-dollar gross domestic product, up from 2.7 percent in the first quarter.',
      'The revised first-quarter deficit was $212.6 billion.',
    ],
    options: [
      'US current-account deficit widens to $246B in second quarter',
      'US current-account deficit grows 15.7% to $246B',
      'Current-account deficit rises to 3% of GDP in second quarter',
    ],
    press: 0,
    lede: 'The U.S. current-account deficit widened by $33.4 billion, or 15.7%, to $246.0 billion in the second quarter, the Bureau of Economic Analysis said Thursday.',
    graf2: 'The deficit was 3.0% of current-dollar gross domestic product, up from 2.7% in the first quarter. The agency revised the first-quarter deficit to $212.6 billion and said the widening reflected a larger deficit on goods.',
    quote: null,
    fixes: [
      { from: '15.7 percent', to: '15.7%', rule: 'percent' },
      { from: 'U.S. current-account deficit', to: 'US current-account deficit', rule: 'us-headlines' },
      { from: '$246.0 billion', to: '$246B', rule: 'headline-money' },
    ],
    facts: [
      { text: 'US current-account deficit', span: 'The U.S. current-account deficit resulting from international economic transactions widened by $33.4 billion, or 15.7 percent, to $246.0 billion in the second quarter of 2026, according to statistics released today by the U.S. Bureau of Economic Analysis.' },
      { text: 'widens', span: 'The U.S. current-account deficit resulting from international economic transactions widened by $33.4 billion, or 15.7 percent, to $246.0 billion in the second quarter of 2026, according to statistics released today by the U.S. Bureau of Economic Analysis.' },
      { text: '$246B', span: 'The U.S. current-account deficit resulting from international economic transactions widened by $33.4 billion, or 15.7 percent, to $246.0 billion in the second quarter of 2026, according to statistics released today by the U.S. Bureau of Economic Analysis.' },
      { text: 'second quarter', span: 'The U.S. current-account deficit resulting from international economic transactions widened by $33.4 billion, or 15.7 percent, to $246.0 billion in the second quarter of 2026, according to statistics released today by the U.S. Bureau of Economic Analysis.' },
      { text: '$33.4 billion', span: 'The U.S. current-account deficit resulting from international economic transactions widened by $33.4 billion, or 15.7 percent, to $246.0 billion in the second quarter of 2026, according to statistics released today by the U.S. Bureau of Economic Analysis.' },
      { text: '15.7%', span: 'The U.S. current-account deficit resulting from international economic transactions widened by $33.4 billion, or 15.7 percent, to $246.0 billion in the second quarter of 2026, according to statistics released today by the U.S. Bureau of Economic Analysis.' },
      { text: '$246.0 billion', span: 'The U.S. current-account deficit resulting from international economic transactions widened by $33.4 billion, or 15.7 percent, to $246.0 billion in the second quarter of 2026, according to statistics released today by the U.S. Bureau of Economic Analysis.' },
      { text: 'Bureau of Economic Analysis', span: 'The U.S. current-account deficit resulting from international economic transactions widened by $33.4 billion, or 15.7 percent, to $246.0 billion in the second quarter of 2026, according to statistics released today by the U.S. Bureau of Economic Analysis.' },
      { text: 'Thursday', span: 'EMBARGOED UNTIL RELEASE AT 8:30 a.m. EDT, Thursday, September 24, 2026' },
      { text: '3.0%', span: 'The second-quarter deficit was 3.0 percent of current-dollar gross domestic product, up from 2.7 percent in the first quarter.' },
      { text: 'current-dollar gross domestic product', span: 'The second-quarter deficit was 3.0 percent of current-dollar gross domestic product, up from 2.7 percent in the first quarter.' },
      { text: '2.7%', span: 'The second-quarter deficit was 3.0 percent of current-dollar gross domestic product, up from 2.7 percent in the first quarter.' },
      { text: '$212.6 billion', span: 'The revised first-quarter deficit was $212.6 billion.' },
      { text: 'a larger deficit on goods', span: 'The $33.4 billion widening of the current-account deficit in the second quarter reflected an expanded deficit on goods that was partly offset by reduced deficits on primary (earned) income and on secondary income (current transfers).' },
    ],
  },
  {
    story: 8,
    dateline: 'WASHINGTON',
    category: 'Agriculture',
    tags: ['hogs', 'livestock', 'USDA'],
    says: [
      'Of the 74.3 million hogs and pigs, 68.4 million were market hogs, while 5.87 million were kept for breeding.',
      'Iowa hog producers accounted for the largest inventory among the states, at 24.7 million head.',
    ],
    options: [
      'US hog inventory down 2% from a year earlier, USDA says',
      'Farms had 74.3 million hogs and pigs on Sept. 1, USDA says',
      'Iowa leads US hog inventory with 24.7 million head',
    ],
    press: 0,
    lede: 'U.S. farms had 74.3 million hogs and pigs as of Sept. 1, down 2% from a year earlier but up 2% from June 1, the Agriculture Department said Thursday.',
    graf2: 'Of those, 68.4 million were market hogs and 5.87 million were kept for breeding, according to the Quarterly Hogs and Pigs report from the National Agricultural Statistics Service. Iowa had the largest inventory, at 24.7 million head.',
    quote: null,
    fixes: [
      { from: 'Washington D.C.', to: 'WASHINGTON', rule: 'datelines' },
      { from: 'Sept.1', to: 'Sept. 1', rule: 'months' },
      { from: 'United States hog inventory', to: 'US hog inventory', rule: 'us-headlines' },
    ],
    facts: [
      { text: 'US hog inventory', span: 'United States hog inventory down 2%' },
      { text: 'down 2%', span: 'As of Sept.1, there were 74.3 million hogs and pigs on U.S. farms, down 2% from September 2025 but up 2% from June 1, 2026, according to the Quarterly Hogs and Pigs report published today by the U.S. Department of Agriculture’s National Agricultural Statistics Service (NASS).' },
      { text: 'a year earlier', span: 'As of Sept.1, there were 74.3 million hogs and pigs on U.S. farms, down 2% from September 2025 but up 2% from June 1, 2026, according to the Quarterly Hogs and Pigs report published today by the U.S. Department of Agriculture’s National Agricultural Statistics Service (NASS).' },
      { text: 'USDA', span: 'As of Sept.1, there were 74.3 million hogs and pigs on U.S. farms, down 2% from September 2025 but up 2% from June 1, 2026, according to the Quarterly Hogs and Pigs report published today by the U.S. Department of Agriculture’s National Agricultural Statistics Service (NASS).' },
      { text: 'U.S. farms', span: 'As of Sept.1, there were 74.3 million hogs and pigs on U.S. farms, down 2% from September 2025 but up 2% from June 1, 2026, according to the Quarterly Hogs and Pigs report published today by the U.S. Department of Agriculture’s National Agricultural Statistics Service (NASS).' },
      { text: '74.3 million hogs and pigs', span: 'As of Sept.1, there were 74.3 million hogs and pigs on U.S. farms, down 2% from September 2025 but up 2% from June 1, 2026, according to the Quarterly Hogs and Pigs report published today by the U.S. Department of Agriculture’s National Agricultural Statistics Service (NASS).' },
      { text: 'Sept. 1', span: 'As of Sept.1, there were 74.3 million hogs and pigs on U.S. farms, down 2% from September 2025 but up 2% from June 1, 2026, according to the Quarterly Hogs and Pigs report published today by the U.S. Department of Agriculture’s National Agricultural Statistics Service (NASS).' },
      { text: 'up 2% from June 1', span: 'As of Sept.1, there were 74.3 million hogs and pigs on U.S. farms, down 2% from September 2025 but up 2% from June 1, 2026, according to the Quarterly Hogs and Pigs report published today by the U.S. Department of Agriculture’s National Agricultural Statistics Service (NASS).' },
      { text: 'Agriculture Department', span: 'As of Sept.1, there were 74.3 million hogs and pigs on U.S. farms, down 2% from September 2025 but up 2% from June 1, 2026, according to the Quarterly Hogs and Pigs report published today by the U.S. Department of Agriculture’s National Agricultural Statistics Service (NASS).' },
      { text: 'Thursday', span: 'Thu, 09/24/26 3:00 pm ET Hogs and Pigs Published' },
      { text: '68.4 million were market hogs', span: 'Of the 74.3 million hogs and pigs, 68.4 million were market hogs, while 5.87 million were kept for breeding.' },
      { text: '5.87 million were kept for breeding', span: 'Of the 74.3 million hogs and pigs, 68.4 million were market hogs, while 5.87 million were kept for breeding.' },
      { text: 'Quarterly Hogs and Pigs report', span: 'As of Sept.1, there were 74.3 million hogs and pigs on U.S. farms, down 2% from September 2025 but up 2% from June 1, 2026, according to the Quarterly Hogs and Pigs report published today by the U.S. Department of Agriculture’s National Agricultural Statistics Service (NASS).' },
      { text: 'National Agricultural Statistics Service', span: 'As of Sept.1, there were 74.3 million hogs and pigs on U.S. farms, down 2% from September 2025 but up 2% from June 1, 2026, according to the Quarterly Hogs and Pigs report published today by the U.S. Department of Agriculture’s National Agricultural Statistics Service (NASS).' },
      { text: 'Iowa had the largest inventory', span: 'Iowa hog producers accounted for the largest inventory among the states, at 24.7 million head.' },
      { text: '24.7 million head', span: 'Iowa hog producers accounted for the largest inventory among the states, at 24.7 million head.' },
      { text: 'WASHINGTON', span: '(Washington D.C., September 24, 2026)' },
    ],
  },
  {
    story: 9,
    dateline: 'ISSAQUAH, Wash.',
    category: 'Business',
    tags: ['earnings', 'retail', 'Costco'],
    says: [
      'Net sales for the quarter increased 11.2 percent, to $93.9 billion, from $84.4 billion last year.',
      'Net income for the fourth quarter was $2.998 billion, $6.75 per diluted share, compared to $2.610 billion, $5.87 per diluted share, last year.',
    ],
    options: [
      'Costco fourth-quarter net sales rise 11.2% to $93.9B',
      'Costco earns $6.75 per diluted share in fourth quarter',
      'Costco net income rises to $3B in fiscal fourth quarter',
    ],
    press: 0,
    lede: 'Costco’s fourth-quarter net sales rose 11.2% to $93.9 billion in the 16 weeks that ended Aug. 30, the company said Thursday.',
    graf2: 'Net income was $3 billion, or $6.75 per diluted share, up from $2.61 billion, or $5.87 per share, a year earlier. For the 52-week fiscal year, net sales rose 10.1% to $297.2 billion.',
    quote: null,
    fixes: [
      { from: 'fourth quarter', to: 'fourth-quarter', rule: 'hyphen' },
      { from: 'August 30, 2026', to: 'Aug. 30', rule: 'months' },
      { from: '$2.998 billion', to: '$3 billion', rule: 'decimals' },
    ],
    facts: [
      { text: 'Costco', span: 'ISSAQUAH, Wash., September 24, 2026 - Costco Wholesale Corporation (“Costco” or the “Company”) (Nasdaq: COST) today announced its operating results for the 16-week fourth quarter and the 52-week fiscal year ended August 30, 2026.' },
      { text: 'fourth-quarter', span: 'ISSAQUAH, Wash., September 24, 2026 - Costco Wholesale Corporation (“Costco” or the “Company”) (Nasdaq: COST) today announced its operating results for the 16-week fourth quarter and the 52-week fiscal year ended August 30, 2026.' },
      { text: 'net sales rose 11.2%', span: 'Net sales for the quarter increased 11.2 percent, to $93.9 billion, from $84.4 billion last year.' },
      { text: '$93.9 billion', span: 'Net sales for the quarter increased 11.2 percent, to $93.9 billion, from $84.4 billion last year.' },
      { text: '$93.9B', span: 'Net sales for the quarter increased 11.2 percent, to $93.9 billion, from $84.4 billion last year.' },
      { text: '16 weeks', span: 'ISSAQUAH, Wash., September 24, 2026 - Costco Wholesale Corporation (“Costco” or the “Company”) (Nasdaq: COST) today announced its operating results for the 16-week fourth quarter and the 52-week fiscal year ended August 30, 2026.' },
      { text: 'Aug. 30', span: 'ISSAQUAH, Wash., September 24, 2026 - Costco Wholesale Corporation (“Costco” or the “Company”) (Nasdaq: COST) today announced its operating results for the 16-week fourth quarter and the 52-week fiscal year ended August 30, 2026.' },
      { text: '$3 billion', span: 'Net income for the fourth quarter was $2.998 billion, $6.75 per diluted share, compared to $2.610 billion, $5.87 per diluted share, last year.' },
      { text: '$6.75 per diluted share', span: 'Net income for the fourth quarter was $2.998 billion, $6.75 per diluted share, compared to $2.610 billion, $5.87 per diluted share, last year.' },
      { text: '$2.61 billion', span: 'Net income for the fourth quarter was $2.998 billion, $6.75 per diluted share, compared to $2.610 billion, $5.87 per diluted share, last year.' },
      { text: '$5.87', span: 'Net income for the fourth quarter was $2.998 billion, $6.75 per diluted share, compared to $2.610 billion, $5.87 per diluted share, last year.' },
      { text: '52-week fiscal year', span: 'ISSAQUAH, Wash., September 24, 2026 - Costco Wholesale Corporation (“Costco” or the “Company”) (Nasdaq: COST) today announced its operating results for the 16-week fourth quarter and the 52-week fiscal year ended August 30, 2026.' },
      { text: 'net sales rose 10.1%', span: 'Net sales for the fiscal year increased 10.1 percent, to $297.2 billion, from $269.9 billion last year.' },
      { text: '$297.2 billion', span: 'Net sales for the fiscal year increased 10.1 percent, to $297.2 billion, from $269.9 billion last year.' },
    ],
  },
];

export const STYLE = [
  { id: 'percent', entry: 'percent', quote: 'Use the % sign with a numeral in most cases: 61% of voters, a 5.5% tariff.', label: 'Use the % sign with a numeral', url: 'https://bsky.app/profile/apstylebook.com/post/3mwlbg6wqxx2p' },
  { id: 'months', entry: 'months', quote: 'When a month is used with a specific date, abbreviate only Jan., Feb., Aug., Sept., Oct., Nov. and Dec.', label: 'Sept. 24, not September 24', url: 'https://apstylebook.com/ask_the_editors/style_guidance' },
  { id: 'times', entry: 'times', quote: 'Use figures except for noon and midnight. Use a colon to separate hours from minutes: 11 a.m., 1 p.m., 3:30 p.m., 9-11 a.m., 9 a.m. to 5 p.m.', label: 'Figures and a.m.; noon in words', url: 'https://apstylebook.com/ask_the_editors/style_guidance' },
  { id: 'times-no-00', entry: 'times', quote: 'Our style is Oct. 10 at 4 p.m. (abbreviating the month when used with a specific date, and not using the :00)', label: '10 a.m., not 10:00 AM', url: 'https://apstylebook.com/ask_the_editors/style_guidance' },
  { id: 'millions', entry: 'millions, billions', quote: 'Use figures with million, billion or trillion in all except casual uses, such as I\'d like to win a billion dollars.', label: 'Figures with million, billion', url: 'https://bsky.app/profile/apstylebook.com/post/3mameiir6pk2z' },
  { id: 'headline-money', entry: 'millions, billions', quote: 'In headlines, abbreviate only millions, billions: $5M lawsuit, $1.6B prize.', label: 'Headlines: $246B, not $246.0 billion', url: 'https://bsky.app/profile/apstylebook.com/post/3mameiksn7v2e' },
  { id: 'decimals', entry: 'millions, billions', quote: 'Do not go beyond two decimal places.', label: 'No more than two decimal places', url: 'https://bsky.app/profile/apstylebook.com/post/3mameijlyvf2e' },
  { id: 'us-headlines', entry: 'U.S.', quote: 'Use periods in the abbreviation U.S. in body copy text. In headlines, it\'s US with no periods.', label: 'U.S. in text, US in headlines', url: 'https://bsky.app/profile/apstylebook.com/post/3msvz7jk4dg2x' },
  { id: 'headline-numerals', entry: 'headlines', quote: 'Use numerals; do not spell out numbers except in casual uses or formal names: hundreds instead of 100s; Big Ten; one of the first.', label: 'Headlines use numerals: 2, not two', url: 'https://apstylebook.com/ask_the_editors/style_guidance' },
  { id: 'hyphen', entry: 'hyphen', quote: 'Use hyphens as joiners, such as for compound modifiers: small-business owner.', label: 'Compound modifier: fourth-quarter', url: 'https://bsky.app/profile/apstylebook.com/post/3lny4rddlfc2g' },
  { id: 'datelines', entry: 'datelines', quote: 'Datelines on stories should contain a place name, in capital letters, followed in most cases by the name of the state, country or territory where the city is located.', label: 'Dateline city in capital letters', url: 'https://bsky.app/profile/apstylebook.com/post/3mrq6uxf64d2u' },
  { id: 'dateline-source', entry: 'bylines and datelines', quote: 'A dateline tells the reader where we obtained the basic information for a story.', label: 'Dateline: where the facts came from', url: 'https://www.ap.org/wp-content/uploads/2026/02/THE-ASSOCIATED-PRESS-STATEMENT-OF-NEWS-VALUES-AND-PRINCIPLES-1.pdf' },
];
// ---------- END DATA ----------
