// SHED 2025 tab plan for the Qualtrics XM desk. Generated by research/build.5aa2de03.mjs from the
// Federal Reserve public-use file; every number is computed, every string verbatim or composed from
// computed values. Re-check with: node research/verify.5aa2de03.mjs <this file>
export const PLACEHOLDER = false;
export const DATASET = {
  "project": "SHED 2025",
  "title": "Economic Well-Being of U.S. Households in 2025",
  "publisher": "Board of Governors of the Federal Reserve System",
  "released": "May 13, 2026",
  "responses": 12934,
  "fielded": "October 17 through October 28, 2025",
  "panel": "Ipsos, a private consumer research firm, administered the survey using its KnowledgePanel, a nationally representative probability-based online panel.",
  "weightVar": "weight",
  "urls": {
    "data": "https://www.federalreserve.gov/consumerscommunities/files/SHED_public_use_data_2025_(CSV).zip",
    "codebook": "https://www.federalreserve.gov/consumerscommunities/files/SHED_2025codebook.pdf",
    "report": "https://www.federalreserve.gov/publications/files/2025-report-economic-well-being-us-households-202605.pdf"
  }
};
export const BANNERS = {
  "age": {
    "label": "Age",
    "var": "ppage",
    "cols": [
      {
        "letter": "A",
        "label": "18-29",
        "n": 2091
      },
      {
        "letter": "B",
        "label": "30-44",
        "n": 3002
      },
      {
        "letter": "C",
        "label": "45-59",
        "n": 2963
      },
      {
        "letter": "D",
        "label": "60+",
        "n": 4878
      }
    ]
  },
  "age_workers": {
    "label": "Age (workers)",
    "var": "ppage",
    "cols": [
      {
        "letter": "A",
        "label": "18-29",
        "n": 1463
      },
      {
        "letter": "B",
        "label": "30-44",
        "n": 2312
      },
      {
        "letter": "C",
        "label": "45-59",
        "n": 2214
      },
      {
        "letter": "D",
        "label": "60+",
        "n": 1499
      }
    ]
  }
};
export const LEARN = [
  {
    "text": "The Survey of Household Economics and Decisionmaking was fielded from October 17 through October 28, 2025.",
    "src": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-description.htm (Description of the Survey, paragraph 1)"
  },
  {
    "text": "Data for the 2025 SHED were collected by Ipsos using their online probability based KnowledgePanel.",
    "src": "https://www.federalreserve.gov/consumerscommunities/files/SHED_2025codebook.pdf (Codebook p. 1, introduction)"
  },
  {
    "text": "The SHED sample was designed to be representative of adults age 18 and older living in the United States.",
    "src": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-description.htm (Description of the Survey, Sampling and Weighting, paragraph 1)"
  },
  {
    "text": "the final sample used in the report included 12,934 respondents.",
    "src": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-description.htm (Description of the Survey, Survey Participation, paragraph 2)"
  },
  {
    "text": "The sample weight, “weight,” is most commonly used",
    "src": "https://www.federalreserve.gov/consumerscommunities/files/SHED_2025codebook.pdf (Codebook p. 1, Analysis Weights)"
  },
  {
    "text": "The design effect for the 2025 survey with the weights used in this report is 1.14",
    "src": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-description.htm (Description of the Survey, Sampling and Weighting, paragraph 4)"
  },
  {
    "text": "Item non-response for non-text questions in the 2025 SHED was handled by imputation.",
    "src": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-description.htm (Description of the Survey, Item Non-Response and Imputation)"
  },
  {
    "text": "Typically, less than 1 percent of observations were missing for each question",
    "src": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-description.htm (Description of the Survey, Item Non-Response and Imputation)"
  },
  {
    "text": "Questions with fewer than 12,295 respondents were not asked to the full sample",
    "src": "https://www.federalreserve.gov/publications/2026-supplemental-appendixes-report-economic-well-being-us-households-2025-appendix-b.htm (Appendix B, introduction)"
  },
  {
    "text": "Here and in subsequent tables and figures, percentages may not sum to 100 because of rounding.",
    "src": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-overall-financial-well-being.htm (Overall Financial Well-Being, Table 1 note)"
  },
  {
    "text": "We are not asking about purchases made directly with credit cards, layaway, or rent-to-own services.",
    "src": "https://www.federalreserve.gov/publications/2026-supplemental-appendixes-report-economic-well-being-us-households-2025-appendix-a.htm (Appendix A, Credit Section, BNPL1)"
  },
  {
    "text": "Please do not include seeing AI results from search engines.",
    "src": "https://www.federalreserve.gov/publications/2026-supplemental-appendixes-report-economic-well-being-us-households-2025-appendix-a.htm (Appendix A, Employment Section, D50)"
  }
];
export const QUEUE = [
  {
    "var": "BNPL1",
    "topic": "Buy Now, Pay Later use",
    "question": "In the past year, have you used a \"Buy Now, Pay Later\" service to buy something?",
    "base": "All respondents",
    "nBase": 12934,
    "headline": {
      "option": "Yes",
      "pct": 16
    },
    "published": {
      "pct": 16,
      "quote": "Sixteen percent of people used BNPL in the prior 12 months",
      "loc": "Credit: Buy Now, Pay Later",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-credit.htm"
    },
    "finding": "In 2025, 16 percent of adults used Buy Now, Pay Later in the prior year, and use among adults age 60 and older (9 percent) was significantly lower than among adults ages 18 to 29 (22 percent), 30 to 44 (21 percent), and 45 to 59 (17 percent).",
    "banner": "age",
    "test": "Column Stat Tests (All): pairwise two-proportion z-test, pooled, weighted p, unweighted n, 95% confidence, two-sided",
    "rows": [
      {
        "option": "Yes",
        "total": 16,
        "cells": [
          {
            "pct": 22,
            "sig": "CD"
          },
          {
            "pct": 21,
            "sig": "CD"
          },
          {
            "pct": 17,
            "sig": "D"
          },
          {
            "pct": 9,
            "sig": ""
          }
        ]
      },
      {
        "option": "No",
        "total": 84,
        "cells": [
          {
            "pct": 78,
            "sig": ""
          },
          {
            "pct": 79,
            "sig": ""
          },
          {
            "pct": 83,
            "sig": "AB"
          },
          {
            "pct": 91,
            "sig": "ABC"
          }
        ]
      }
    ]
  },
  {
    "var": "B2",
    "topic": "Financial well-being",
    "question": "Overall, which one of the following best describes how well you are managing financially these days?",
    "base": "All respondents",
    "nBase": 12934,
    "headline": {
      "option": "Living comfortably",
      "pct": 34
    },
    "published": {
      "pct": 34,
      "quote": "Near the end of 2025, 73 percent of adults reported \"doing okay\" financially (39 percent) or \"living comfortably\" (34 percent).",
      "loc": "Overall Financial Well-Being: section summary",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-overall-financial-well-being.htm"
    },
    "finding": "In 2025, 34 percent of adults said they were living comfortably, and the share among adults age 60 and older (47 percent) was significantly higher than among adults ages 18 to 29 (24 percent), 30 to 44 (28 percent), and 45 to 59 (32 percent).",
    "banner": "age",
    "test": "Column Stat Tests (All): pairwise two-proportion z-test, pooled, weighted p, unweighted n, 95% confidence, two-sided",
    "rows": [
      {
        "option": "Living comfortably",
        "total": 34,
        "cells": [
          {
            "pct": 24,
            "sig": ""
          },
          {
            "pct": 28,
            "sig": "A"
          },
          {
            "pct": 32,
            "sig": "AB"
          },
          {
            "pct": 47,
            "sig": "ABC"
          }
        ]
      },
      {
        "option": "Doing okay",
        "total": 39,
        "cells": [
          {
            "pct": 40,
            "sig": "D"
          },
          {
            "pct": 40,
            "sig": "D"
          },
          {
            "pct": 42,
            "sig": "D"
          },
          {
            "pct": 36,
            "sig": ""
          }
        ]
      },
      {
        "option": "Just getting by",
        "total": 19,
        "cells": [
          {
            "pct": 25,
            "sig": "BCD"
          },
          {
            "pct": 22,
            "sig": "CD"
          },
          {
            "pct": 18,
            "sig": "D"
          },
          {
            "pct": 13,
            "sig": ""
          }
        ]
      },
      {
        "option": "Finding it difficult to get by",
        "total": 8,
        "cells": [
          {
            "pct": 12,
            "sig": "CD"
          },
          {
            "pct": 11,
            "sig": "CD"
          },
          {
            "pct": 8,
            "sig": "D"
          },
          {
            "pct": 5,
            "sig": ""
          }
        ]
      }
    ]
  },
  {
    "var": "D50",
    "topic": "Generative AI at work",
    "question": "Did you use Generative AI at your job last month?",
    "base": "If D1A=1 (Worked last month)",
    "nBase": 7488,
    "headline": {
      "option": "Yes",
      "pct": 25
    },
    "published": {
      "pct": 25,
      "quote": "The 44 percent who agree that generative AI saves time is higher than the 25 percent of workers who said they used AI in their job in the prior month.",
      "loc": "Employment and Job Quality: Generative AI and Methods for Doing Work",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-employment-and-job-quality.htm"
    },
    "finding": "In 2025, 25 percent of workers used generative AI at their job in the prior month, and workers ages 18 to 29 (20 percent) were significantly less likely to use it than workers ages 30 to 44 (31 percent) and 45 to 59 (28 percent).",
    "banner": "age_workers",
    "test": "Column Stat Tests (All): pairwise two-proportion z-test, pooled, weighted p, unweighted n, 95% confidence, two-sided",
    "rows": [
      {
        "option": "Yes",
        "total": 25,
        "cells": [
          {
            "pct": 20,
            "sig": "D"
          },
          {
            "pct": 31,
            "sig": "ACD"
          },
          {
            "pct": 28,
            "sig": "AD"
          },
          {
            "pct": 13,
            "sig": ""
          }
        ]
      },
      {
        "option": "No",
        "total": 75,
        "cells": [
          {
            "pct": 80,
            "sig": "BC"
          },
          {
            "pct": 69,
            "sig": ""
          },
          {
            "pct": 72,
            "sig": "B"
          },
          {
            "pct": 87,
            "sig": "ABC"
          }
        ]
      }
    ]
  },
  {
    "var": "BNPL3A",
    "topic": "BNPL late fee charged",
    "question": "In the past year, have you been charged extra because you were late on a Buy Now, Pay Later payment?",
    "base": "If BNPL3=1 or refused (Has been late making BNPL payment in the past year)",
    "nBase": 487,
    "headline": {
      "option": "Yes",
      "pct": 64
    },
    "published": {
      "pct": 64,
      "quote": "Sixty-four percent of those BNPL users who were late making a payment (17 percent of those who used BNPL) said they were charged extra for being late.",
      "loc": "Credit: Buy Now, Pay Later",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-credit.htm"
    },
    "finding": "Among Buy Now, Pay Later users who paid late in the prior year, 64 percent said they were charged extra for being late."
  },
  {
    "var": "C2A",
    "topic": "Has a credit card",
    "question": "Do you currently have at least one credit card? Please do not include debit cards or prepaid cards.",
    "base": "All respondents",
    "nBase": 12934,
    "headline": {
      "option": "Yes",
      "pct": 82
    },
    "published": {
      "pct": 82,
      "quote": "Eighty-two percent of adults had a credit card in 2025, compared to a high of 84 percent in 2021 (figure 32).",
      "loc": "Credit: Credit Cards",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-credit.htm"
    },
    "finding": "In 2025, 82 percent of adults had at least one credit card."
  },
  {
    "var": "A6",
    "topic": "Credit card approval confidence",
    "question": "If you were to apply for a credit card today, how confident are you that your application would be approved?",
    "base": "All respondents",
    "nBase": 12934,
    "headline": {
      "option": "Very confident",
      "pct": 61
    },
    "published": {
      "pct": 61,
      "quote": "Sixty-one percent of adults in 2025 felt very confident their credit card application would be approved, if they were to apply, down from 65 percent in 2021 (figure 30).",
      "loc": "Credit: Credit Outcomes and Perceptions",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-credit.htm"
    },
    "finding": "In 2025, 61 percent of adults were very confident that a credit card application would be approved."
  },
  {
    "var": "A0",
    "topic": "Applied for credit",
    "question": "In the past 12 months have you applied for any credit (such as a credit card, higher credit card limit, mortgage, refinance, student loan, personal loan, or other loan)?",
    "base": "All respondents",
    "nBase": 12934,
    "headline": {
      "option": "Yes",
      "pct": 33
    },
    "published": {
      "pct": 33,
      "quote": "Thirty-three percent of adults applied for any type of credit in 2025.",
      "loc": "Credit: Credit Outcomes and Perceptions",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-credit.htm"
    },
    "finding": "In 2025, 33 percent of adults applied for some type of credit in the prior year."
  },
  {
    "var": "BK1",
    "topic": "Bank account",
    "question": "Do you and/or your spouse or partner currently have a checking, savings, or money market account?",
    "base": "All respondents",
    "nBase": 12934,
    "headline": {
      "option": "No",
      "pct": 6
    },
    "published": {
      "pct": 6,
      "quote": "Six percent of adults were \"unbanked\" in 2025, meaning neither they nor their spouse or partner had a checking, savings, or money market account (figure 27).",
      "loc": "Banking: Bank Account Ownership",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-banking.htm"
    },
    "finding": "In 2025, 6 percent of adults were unbanked, with no checking, savings, or money market account for themselves or a spouse or partner."
  },
  {
    "var": "BK2_f",
    "topic": "Paid an overdraft fee",
    "question": "In the past 12 months, did you and/or your spouse or partner: Pay an overdraft fee on a bank account",
    "base": "Display if BK1=1",
    "nBase": 12236,
    "headline": {
      "option": "Yes",
      "pct": 12
    },
    "published": {
      "pct": 12,
      "quote": "In 2025, 12 percent of adults with a bank account said they paid an overdraft fee in the prior 12 months, similar to the shares seen in recent years, but up 1 percentage point from 2021.",
      "loc": "Banking: Bank Account Ownership",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-banking.htm"
    },
    "finding": "Among adults with a bank account, 12 percent paid an overdraft fee in the prior year."
  },
  {
    "var": "EF1",
    "topic": "Three-month emergency fund",
    "question": "Have you set aside emergency or rainy day funds that would cover your expenses for 3 months in case of sickness, job loss, economic downturn, or other emergencies?",
    "base": "All respondents",
    "nBase": 12934,
    "headline": {
      "option": "Yes",
      "pct": 55
    },
    "published": {
      "pct": 55,
      "quote": "In 2025, 55 percent of adults said they had set aside money for three months of expenses in an emergency savings or \"rainy day\" fund",
      "loc": "Savings and Investments: Emergency Savings and Unexpected Expenses",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-savings-investments.htm"
    },
    "finding": "In 2025, 55 percent of adults had emergency or rainy day funds that would cover three months of expenses."
  },
  {
    "var": "K0",
    "topic": "Retirement savings on track",
    "question": "Do you think that your retirement savings plan is currently on track?",
    "base": "If (D1I ne 1) (Not retired)",
    "nBase": 8740,
    "headline": {
      "option": "Yes",
      "pct": 35
    },
    "published": {
      "pct": 35,
      "quote": "a lower 35 percent of non-retirees thought their retirement saving was on track.",
      "loc": "Savings and Investments: Retirement Savings and Investments",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-savings-investments.htm"
    },
    "finding": "Among adults who were not retired, 35 percent thought their retirement savings plan was on track, and 21 percent did not know."
  },
  {
    "var": "D52_a",
    "topic": "Generative AI saves time",
    "question": "Do you agree or disagree with the following statements about using Generative AI for your job? It saves time",
    "base": "If D50=1 (Used Generative AI for a job)",
    "nBase": 1850,
    "headline": {
      "option": "Agree",
      "pct": 81
    },
    "published": {
      "pct": 81,
      "quote": "Eighty-one percent of people who used generative AI agreed that it saves them time.",
      "loc": "Executive Summary: section summary",
      "url": "https://www.federalreserve.gov/publications/2026-economic-well-being-of-us-households-in-2025-executive-summary.htm"
    },
    "finding": "Among workers who used generative AI at their job in the prior month, 81 percent agreed that it saves time."
  }
];
