// gdocs-data.js: GENERATED by /tmp/cw-ad.cda60abe/gen-data.mjs from research/research.json.
// Do not edit by hand: re-run the generator. Everything the Google Docs copy deck (gdocs.js) shows that is not UI
// chrome comes from here. Specs, style-guide rules, the live App Store listing and the product facts behind every
// drafted line are verbatim from the pages in each record's url (retrieved 2026-09-29); the request comments,
// the drafted lines and the replies are the ad's own copy, written from those facts (`facts` = research.json facts
// indexes). No character or word count is stored: the desk computes every count from the string at runtime.
// Copy rules checked at generation: no em or en dashes, no hype words, prices only "from" / "starts at", every line
// within its limit, subject lines within 9 words.

export const DATA_SOURCE = "research";
export const AS_OF = "2026-09-29";
export const CLIENT = 'Mailchimp';
export const DOC_TITLE = 'Mailchimp copy deck';
export const USER = { name: 'Sam R.', initial: 'S' };

// the 12 deliverables, one Document tab each; the three worked on the page come first (main 0, 1, 2)
export const DELIVERABLES = [
 {
  "id": "rsa-headlines",
  "main": 0,
  "tab": "Search ad headlines",
  "deck": "Google Ads · Headlines",
  "h1": "Google Ads · Responsive search ad headlines",
  "platform": "Google Ads",
  "field": "Responsive search ad headline",
  "team": "Growth team",
  "teamInitial": "G",
  "teamHue": "#1e8e3e",
  "request": "Need 6 headlines for the pricing search campaign, 30 characters max each. No exclamation points.",
  "limit": 30,
  "unit": "characters",
  "limitLabel": "30 characters",
  "limitSrc": "https://support.google.com/google-ads/answer/7684791?hl=en",
  "specs": [
   {
    "label": "Spec",
    "text": "The headline fields for responsive search ads support up to 30 characters.",
    "url": "https://support.google.com/google-ads/answer/7684791?hl=en",
    "host": "support.google.com"
   }
  ],
  "extra": null,
  "checks": [
   "30 characters max",
   "No exclamation points",
   "Mailchimp voice"
  ],
  "reply": "Drafted 6 headlines, all under 30 characters. Sources below.",
  "lines": [
   {
    "label": "Headline 1",
    "text": "Free for under 250 contacts",
    "limit": 30,
    "wordLimit": null,
    "facts": [
     3
    ]
   },
   {
    "label": "Headline 2",
    "text": "Standard plan: 14-day trial",
    "limit": 30,
    "wordLimit": null,
    "facts": [
     9
    ]
   },
   {
    "label": "Headline 3",
    "text": "Essentials from $13 a month",
    "limit": 30,
    "wordLimit": null,
    "facts": [
     6
    ]
   },
   {
    "label": "Headline 4",
    "text": "Email and SMS marketing",
    "limit": 30,
    "wordLimit": null,
    "facts": [
     0,
     15
    ]
   },
   {
    "label": "Headline 5",
    "text": "Integrates with 300+ apps",
    "limit": 30,
    "wordLimit": null,
    "facts": [
     2,
     19
    ]
   },
   {
    "label": "Headline 6",
    "text": "Premium: unlimited contacts",
    "limit": 30,
    "wordLimit": null,
    "facts": [
     16
    ]
   }
  ],
  "sources": [
   {
    "line": 0,
    "use": "Free for under 250 contacts",
    "q": "Under 250 contacts? It's free.",
    "fact": 3,
    "url": "https://mailchimp.com/pricing/marketing/",
    "host": "mailchimp.com"
   },
   {
    "line": 1,
    "use": "Standard plan: 14-day trial",
    "q": "The free trial of Standard or Essentials lasts for 14 days.",
    "fact": 9,
    "url": "https://mailchimp.com/pricing/marketing/",
    "host": "mailchimp.com"
   },
   {
    "line": 2,
    "use": "Essentials from $13 a month",
    "q": "Then, starts at $13 /month",
    "fact": 6,
    "url": "https://mailchimp.com/pricing/marketing/",
    "host": "mailchimp.com"
   },
   {
    "line": 3,
    "use": "Email and SMS marketing",
    "q": "Email & SMS marketing minus the learning curve",
    "fact": 0,
    "url": "https://mailchimp.com/",
    "host": "mailchimp.com"
   },
   {
    "line": 4,
    "use": "Integrates with 300+ apps",
    "q": "One marketing platform to unite 300+ apps",
    "fact": 2,
    "url": "https://mailchimp.com/",
    "host": "mailchimp.com"
   },
   {
    "line": 5,
    "use": "Premium: unlimited contacts",
    "q": "Our most advanced tools, unlimited contacts",
    "fact": 16,
    "url": "https://mailchimp.com/pricing/marketing/",
    "host": "mailchimp.com"
   }
  ]
 },
 {
  "id": "email-subject",
  "main": 1,
  "tab": "Subject lines",
  "deck": "Email · Subject lines",
  "h1": "Email · Subject lines and preview text",
  "platform": "Mailchimp email",
  "field": "Subject line (+ preview text)",
  "team": "Lifecycle team",
  "teamInitial": "L",
  "teamHue": "#c5221f",
  "request": "Need 3 subject lines for the plans email, sentence case, 60 characters and 9 words max. Plus preview text.",
  "limit": 60,
  "unit": "characters",
  "limitLabel": "60 characters, 9 words",
  "limitSrc": "https://mailchimp.com/help/best-practices-for-email-subject-lines/",
  "specs": [
   {
    "label": "Spec",
    "text": "We recommend you use no more than 9 words and 60 characters.",
    "url": "https://mailchimp.com/help/best-practices-for-email-subject-lines/",
    "host": "mailchimp.com"
   }
  ],
  "extra": null,
  "checks": [
   "60 characters max",
   "9 words max",
   "Sentence case"
  ],
  "reply": "Drafted 3 subject lines, all under 9 words. Sources below.",
  "lines": [
   {
    "label": "Subject line 1",
    "text": "Under 250 contacts? Mailchimp is free",
    "limit": 60,
    "wordLimit": 9,
    "facts": [
     3
    ]
   },
   {
    "label": "Subject line 2",
    "text": "Try the Standard plan free for 14 days",
    "limit": 60,
    "wordLimit": 9,
    "facts": [
     9
    ]
   },
   {
    "label": "Subject line 3",
    "text": "Connect Mailchimp to 300+ apps",
    "limit": 60,
    "wordLimit": 9,
    "facts": [
     2
    ]
   },
   {
    "label": "Preview text",
    "text": "Use core features to manage early growth.",
    "limit": null,
    "wordLimit": null,
    "facts": [
     4
    ]
   }
  ],
  "sources": [
   {
    "line": 0,
    "use": "Under 250 contacts? Mailchimp is free",
    "q": "Under 250 contacts? It's free.",
    "fact": 3,
    "url": "https://mailchimp.com/pricing/marketing/",
    "host": "mailchimp.com"
   },
   {
    "line": 1,
    "use": "Try the Standard plan free for 14 days",
    "q": "The free trial of Standard or Essentials lasts for 14 days.",
    "fact": 9,
    "url": "https://mailchimp.com/pricing/marketing/",
    "host": "mailchimp.com"
   },
   {
    "line": 2,
    "use": "Connect Mailchimp to 300+ apps",
    "q": "One marketing platform to unite 300+ apps",
    "fact": 2,
    "url": "https://mailchimp.com/",
    "host": "mailchimp.com"
   },
   {
    "line": 3,
    "use": "Use core features to manage early growth.",
    "q": "Use core features to manage early growth.",
    "fact": 4,
    "url": "https://mailchimp.com/pricing/marketing/",
    "host": "mailchimp.com"
   }
  ]
 },
 {
  "id": "appstore-subtitle",
  "main": 2,
  "tab": "App Store subtitle",
  "deck": "App Store · Subtitle",
  "h1": "App Store · Subtitle and promotional text",
  "platform": "App Store (iOS)",
  "field": "Subtitle (+ promotional text)",
  "team": "App team",
  "teamInitial": "A",
  "teamHue": "#1a73e8",
  "request": "New subtitle for the iOS app, 30 characters max. Also promotional text, 170 max.",
  "limit": 30,
  "unit": "characters",
  "limitLabel": "30 characters",
  "limitSrc": "https://developer.apple.com/help/app-store-connect/reference/app-information/app-information",
  "specs": [
   {
    "label": "Subtitle",
    "text": "This can’t be longer than 30 characters.",
    "url": "https://developer.apple.com/help/app-store-connect/reference/app-information/app-information",
    "host": "developer.apple.com"
   },
   {
    "label": "Promotional text",
    "text": "This property can’t be longer than 170 characters.",
    "url": "https://developer.apple.com/help/app-store-connect/reference/app-information/platform-version-information",
    "host": "developer.apple.com"
   }
  ],
  "extra": {
   "label": "Live listing",
   "text": "Mailchimp Email Marketing · 4.9 out of 5, 52K Ratings",
   "url": "https://apps.apple.com/us/app/mailchimp-email-marketing/id366794783",
   "host": "apps.apple.com"
  },
  "checks": [
   "Subtitle: 30 max",
   "Promotional text: 170 max",
   "Mailchimp voice"
  ],
  "reply": "Subtitle at 29 of 30, promo text at 133 of 170. Sources below.",
  "lines": [
   {
    "label": "Subtitle",
    "text": "Email campaigns and analytics",
    "limit": 30,
    "wordLimit": null,
    "facts": [
     26,
     25
    ],
    "was": "Email, Analytics, Contacts"
   },
   {
    "label": "Promotional text",
    "text": "Add contacts from your phone or scan business cards. Resend to non-openers in one click, and track results for all of your campaigns.",
    "limit": 170,
    "wordLimit": null,
    "facts": [
     23,
     24,
     25
    ]
   }
  ],
  "sources": [
   {
    "line": 0,
    "use": "Email campaigns",
    "q": "Create, edit and send email marketing campaigns",
    "fact": 26,
    "url": "https://apps.apple.com/us/app/mailchimp-email-marketing/id366794783",
    "host": "apps.apple.com"
   },
   {
    "line": 0,
    "use": "analytics",
    "q": "Track results for all of your campaigns",
    "fact": 25,
    "url": "https://apps.apple.com/us/app/mailchimp-email-marketing/id366794783",
    "host": "apps.apple.com"
   },
   {
    "line": 1,
    "use": "scan business cards",
    "q": "Add contacts from your device, scan business cards",
    "fact": 23,
    "url": "https://apps.apple.com/us/app/mailchimp-email-marketing/id366794783",
    "host": "apps.apple.com"
   },
   {
    "line": 1,
    "use": "Resend to non-openers in one click",
    "q": "With one-click Resend to Non-Openers",
    "fact": 24,
    "url": "https://apps.apple.com/us/app/mailchimp-email-marketing/id366794783",
    "host": "apps.apple.com"
   }
  ]
 },
 {
  "id": "rsa-descriptions",
  "main": null,
  "tab": "Search ad descriptions",
  "deck": "Google Ads · Descriptions",
  "h1": "",
  "platform": "Google Ads",
  "field": "Responsive search ad description",
  "team": "Growth team",
  "teamInitial": "G",
  "teamHue": "#1e8e3e",
  "request": "2 descriptions for the same ad group. 90 characters max each.",
  "limit": 90,
  "unit": "characters",
  "limitLabel": "90 characters",
  "limitSrc": "https://support.google.com/google-ads/answer/7684791?hl=en",
  "specs": [],
  "extra": null,
  "checks": [],
  "reply": "",
  "lines": [
   {
    "label": "Responsive search ad description 1",
    "text": "Under 250 contacts? It's free. Move to a paid plan as you scale.",
    "limit": 90,
    "wordLimit": null,
    "facts": [
     3,
     4
    ]
   },
   {
    "label": "Responsive search ad description 2",
    "text": "Try the Standard plan free for 14 days. Cancel or downgrade at any time.",
    "limit": 90,
    "wordLimit": null,
    "facts": [
     9,
     10
    ]
   }
  ],
  "sources": []
 },
 {
  "id": "meta-primary",
  "main": null,
  "tab": "Meta primary text",
  "deck": "Meta · Primary text",
  "h1": "",
  "platform": "Meta (Facebook Feed)",
  "field": "Primary text",
  "team": "Social team",
  "teamInitial": "S",
  "teamHue": "#e37400",
  "request": "Primary text for the Facebook Feed ad. Aim for 50 to 150 characters.",
  "limit": 150,
  "unit": "characters",
  "limitLabel": "50 to 150 characters",
  "limitSrc": "https://www.facebook.com/business/ads-guide/image/facebook-feed",
  "specs": [],
  "extra": null,
  "checks": [],
  "reply": "",
  "lines": [
   {
    "label": "Primary text",
    "text": "Under 250 contacts? Mailchimp is free. Connect 300+ apps now, and move to a paid plan as you scale.",
    "limit": 150,
    "wordLimit": null,
    "facts": [
     3,
     2,
     4
    ]
   }
  ],
  "sources": []
 },
 {
  "id": "meta-headline",
  "main": null,
  "tab": "Meta headline",
  "deck": "Meta · Headline",
  "h1": "",
  "platform": "Meta (Facebook Feed)",
  "field": "Headline",
  "team": "Social team",
  "teamInitial": "S",
  "teamHue": "#e37400",
  "request": "Headline for the same ad. Meta recommends 27 characters.",
  "limit": 27,
  "unit": "characters",
  "limitLabel": "27 characters",
  "limitSrc": "https://www.facebook.com/business/ads-guide/image/facebook-feed",
  "specs": [],
  "extra": null,
  "checks": [],
  "reply": "",
  "lines": [
   {
    "label": "Headline",
    "text": "Try Standard for 14 days",
    "limit": 27,
    "wordLimit": null,
    "facts": [
     9
    ]
   }
  ],
  "sources": []
 },
 {
  "id": "linkedin-intro",
  "main": null,
  "tab": "LinkedIn intro text",
  "deck": "LinkedIn · Intro text",
  "h1": "",
  "platform": "LinkedIn",
  "field": "Introductory text (single image ad)",
  "team": "Social team",
  "teamInitial": "S",
  "teamHue": "#e37400",
  "request": "Intro text for the Premium LinkedIn ad. Keep it under 150 characters so it does not truncate.",
  "limit": 150,
  "unit": "characters",
  "limitLabel": "150 characters",
  "limitSrc": "https://www.linkedin.com/help/lms/answer/a426534",
  "specs": [],
  "extra": null,
  "checks": [],
  "reply": "",
  "lines": [
   {
    "label": "Introductory text (single image ad)",
    "text": "Premium includes unlimited contacts and our most advanced tools, plus phone and priority support. Built for teams.",
    "limit": 150,
    "wordLimit": null,
    "facts": [
     16,
     28
    ]
   }
  ],
  "sources": []
 },
 {
  "id": "x-post",
  "main": null,
  "tab": "X post",
  "deck": "X · Post",
  "h1": "",
  "platform": "X",
  "field": "Post copy (with link)",
  "team": "Social team",
  "teamInitial": "S",
  "teamHue": "#e37400",
  "request": "One X post for the nonprofit discount. 257 characters max, since it carries a link.",
  "limit": 257,
  "unit": "characters",
  "limitLabel": "257 characters",
  "limitSrc": "https://help.x.com/en/business-and-advertising/creative-ad-specifications",
  "specs": [],
  "extra": null,
  "checks": [],
  "reply": "",
  "lines": [
   {
    "label": "Post copy (with link)",
    "text": "Nonprofits and charities get 15% off Mailchimp. Sign up for a free account, then contact our Billing team with your username and a link to your website.",
    "limit": 257,
    "wordLimit": null,
    "facts": [
     14
    ]
   }
  ],
  "sources": []
 },
 {
  "id": "play-short",
  "main": null,
  "tab": "Play short description",
  "deck": "Google Play · Short description",
  "h1": "",
  "platform": "Google Play",
  "field": "Short description",
  "team": "App team",
  "teamInitial": "A",
  "teamHue": "#1a73e8",
  "request": "Short description for the Android listing. 80 characters max.",
  "limit": 80,
  "unit": "characters",
  "limitLabel": "80 characters",
  "limitSrc": "https://support.google.com/googleplay/android-developer/answer/9859152?hl=en",
  "specs": [],
  "extra": null,
  "checks": [],
  "reply": "",
  "lines": [
   {
    "label": "Short description",
    "text": "Create and send email campaigns, then track results from your phone.",
    "limit": 80,
    "wordLimit": null,
    "facts": [
     26,
     25
    ]
   }
  ],
  "sources": []
 },
 {
  "id": "sms",
  "main": null,
  "tab": "SMS message",
  "deck": "SMS · Message",
  "h1": "",
  "platform": "Mailchimp SMS",
  "field": "SMS body (GSM)",
  "team": "Lifecycle team",
  "teamInitial": "L",
  "teamHue": "#c5221f",
  "request": "One SMS for the trial push. 160 characters max, opt-out included, plain characters only.",
  "limit": 160,
  "unit": "characters",
  "limitLabel": "160 characters",
  "limitSrc": "https://mailchimp.com/help/about-sms-marketing/",
  "specs": [],
  "extra": null,
  "checks": [],
  "reply": "",
  "lines": [
   {
    "label": "SMS body (GSM)",
    "text": "Mailchimp: try the Standard plan free for 14 days, then it starts at $20/month. Cancel or downgrade any time. Reply STOP to opt out.",
    "limit": 160,
    "wordLimit": null,
    "facts": [
     9,
     7,
     10
    ]
   }
  ],
  "sources": []
 },
 {
  "id": "youtube-bumper",
  "main": null,
  "tab": "YouTube bumper",
  "deck": "YouTube · Bumper script",
  "h1": "",
  "platform": "YouTube",
  "field": "Bumper ad voiceover script (6 seconds)",
  "team": "Brand team",
  "teamInitial": "B",
  "teamHue": "#9334e6",
  "request": "Script for a 6-second bumper. About 12 words, one idea.",
  "limit": 6,
  "unit": "seconds",
  "limitLabel": "6 seconds",
  "limitSrc": "https://support.google.com/google-ads/answer/7159363?hl=en",
  "specs": [],
  "extra": null,
  "checks": [],
  "reply": "",
  "lines": [
   {
    "label": "Bumper ad voiceover script (6 seconds)",
    "text": "Under 250 contacts? Mailchimp is free. Upgrade as you scale.",
    "limit": null,
    "wordLimit": null,
    "facts": [
     3,
     4
    ]
   }
  ],
  "sources": []
 },
 {
  "id": "sitelink",
  "main": null,
  "tab": "Sitelink",
  "deck": "Google Ads · Sitelink",
  "h1": "",
  "platform": "Google Ads",
  "field": "Sitelink text",
  "team": "Growth team",
  "teamInitial": "G",
  "teamHue": "#1e8e3e",
  "request": "Sitelink text for the nonprofit page. 25 characters max.",
  "limit": 25,
  "unit": "characters",
  "limitLabel": "25 characters",
  "limitSrc": "https://support.google.com/google-ads/answer/2375416?hl=en",
  "specs": [],
  "extra": null,
  "checks": [],
  "reply": "",
  "lines": [
   {
    "label": "Sitelink text",
    "text": "15% off for nonprofits",
    "limit": 25,
    "wordLimit": null,
    "facts": [
     14
    ]
   }
  ],
  "sources": []
 }
];

// the "Style guide" tab: verbatim rules from the Mailchimp Content Style Guide (CC BY-NC 4.0, quoted in short excerpts)
export const STYLE = {
 "title": "Mailchimp Content Style Guide",
 "url": "https://styleguide.mailchimp.com/",
 "licence": "© Mailchimp 2023. This work is available under a Creative Commons Attribution-NonCommercial 4.0 International License.",
 "rules": [
  {
   "ix": 0,
   "section": "Voice and tone",
   "head": "",
   "text": "We are plainspoken.",
   "url": "https://styleguide.mailchimp.com/voice-and-tone/"
  },
  {
   "ix": 1,
   "section": "Voice and tone",
   "head": "",
   "text": "We are genuine.",
   "url": "https://styleguide.mailchimp.com/voice-and-tone/"
  },
  {
   "ix": 2,
   "section": "Voice and tone",
   "head": "",
   "text": "We are translators.",
   "url": "https://styleguide.mailchimp.com/voice-and-tone/"
  },
  {
   "ix": 3,
   "section": "Voice and tone",
   "head": "",
   "text": "Our humor is dry.",
   "url": "https://styleguide.mailchimp.com/voice-and-tone/"
  },
  {
   "ix": 6,
   "section": "Voice and tone",
   "head": "Avoid slang and jargon",
   "text": "Write in plain English.",
   "url": "https://styleguide.mailchimp.com/voice-and-tone/"
  },
  {
   "ix": 7,
   "section": "Grammar and mechanics",
   "head": "",
   "text": "Be concise. Use short words and sentences. Avoid unnecessary modifiers.",
   "url": "https://styleguide.mailchimp.com/grammar-and-mechanics/"
  },
  {
   "ix": 9,
   "section": "Grammar and mechanics",
   "head": "",
   "text": "Use active voice. Avoid passive voice.",
   "url": "https://styleguide.mailchimp.com/grammar-and-mechanics/"
  },
  {
   "ix": 15,
   "section": "Grammar and mechanics",
   "head": "",
   "text": "Use exclamation points sparingly, and never more than one at a time.",
   "url": "https://styleguide.mailchimp.com/grammar-and-mechanics/"
  },
  {
   "ix": 19,
   "section": "Grammar and mechanics",
   "head": "",
   "text": "Always capitalize the first “M” and lowercase the “c” in Mailchimp.",
   "url": "https://styleguide.mailchimp.com/grammar-and-mechanics/"
  },
  {
   "ix": 26,
   "section": "Writing email newsletters",
   "head": "",
   "text": "Subject lines should be in sentence case.",
   "url": "https://styleguide.mailchimp.com/writing-email-newsletters/"
  },
  {
   "ix": 29,
   "section": "Word list",
   "head": "",
   "text": "email (never hyphenate, never capitalize unless it begins a sentence)",
   "url": "https://styleguide.mailchimp.com/word-list/"
  },
  {
   "ix": 31,
   "section": "Word list",
   "head": "",
   "text": "automagical (we used to say this a lot, and we’re embarrassed about it)",
   "url": "https://styleguide.mailchimp.com/word-list/"
  }
 ]
};

// the HUD's "What the style guide says" chips (sentences from STYLE rules 7, 9 and 6)
export const CHIPS = ["Be concise.","Use active voice.","Write in plain English."];
