// Listing data for the "Your 10 dresses" lookbook.
// All sellers and brands are fictional. Ratings, review counts and prices are representative
// marketplace values, not scraped records. Photos are sourced stock, credited in CREDITS.txt.

export const query = {
  site: 'amazon.com',
  department: "Women's Dresses",
  searched: '2,140',
  filtered: '318',
  asked: 'Find me 10 dresses on amazon to pick from',
};

export const filters = [
  'All styles',
  'Wrap',
  'Slip',
  'Sweater',
  'Shirt dress',
  'Maxi',
];

export const note =
  'Ten dresses out of 2,140 searched. Each one held 4.3 stars or better with a Prime badge. Shortlisted dresses collect in the tray below, with the list ready to open on Amazon.';

export const items = [
  {
    img: './img/look-01.webp',
    title: 'Bloomfield Tiered Floral Midi Dress',
    price: '$54.99',
    meta: '4.6 · 2,318 ratings · Prime',
    source: 'amazon',
    n: 1,
    style: 'Floral midi',
    brand: 'Petal & Pine',
    rating: 4.6,
    reviews: '2,318',
    prime: true,
    badge: 'Best seller',
    fabric: 'Cotton blend poplin. Smocked back, tiered skirt, lined.',
    fit: 'Fitted waist, relaxed skirt',
    why: 'The smocked back does the work, so the waist sits right without a belt.',
    delivery: 'FREE delivery Thu',
    colors: [
      { name: 'Rose garden', hex: '#c0737f' },
      { name: 'Ink navy', hex: '#2c3a52' },
      { name: 'Sage', hex: '#7d8a63' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    soldOut: ['XS'],
    chosen: 1,
    size: 'S',
  },
  {
    img: './img/look-02.webp',
    title: 'Aurelia V Neck Wrap Dress',
    price: '$42.50',
    meta: '4.5 · 4,102 ratings · Prime',
    source: 'amazon',
    n: 2,
    style: 'Wrap',
    brand: 'Aurelia',
    rating: 4.5,
    reviews: '4,102',
    prime: true,
    badge: 'Prime',
    fabric: 'Rayon crepe with a true wrap front and a self tie waist.',
    fit: 'True to size, hidden snap',
    why: 'A true wrap front with a hidden snap, so it stays closed on the move.',
    delivery: 'FREE delivery Fri',
    colors: [
      { name: 'Tangerine', hex: '#e07a2f' },
      { name: 'Black', hex: '#221f1c' },
      { name: 'Plum', hex: '#6a3a52' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    soldOut: [],
    chosen: 0,
    size: 'M',
  },
  {
    img: './img/look-03.webp',
    title: 'Marlowe Pleated Polka Dot Midi Dress',
    price: '$49.99',
    meta: '4.4 · 1,764 ratings · Prime',
    source: 'amazon',
    n: 3,
    style: 'Polka dot',
    brand: 'Marlowe Row',
    rating: 4.4,
    reviews: '1,764',
    prime: true,
    badge: 'Prime',
    fabric: 'Soft knit bodice, pleated skirt, elasticated waist.',
    fit: 'Runs small, size up',
    why: 'Pleats run through the skirt, so it falls straight instead of catching.',
    delivery: 'FREE delivery Sat',
    colors: [
      { name: 'Ivory dot', hex: '#23201d' },
      { name: 'Rose dot', hex: '#b5716f' },
      { name: 'Cobalt dot', hex: '#2f4d86' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    soldOut: ['XL'],
    chosen: 1,
    size: 'M',
  },
  {
    img: './img/look-04.webp',
    title: 'Nordvik Ribbed Knit Sweater Dress',
    price: '$38.99',
    meta: '4.7 · 6,251 ratings · Prime',
    source: 'amazon',
    n: 4,
    style: 'Sweater',
    brand: 'Nordvik',
    rating: 4.7,
    reviews: '6,251',
    prime: true,
    badge: 'Top rated',
    fabric: 'Ribbed viscose blend. Long sleeve, mid calf, side slit.',
    fit: 'Body skimming',
    why: 'Holds its shape past a full day of wear, per 6,251 reviews.',
    delivery: 'FREE delivery Thu',
    colors: [
      { name: 'Ash', hex: '#8e8b86' },
      { name: 'Walnut', hex: '#5b4636' },
      { name: 'Cream', hex: '#e6ddcd' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    soldOut: [],
    chosen: 1,
    size: 'S',
  },
  {
    img: './img/look-05.webp',
    title: 'Cove Satin V Neck Slip Dress',
    price: '$35.99',
    meta: '4.3 · 918 ratings · Prime',
    source: 'amazon',
    n: 5,
    style: 'Slip',
    brand: 'Cove & Cotton',
    rating: 4.3,
    reviews: '918',
    prime: true,
    badge: 'Prime',
    fabric: 'Satin with bias cut. Adjustable straps, unlined skirt.',
    fit: 'Bias cut, true to size',
    why: 'Bias cut satin that skims, with a hem you can take up yourself.',
    delivery: 'FREE delivery Fri',
    colors: [
      { name: 'Ivory', hex: '#efe6d8' },
      { name: 'Slate', hex: '#5a6270' },
      { name: 'Cinnamon', hex: '#a05a3c' },
    ],
    sizes: ['XS', 'S', 'M', 'L'],
    soldOut: ['XS'],
    chosen: 2,
    size: 'S',
  },
  {
    img: './img/look-06.webp',
    title: 'Fernwell Lace Midi Dress',
    price: '$68.00',
    meta: '4.8 · 1,207 ratings · Prime',
    source: 'amazon',
    n: 6,
    style: 'Lace',
    brand: 'Fernwell',
    rating: 4.8,
    reviews: '1,207',
    prime: true,
    badge: 'Wedding guest',
    fabric: 'Floral lace over solid lining. Short sleeve, mid calf.',
    fit: 'True to size',
    why: 'Lace over lining to the knee, the one most saved for weddings.',
    delivery: 'FREE delivery Sat',
    colors: [
      { name: 'Antique ivory', hex: '#e4d8c3' },
      { name: 'Dusty rose', hex: '#c99a97' },
      { name: 'Midnight', hex: '#22252e' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    soldOut: [],
    chosen: 2,
    size: 'M',
  },
  {
    img: './img/look-07.webp',
    title: 'Sable Row Belted Crepe Sheath Dress',
    price: '$59.50',
    meta: '4.5 · 3,048 ratings · Prime',
    source: 'amazon',
    n: 7,
    style: 'Sheath',
    brand: 'Sable Row',
    rating: 4.5,
    reviews: '3,048',
    prime: true,
    badge: 'Work',
    fabric: 'Stretch crepe. Three quarter sleeve, matching fabric belt.',
    fit: 'Slim, size up for room',
    why: 'Work week crepe that does not crease through a commute.',
    delivery: 'FREE delivery Thu',
    colors: [
      { name: 'Olive grey', hex: '#6c6a58' },
      { name: 'Ink', hex: '#1f2124' },
      { name: 'Burgundy', hex: '#5e2531' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    soldOut: [],
    chosen: 1,
    size: 'M',
  },
  {
    img: './img/look-08.webp',
    title: 'Indigo Field Belted Print Midi Dress',
    price: '$46.90',
    meta: '4.4 · 2,673 ratings · Prime',
    source: 'amazon',
    n: 8,
    style: 'Print',
    brand: 'Indigo Field',
    rating: 4.4,
    reviews: '2,673',
    prime: true,
    badge: 'Prime',
    fabric: 'Lightweight weave, tiled print, fabric belt, side pockets.',
    fit: 'Relaxed through the waist',
    why: 'Pockets, a tie belt, and a print that hides a lunch spill.',
    delivery: 'FREE delivery Fri',
    colors: [
      { name: 'Blue tile', hex: '#3f6d94' },
      { name: 'Clay tile', hex: '#a9603f' },
      { name: 'Green tile', hex: '#4d7a5c' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    soldOut: ['XXL'],
    chosen: 1,
    size: 'L',
  },
  {
    img: './img/look-09.webp',
    title: 'Linden Bell Sleeve Linen Blend Dress',
    price: '$57.99',
    meta: '4.6 · 1,455 ratings · Prime',
    source: 'amazon',
    n: 9,
    style: 'Linen blend',
    brand: 'Linden Lane',
    rating: 4.6,
    reviews: '1,455',
    prime: true,
    badge: 'Prime',
    fabric: 'Linen and viscose blend. Bell sleeve, tiered hem, side zip.',
    fit: 'Loose, cinch with the belt',
    why: 'Linen blend that breathes, cut loose with a removable belt.',
    delivery: 'FREE delivery Sat',
    colors: [
      { name: 'Blush', hex: '#d8a89a' },
      { name: 'River blue', hex: '#7d99a8' },
      { name: 'Wheat', hex: '#cbb083' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    soldOut: [],
    chosen: 0,
    size: 'M',
  },
  {
    img: './img/look-10.webp',
    title: 'Palma Palm Print Shirt Dress',
    price: '$44.75',
    meta: '4.3 · 5,096 ratings · Prime',
    source: 'amazon',
    n: 10,
    style: 'Shirt dress',
    brand: 'Palma',
    rating: 4.3,
    reviews: '5,096',
    prime: true,
    badge: 'Prime',
    fabric: 'Button front, collar, tie belt, two patch pockets.',
    fit: 'Straight, belt to shape',
    why: 'Button front shirt dress that wears open over jeans as well.',
    delivery: 'FREE delivery Thu',
    colors: [
      { name: 'Lagoon', hex: '#2f6d78' },
      { name: 'Terracotta', hex: '#b9603c' },
      { name: 'Leaf', hex: '#4f7a3f' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    soldOut: ['XS'],
    chosen: 1,
    size: 'M',
  },
];